Fix dhcp in iface_start_ifconfig: It was re-using the variable ${i} which would result in the following error:     /sbin/runscript.sh: line 441: ((: 16.141.88.153: syntax error     in expression (error token is ".141.88.153")
Use vlan_IFACE instead of iface_IFACE_vlans in net.eth0 for more
consistent vlan configuration.  Thanks to robbat2 in bug 55394
(not fully resolved)

Add example for checking if root filesystem is NFS-mounted via
predown function in conf.d/net for bug 53104.  This might be
better integrated at some point into net.eth0

svn path=/trunk/; revision=518

diff --git a/etc/conf.d/net b/etc/conf.d/net
--- a/etc/conf.d/net
+++ b/etc/conf.d/net
@@ -53,6 +53,12 @@
 #	"default gw 192.168.0.1"
 #)
 
+# VLAN support - emerge net-misc/vconfig 
+# Please ensure your VLAN IDs are NOT zero-padded
+#vlans_eth0="1 2"
+#ifconfig_eth0_1=( "dhcp" )
+#ifconfig_eth0_2=( "172.16.2.1 broadcast 172.16.3.255 netmask 255.255.254.0" )
+
 
 ##############################################################################
 #   OLD-STYLE IFACE examples (deprecated)
@@ -88,6 +94,12 @@
 #broadcast_eth0="192.168.0.255 192.168.0.255"
 #netmask_eth0="255.255.255.0 255.255.255.0"
 
+# VLAN support - emerge net-misc/vconfig
+# Please ensure your VLAN IDs are NOT zero-padded
+#vlans_eth0="1 2"
+#iface_eth0_1="dhcp"
+#iface_eth0_2="172.16.2.1 broadcast 172.16.3.255 netmask 255.255.254.0"
+
 
 ##############################################################################
 #   IPROUTE2-STYLE CONFIGURATION
@@ -96,6 +108,8 @@
 #   addresses.  This style is very useful if you are building an
 #   advanced linux router or using VRRP For more information on how to
 #   use the iproute2 command have a look at the ip(8) man page.
+#
+#   NOTE: You must emerge sys-apps/iproute2 to use this configuration
 ##############################################################################
 
 # To use DHCP on eth0, simply uncomment the following line:
@@ -121,6 +135,12 @@
 #iproute_eth0=(
 #	"default via 192.168.0.1"
 #)
+
+# VLAN support - emerge net-misc/vconfig
+# Please ensure your VLAN IDs are NOT zero-padded
+#vlans_eth0="1 2"
+#ipaddr_eth0_1=( "dhcp" )
+#ipaddr_eth0_2=( "172.16.2.1/23 brd 172.16.3.255" )
 
 
 ##############################################################################
@@ -160,10 +180,9 @@
 #
 #predown() {
 #	# Test to make sure the root filesystem is not mounted via NFS.
-#	# Interface ($1) is ignored but could also be tested.  I'm not
-#	# sure this is quite the right test, will be able to update when I
-#	# hear back from the submitter on bug 53104
-#	if grep -q ' / nfs ' /proc/mounts; then
+#	# Interface ($1) is ignored but could also be tested if you know
+#	# what interface is providing NFS root.
+#	if grep -q ' / nfs' /proc/mounts; then
 #		ewarn "Root is NFS mounted, aborting deconfiguration of $1"
 #		return 1
 #	fi
@@ -182,3 +201,115 @@
 #	# This function is mostly here for completeness... I haven't
 #	# thought of anything nifty to do with it yet ;-)
 #}
+
+# For changing MAC addresses - emerge net-analyzer/macchanger
+# - to set a specific MAC address
+#mac_eth0="00:11:22:33:44:55"
+# - to randomize the last 3 bytes only
+#mac_eth0="random-ending"
+# - to randomize between the same physical type of connection (eg fibre, copper, wireless) , all vendors
+#mac_eth0="random-samekind"
+# - to randomize between any physical type of connection (eg fibre, copper, wireless) , all vendors
+#mac_eth0="random-anykind"
+# - full randomization - WARNING: some MAC addresses generated by this may NOT act as expected
+#mac_eth0="random-full"
+# custom - passes all parameters directly to net-analyzer/macchanger
+#mac_eth0="some custom set of parameters"
+
+# uncomment this function for support for changing MAC addresses
+# also uncomment it's invocation in preup() above
+preup_macchanger() {
+	eval mac_IFACE=\"\$\{mac_${IFACE}\}\"
+	if [ -n "${mac_IFACE}" ]; then
+		if [[ -x /sbin/macchanger ]]; then
+			local macchanger_opts=""
+			case "${mac_IFACE}" in
+				# specific mac-addr, i wish there were a shorter way to specify this 
+				[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]) macchanger_opts="${macchanger_opts} --mac=${mac_IFACE}" ;;
+				# increment MAC address, default macchanger behavior
+				increment) macchanger_opts="${macchanger_opts}" ;;
+        	    # randomize just the ending bytes
+        	    random-ending) macchanger_opts="${macchanger_opts} -e" ;;
+        	    # keep the same kind of physical layer (eg fibre, copper)
+        	    random-samekind) macchanger_opts="${macchanger_opts} -a" ;;
+        	    # randomize to any known vendor of any physical layer type
+        	    random-anykind) macchanger_opts="${macchanger_opts} -A" ;;
+        	    # fully random bytes
+        	    random-full) macchanger_opts="${macchanger_opts} -r" ;;
+        	    # default case is just to pass on all the options
+				*) macchanger_opts="${macchanger_opts} ${mac_IFACE}" ;;
+			esac
+        	#echo "/sbin/macchanger ${macchanger_opts} ${IFACE}"
+        	/sbin/macchanger ${macchanger_opts} ${IFACE} >/dev/null 
+			retval=$?
+			if [ $retval -gt 0 ]; then
+				eerror "Failed to set MAC address"
+				return 1
+			fi
+		else	
+			eerror "For changing MAC addresses, emerge net-analyzer/macchanger"
+			return 1
+		fi
+	fi
+	return 0 #important
+}
+
+# For link bonding/trunking - emerge net-misc/ifenslave
+# if you are using any of the slave interfaces, it is important that you remove
+# configurations for them and take them down first!
+slaves_bond0="eth2"
+ipaddr_bond0=( "172.16.2.1/23 brd 172.16.3.255" )
+
+postup_bonding() {
+	# return silently if this is not a bonding interface
+	if [ -n "${IFACE/bond*/}" ]; then
+		return 0
+	fi
+	eval slaves_IFACE=\"\$\{slaves_${IFACE}\}\"
+	if [[ -n "${slaves_IFACE}" ]]; then
+		if [[ -x /sbin/ifenslave ]]; then
+			# must force the slaves to a particular state before adding them
+			for slaveiface in ${slaves_IFACE}; do
+				ifconfig ${slaveiface} 0.0.0.0 up
+			done
+			# now force the master to up
+			ifconfig ${IFACE} up
+			# finally add in slaves
+			/sbin/ifenslave ${IFACE} ${slaves_IFACE}
+		else
+			eerror "For link aggregation (bonding), emerge net-misc/ifenslave"
+			return 1
+		fi
+	fi
+	return 0 #important
+}
+
+predown_bonding() {
+	# return silently if this is not a bonding interface
+	if [ -n "${IFACE/bond*/}" ]; then
+		return 0
+	fi
+	# don't trust the config, get the active list instead
+	slaves_IFACE=$(awk '/^Slave Interface:/ { printf $3" " }' /proc/net/bonding/${IFACE})
+	if [[ -n "${slaves_IFACE}" ]]; then
+		# remove all slaves
+		echo /sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
+		/sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
+		# reset all slaves
+		for slaveiface in ${slaves_IFACE}; do
+			ifconfig ${slaveiface} 0.0.0.0 down
+		done
+	fi
+	return 0
+}
+
+preup_linkdetect() {
+	# Test for link on the interface prior to bringing it up.  This
+	# only works on some network adapters and requires the ethtool
+	# package to be installed.
+	if ethtool $1 | grep -q 'Link detected: no'; then
+		ewarn "No link on $1, aborting configuration"
+		return 1
+	fi
+}
+
