Fix bug 56856: Get rid of net.rej and integrate missing stuff to conf.d/net
svn path=/trunk/; revision=525

diff --git a/etc/conf.d/net b/etc/conf.d/net
--- a/etc/conf.d/net
+++ b/etc/conf.d/net
@@ -164,42 +164,54 @@
 #
 # The return values for the postup and postdown functions are ignored
 # since there's nothing to do if they indicate failure.
-#
+
 #preup() {
-#	# Test for link on the interface prior to bringing it up.  This
-#	# only works on some network adapters and requires the ethtool
-#	# package to be installed.
-#	if ethtool $1 | grep -q 'Link detected: no'; then
-#		ewarn "No link on $1, aborting configuration"
-#		return 1
-#	fi
+#	# Uncomment this function below if you want to check for link
+#	# Remember to uncomment the preup_linkdetect function!
+#	#preup_linkdetect $1
+#
+#	# Enable this function with this next line if you want to change your 
+#	# MAC address. Remember to uncomment the preup_macchanger function!
+#	#preup_macchanger $1
 #
 #	# Remember to return 0 on success
 #	return 0
 #}
-#
+
 #predown() {
 #	# Test to make sure the root filesystem is not mounted via NFS.
-#	# Interface ($1) is ignored but could also be tested if you know
-#	# what interface is providing NFS root.
-#	if grep -q ' / nfs' /proc/mounts; then
-#		ewarn "Root is NFS mounted, aborting deconfiguration of $1"
-#		return 1
-#	fi
+#	# Interface ($1) is ignored but could also be tested.
+#	#if grep -q ' / nfs ' /proc/mounts; then
+#	#	ewarn "Root is NFS mounted, aborting deconfiguration of $1"
+#	#	return 1
+#	#fi
+#
+#	# Bonding support
+#	#predown_bonding $1
 #
 #	# Remember to return 0 on success
 #	return 0
 #}
-#
+
 #postup() {
 #	# This function could be used, for example, to register with a
 #	# dynamic DNS service.  Another possibility would be to
 #	# send/receive mail once the interface is brought up.
-#}
 #
+#	# Enable this function with the next line if you want to use bonding.
+#	# Remember to uncomment the preup_bonding function!
+#	#postup_bonding $1
+#
+#	# Return 0 for success (ignored)
+#	return 0
+#}
+
 #postdown() {
 #	# This function is mostly here for completeness... I haven't
 #	# thought of anything nifty to do with it yet ;-)
+#
+#	# Return 0 for success (ignored)
+#	return 0
 #}
 
 # For changing MAC addresses - emerge net-analyzer/macchanger
@@ -218,98 +230,98 @@
 
 # uncomment this function for support for changing MAC addresses
 # also uncomment it's invocation in preup() above
-preup_macchanger() {
-	eval mac_IFACE=\"\$\{mac_${IFACE}\}\"
-	if [ -n "${mac_IFACE}" ]; then
-		if [[ -x /sbin/macchanger ]]; then
-			local macchanger_opts=""
-			case "${mac_IFACE}" in
-				# specific mac-addr, i wish there were a shorter way to specify this 
-				[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]) macchanger_opts="${macchanger_opts} --mac=${mac_IFACE}" ;;
-				# increment MAC address, default macchanger behavior
-				increment) macchanger_opts="${macchanger_opts}" ;;
-        	    # randomize just the ending bytes
-        	    random-ending) macchanger_opts="${macchanger_opts} -e" ;;
-        	    # keep the same kind of physical layer (eg fibre, copper)
-        	    random-samekind) macchanger_opts="${macchanger_opts} -a" ;;
-        	    # randomize to any known vendor of any physical layer type
-        	    random-anykind) macchanger_opts="${macchanger_opts} -A" ;;
-        	    # fully random bytes
-        	    random-full) macchanger_opts="${macchanger_opts} -r" ;;
-        	    # default case is just to pass on all the options
-				*) macchanger_opts="${macchanger_opts} ${mac_IFACE}" ;;
-			esac
-        	#echo "/sbin/macchanger ${macchanger_opts} ${IFACE}"
-        	/sbin/macchanger ${macchanger_opts} ${IFACE} >/dev/null 
-			retval=$?
-			if [ $retval -gt 0 ]; then
-				eerror "Failed to set MAC address"
-				return 1
-			fi
-		else	
-			eerror "For changing MAC addresses, emerge net-analyzer/macchanger"
-			return 1
-		fi
-	fi
-	return 0 #important
-}
+#preup_macchanger() {
+#	eval mac_IFACE=\"\$\{mac_${IFACE}\}\"
+#	if [ -n "${mac_IFACE}" ]; then
+#		if [[ -x /sbin/macchanger ]]; then
+#			local macchanger_opts=""
+#			case "${mac_IFACE}" in
+#				# specific mac-addr, i wish there were a shorter way to specify this 
+#				[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]) macchanger_opts="${macchanger_opts} --mac=${mac_IFACE}" ;;
+#				# increment MAC address, default macchanger behavior
+#				increment) macchanger_opts="${macchanger_opts}" ;;
+#        	    # randomize just the ending bytes
+#        	    random-ending) macchanger_opts="${macchanger_opts} -e" ;;
+#        	    # keep the same kind of physical layer (eg fibre, copper)
+#        	    random-samekind) macchanger_opts="${macchanger_opts} -a" ;;
+#        	    # randomize to any known vendor of any physical layer type
+#        	    random-anykind) macchanger_opts="${macchanger_opts} -A" ;;
+#        	    # fully random bytes
+#        	    random-full) macchanger_opts="${macchanger_opts} -r" ;;
+#        	    # default case is just to pass on all the options
+#				*) macchanger_opts="${macchanger_opts} ${mac_IFACE}" ;;
+#			esac
+#        	#echo "/sbin/macchanger ${macchanger_opts} ${IFACE}"
+#        	/sbin/macchanger ${macchanger_opts} ${IFACE} >/dev/null 
+#			retval=$?
+#			if [ $retval -gt 0 ]; then
+#				eerror "Failed to set MAC address"
+#				return 1
+#			fi
+#		else	
+#			eerror "For changing MAC addresses, emerge net-analyzer/macchanger"
+#			return 1
+#		fi
+#	fi
+#	return 0 #important
+#}
 
 # For link bonding/trunking - emerge net-misc/ifenslave
 # if you are using any of the slave interfaces, it is important that you remove
 # configurations for them and take them down first!
-slaves_bond0="eth2"
-ipaddr_bond0=( "172.16.2.1/23 brd 172.16.3.255" )
+#slaves_bond0="eth2"
+#ipaddr_bond0=( "172.16.2.1/23 brd 172.16.3.255" )
 
-postup_bonding() {
-	# return silently if this is not a bonding interface
-	if [ -n "${IFACE/bond*/}" ]; then
-		return 0
-	fi
-	eval slaves_IFACE=\"\$\{slaves_${IFACE}\}\"
-	if [[ -n "${slaves_IFACE}" ]]; then
-		if [[ -x /sbin/ifenslave ]]; then
-			# must force the slaves to a particular state before adding them
-			for slaveiface in ${slaves_IFACE}; do
-				ifconfig ${slaveiface} 0.0.0.0 up
-			done
-			# now force the master to up
-			ifconfig ${IFACE} up
-			# finally add in slaves
-			/sbin/ifenslave ${IFACE} ${slaves_IFACE}
-		else
-			eerror "For link aggregation (bonding), emerge net-misc/ifenslave"
-			return 1
-		fi
-	fi
-	return 0 #important
-}
+#postup_bonding() {
+#	# return silently if this is not a bonding interface
+#	if [ -n "${IFACE/bond*/}" ]; then
+#		return 0
+#	fi
+#	eval slaves_IFACE=\"\$\{slaves_${IFACE}\}\"
+#	if [[ -n "${slaves_IFACE}" ]]; then
+#		if [[ -x /sbin/ifenslave ]]; then
+#			# must force the slaves to a particular state before adding them
+#			for slaveiface in ${slaves_IFACE}; do
+#				ifconfig ${slaveiface} 0.0.0.0 up
+#			done
+#			# now force the master to up
+#			ifconfig ${IFACE} up
+#			# finally add in slaves
+#			/sbin/ifenslave ${IFACE} ${slaves_IFACE}
+#		else
+#			eerror "For link aggregation (bonding), emerge net-misc/ifenslave"
+#			return 1
+#		fi
+#	fi
+#	return 0 #important
+#}
 
-predown_bonding() {
-	# return silently if this is not a bonding interface
-	if [ -n "${IFACE/bond*/}" ]; then
-		return 0
-	fi
-	# don't trust the config, get the active list instead
-	slaves_IFACE=$(awk '/^Slave Interface:/ { printf $3" " }' /proc/net/bonding/${IFACE})
-	if [[ -n "${slaves_IFACE}" ]]; then
-		# remove all slaves
-		echo /sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
-		/sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
-		# reset all slaves
-		for slaveiface in ${slaves_IFACE}; do
-			ifconfig ${slaveiface} 0.0.0.0 down
-		done
-	fi
-	return 0
-}
+#predown_bonding() {
+#	# return silently if this is not a bonding interface
+#	if [ -n "${IFACE/bond*/}" ]; then
+#		return 0
+#	fi
+#	# don't trust the config, get the active list instead
+#	slaves_IFACE=$(awk '/^Slave Interface:/ { printf $3" " }' /proc/net/bonding/${IFACE})
+#	if [[ -n "${slaves_IFACE}" ]]; then
+#		# remove all slaves
+#		echo /sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
+#		/sbin/ifenslave -d ${IFACE} ${slaves_IFACE}
+#		# reset all slaves
+#		for slaveiface in ${slaves_IFACE}; do
+#			ifconfig ${slaveiface} 0.0.0.0 down
+#		done
+#	fi
+#	return 0
+#}
 
-preup_linkdetect() {
-	# Test for link on the interface prior to bringing it up.  This
-	# only works on some network adapters and requires the ethtool
-	# package to be installed.
-	if ethtool $1 | grep -q 'Link detected: no'; then
-		ewarn "No link on $1, aborting configuration"
-		return 1
-	fi
-}
+#preup_linkdetect() {
+#	# Test for link on the interface prior to bringing it up.  This
+#	# only works on some network adapters and requires the ethtool
+#	# package to be installed.
+#	if ethtool $1 | grep -q 'Link detected: no'; then
+#		ewarn "No link on $1, aborting configuration"
+#		return 1
+#	fi
+#}
 
