Added # vim:ts=4 to all net-script files and re-indented
/dep{cache,tree} are now chmodded 0644 so users can read them

svn path=/branches/baselayout-1_12/; revision=1382

diff --git a/net-scripts/net.modules.d/apipa b/net-scripts/net.modules.d/apipa
--- a/net-scripts/net.modules.d/apipa
+++ b/net-scripts/net.modules.d/apipa
@@ -8,41 +8,41 @@
 #
 # Returns a string to change module definition for starting up
 apipa_provides() {
-    echo "apipa"
+	echo "apipa"
 }
 
 # void apipa_depend(void)
 #
 # Sets up the dependancies for the module
 apipa_depend() {
-    after system dhcp vlan
+	after system dhcp vlan
 }
 
 # bool apipa_check_installed(void)
 #
 # Returns 1 if ifenslave is installed, otherwise 0
 apipa_check_installed() {
-    [[ -x /sbin/arping || -x /usr/sbin/arping2 ]] && return 0
-    if ${1:-false}; then
-	eerror "For Automatic Private IP Addressing (APIPA) support"
-	eerror "emerge net-misc/iputils or net-analyzer/arping"
-    fi
-    return 1
+	[[ -x /sbin/arping || -x /usr/sbin/arping2 ]] && return 0
+	if ${1:-false}; then
+		eerror "For Automatic Private IP Addressing (APIPA) support"
+		eerror "emerge net-misc/iputils or net-analyzer/arping"
+	fi
+	return 1
 }
 
 # bool apipa_check_depends(void)
 #
 # Checks to see if we have the needed functions
 apipa_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_up; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "apipa: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_up; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "apipa: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # bool address_exists(char *interface, char *address)
@@ -52,52 +52,54 @@ apipa_check_depends() {
 # If neither arping (net-misc/iputils) or arping2 (net-analyzer/arping)
 # is installed then we return 1
 address_exists() {
-    local iface="$1" address="${2%%/*}" i
+	local iface="$1" address="${2%%/*}" i
 
-    # We only handle IPv4 addresses
-    [[ ${address} != *.*.*.* ]] && return 1
+	# We only handle IPv4 addresses
+	[[ ${address} != *.*.*.* ]] && return 1
 
-    # We need to bring the interface up to test
-    interface_up "${iface}"
+	# We need to bring the interface up to test
+	interface_up "${iface}"
 
-    if [[ -x /sbin/arping ]]; then
-	/sbin/arping -q -c 2 -w 3 -D -f -I "${iface}" "${address}" \
-	    &>/dev/null || return 0
-    elif [[ -x /usr/sbin/arping2 ]]; then
-	for (( i=0; i<3; i++ )); do
-	    /usr/sbin/arping2 -0 -c 1 -i "${iface}" "${address}" \
-		&>/dev/null && return 0
-	done
-    fi
-    return 1
+	if [[ -x /sbin/arping ]]; then
+		/sbin/arping -q -c 2 -w 3 -D -f -I "${iface}" "${address}" \
+		&>/dev/null || return 0
+	elif [[ -x /usr/sbin/arping2 ]]; then
+		for (( i=0; i<3; i++ )); do
+			/usr/sbin/arping2 -0 -c 1 -i "${iface}" "${address}" \
+			&>/dev/null && return 0
+		done
+	fi
+	return 1
 }
 
 # bool apipa_start(char *iface)
 #
 # Tries to locate an address in the 169.254.0.0 netmask 169.254.255.255 range
 apipa_start() {
-    local iface="$1" i1 i2 addr i=0
+	local iface="$1" i1 i2 addr i=0
 
-    interface_exists "${iface}" true || return 1
+	interface_exists "${iface}" true || return 1
 
-    ebegin "Searching for free addresses"
-    interface_up "${iface}"
+	ebegin "Searching for free addresses"
+	interface_up "${iface}"
 
-    while [[ ${i} -lt 64516 ]]; do
-	(( i1=${RANDOM}%255 ))
-	(( i2=${RANDOM}%255 ))
+	while [[ ${i} -lt 64516 ]]; do
+		(( i1=${RANDOM}%255 ))
+		(( i2=${RANDOM}%255 ))
 
-	addr="169.254.${i1}.${i2}"
-	if ! address_exists "${iface}" "${addr}" ; then
-	    config[config_counter]="${addr}/16 broadcast 169.254.255.255"
-	    (( config_counter-- ))
-	    eend 0
-	    return 0
-	fi
+		addr="169.254.${i1}.${i2}"
+		if ! address_exists "${iface}" "${addr}" ; then
+			config[config_counter]="${addr}/16 broadcast 169.254.255.255"
+			(( config_counter-- ))
+			eend 0
+			return 0
+		fi
 
-	(( i++ ))
-    done
+		(( i++ ))
+	done
 
-    eend 1 "No free address found!"
-    return 1
+	eend 1 "No free address found!"
+	return 1
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/bridge b/net-scripts/net.modules.d/bridge
--- a/net-scripts/net.modules.d/bridge
+++ b/net-scripts/net.modules.d/bridge
@@ -7,46 +7,46 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 brctl() {
-    LC_ALL=C /sbin/brctl "$@"
+	LC_ALL=C /sbin/brctl "$@"
 }
 
 # char* bridge_provides(void)
 #
 # Returns a string to change module definition for starting up
 bridge_provides() {
-    echo "bridge"
+	echo "bridge"
 }
 
 # void bridge_depend(void)
 #
 # Sets up the dependancies for the module
 bridge_depend() {
-    after interface tuntap
-    before dhcp apipa
+	after interface tuntap
+	before dhcp apipa
 }
 
 # bool bridge_check_installed(void)
 #
 # Returns 1 if bridge is installed, otherwise 0
 bridge_check_installed() {
-    [[ -x /sbin/brctl ]] && return 0
-    ${1:-false} && eerror "For bridge support, emerge net-misc/bridge-utils"
-    return 1
+	[[ -x /sbin/brctl ]] && return 0
+	${1:-false} && eerror "For bridge support, emerge net-misc/bridge-utils"
+	return 1
 }
 
 # bool bridge_check_depends(void)
 #
 # Checks to see if we have the needed functions
 bridge_check_depends() {
-    local f
+	local f
 
-    for f in interface_down interface_del_addresses interface_set_flag; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "bridge: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_down interface_del_addresses interface_set_flag; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "bridge: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # char* bridge_get_vars(char *interface)
@@ -54,37 +54,37 @@ bridge_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 bridge_get_vars() {
-    echo "bridge_$1 brctl_$1"
+	echo "bridge_$1 brctl_$1"
 }
 
 # char* bridge_get_ports(char *interface)
 #
 # Returns the interfaces added to the given bridge
 bridge_get_ports() {
-    brctl show 2>/dev/null \
-    | sed -n -e '/^'"$1"'/,/^\S/ { /^\('"$1"'\|\t\)/s/^.*\t//p }'
+	brctl show 2>/dev/null \
+	| sed -n -e '/^'"$1"'/,/^\S/ { /^\('"$1"'\|\t\)/s/^.*\t//p }'
 }
 
 # char* bridge_get_bridge(char *interface)
 #
 # Returns the bridge interface of the given interface
 bridge_get_bridge() {
-    local x=$( brctl show 2>/dev/null \
-    | sed -e '1 {d}; /^[^ ]/ { N }; /.*'"$1"'.*/ {s/^\([^ \t]\+\).*/\1/p}; d' )
+	local x=$( brctl show 2>/dev/null \
+	| sed -e '1 {d}; /^[^ ]/ { N }; /.*'"$1"'.*/ {s/^\([^ \t]\+\).*/\1/p}; d' )
 
-    local -a a=( ${x} )
-    if [[ ${#a[@]} == "1" ]]; then
-	echo "${x}"
-    elif [[ $1 == "${a[3]}" ]]; then
-	echo "${a[0]}"
-    fi
+	local -a a=( ${x} )
+	if [[ ${#a[@]} == "1" ]]; then
+		echo "${x}"
+	elif [[ $1 == "${a[3]}" ]]; then
+		echo "${a[0]}"
+	fi
 }
 
 # bool bridge_exists(char *interface)
 #
 # Returns 0 if the bridge exists, otherwise 1
 bridge_exists() {
-    brctl show 2>/dev/null | grep -q "^$1"
+	brctl show 2>/dev/null | grep -q "^$1"
 }
 
 # bool bridge_create(char *interface)
@@ -92,53 +92,53 @@ bridge_exists() {
 # Creates the bridge - no ports are added here though
 # Returns 0 on success otherwise 1
 bridge_create() {
-    local iface="$1" ifvar=$( bash_variable "$1" ) x i
-    local -a opts
+	local iface="$1" ifvar=$( bash_variable "$1" ) x i
+	local -a opts
 
-    ebegin "Creating bridge ${iface}"
-    x=$( brctl addbr "${iface}" 2>&1 )
-    if [[ -n ${x} ]]; then
-	if [[ ${x} == "br_add_bridge: Package not installed" ]]; then
-	    eend 1 "Bridging (802.1d) support is not present in this kernel"
-	else
-	    eend 1 "${x}"
+	ebegin "Creating bridge ${iface}"
+	x=$( brctl addbr "${iface}" 2>&1 )
+	if [[ -n ${x} ]]; then
+		if [[ ${x} == "br_add_bridge: Package not installed" ]]; then
+			eend 1 "Bridging (802.1d) support is not present in this kernel"
+		else
+			eend 1 "${x}"
+		fi
+		return 1
 	fi
-	return 1
-    fi
 
-    eval opts=( \"\$\{brctl_${ifvar}\[@\]\}\" )
-    for (( i=0; i<${#opts[@]}; i++ )); do
-	x="${opts[i]/ / ${iface} }"
-	[[ ${x} == "${opts[i]}" ]] && x="${x} ${iface}"
-	x=$( brctl ${x} 2>&1 1>/dev/null )
-	[[ -n ${x} ]] && ewarn "${x}"
-    done
-    eend 0
+	eval opts=( \"\$\{brctl_${ifvar}\[@\]\}\" )
+	for (( i=0; i<${#opts[@]}; i++ )); do
+		x="${opts[i]/ / ${iface} }"
+		[[ ${x} == "${opts[i]}" ]] && x="${x} ${iface}"
+		x=$( brctl ${x} 2>&1 1>/dev/null )
+		[[ -n ${x} ]] && ewarn "${x}"
+	done
+	eend 0
 }
 
 # bool bridge_add_port(char *interface, char *port)
 #
 # Adds the port to the bridge
 bridge_add_port() {
-    local iface="$1" port="$2" e
+	local iface="$1" port="$2" e
 
-    interface_set_flag "${port}" promisc true
-    interface_up "${port}"
-    e=$( brctl addif "${iface}" "${port}" 2>&1 )
-    if [[ -n ${e} ]]; then
-	interface_set_flag "${port}" promisc false
-	echo "${e}" >&2
-	return 1
-    fi
-    return 0
+	interface_set_flag "${port}" promisc true
+	interface_up "${port}"
+	e=$( brctl addif "${iface}" "${port}" 2>&1 )
+	if [[ -n ${e} ]]; then
+		interface_set_flag "${port}" promisc false
+		echo "${e}" >&2
+		return 1
+	fi
+	return 0
 }
 
 # bool bridge_delete_port(char *interface, char *port)
 #
 # Deletes a port from a bridge
 bridge_delete_port() {
-    interface_set_flag "$2" promisc false
-    brctl delif "$1" "$2"
+	interface_set_flag "$2" promisc false
+	brctl delif "$1" "$2"
 }
 
 # bool bridge_start(char *iface)
@@ -147,44 +147,44 @@ bridge_delete_port() {
 # This can also be called by non-bridges so that the bridge can be created
 # dynamically
 bridge_pre_start() {
-    local iface="$1" ports briface i ifvar=$( bash_variable "$1" ) opts
-    eval ports=\"\$\{bridge_${ifvar}\[@\]\}\"
-    eval briface=\"\$\{bridge_add_${ifvar}\}\"
-    eval opts=\"\$\{brctl_${ifvar}\}\"
+	local iface="$1" ports briface i ifvar=$( bash_variable "$1" ) opts
+	eval ports=\"\$\{bridge_${ifvar}\[@\]\}\"
+	eval briface=\"\$\{bridge_add_${ifvar}\}\"
+	eval opts=\"\$\{brctl_${ifvar}\}\"
 
-    [[ -z ${ports} && -z ${briface} && -z ${opts} ]] && return 0
+	[[ -z ${ports} && -z ${briface} && -z ${opts} ]] && return 0
 
-    # Destroy the bridge if it exists
-    [[ -n ${ports} ]] && bridge_stop "${iface}"
+	# Destroy the bridge if it exists
+	[[ -n ${ports} ]] && bridge_stop "${iface}"
 
-    # Allow ourselves to add to the bridge
-    if [[ -z ${ports} && -n ${briface} ]]; then
-	ports="${iface}"
-	iface="${briface}"
-    fi
+	# Allow ourselves to add to the bridge
+	if [[ -z ${ports} && -n ${briface} ]]; then
+		ports="${iface}"
+		iface="${briface}"
+	fi
 
-    # Create the bridge if needed
-    bridge_exists "${iface}" || bridge_create "${iface}"
+	# Create the bridge if needed
+	bridge_exists "${iface}" || bridge_create "${iface}"
 
-    if [[ -n ${ports} ]]; then
-	einfo "Adding ports to ${iface}"
-	eindent
+	if [[ -n ${ports} ]]; then
+		einfo "Adding ports to ${iface}"
+		eindent
 
-	for i in ${ports}; do
-	    interface_exists "${i}" && continue 
-	    eerror "interface ${i} does not exist"
-	    return 1
-	done
+		for i in ${ports}; do
+			interface_exists "${i}" && continue 
+			eerror "interface ${i} does not exist"
+			return 1
+		done
 
-	for i in ${ports}; do
-	    ebegin "${i}"
-	    bridge_add_port "${iface}" "${i}"
-	    eend $? || return 1
-	done
-	eoutdent
-    fi
+		for i in ${ports}; do
+			ebegin "${i}"
+			bridge_add_port "${iface}" "${i}"
+			eend $? || return 1
+		done
+		eoutdent
+	fi
 
-    return 0
+	return 0
 }
 
 # bool bridge_stop(char *iface)
@@ -192,34 +192,36 @@ bridge_pre_start() {
 # Removes the device
 # returns 0
 bridge_stop() {
-    bridge_check_installed || return 0
+	bridge_check_installed || return 0
 
-    local iface="$1" ports i deletebridge=false extra=""
+	local iface="$1" ports i deletebridge=false extra=""
 
-    if bridge_exists "${iface}" ; then
-	ebegin "Destroying bridge ${iface}"
-	interface_down "${iface}"
-	ports=$( bridge_get_ports "${iface}" )
-	deletebridge=true
-	eindent
-    else
-	# Work out if we're added to a bridge for removal or not
-	ports="${iface}"
-	iface=$( bridge_get_bridge "${iface}" )
-	[[ -z ${iface} ]] && return 0
-	extra=" from ${iface}"
-    fi
+	if bridge_exists "${iface}" ; then
+		ebegin "Destroying bridge ${iface}"
+		interface_down "${iface}"
+		ports=$( bridge_get_ports "${iface}" )
+		deletebridge=true
+		eindent
+	else
+		# Work out if we're added to a bridge for removal or not
+		ports="${iface}"
+		iface=$( bridge_get_bridge "${iface}" )
+		[[ -z ${iface} ]] && return 0
+		extra=" from ${iface}"
+	fi
 
-    for i in ${ports}; do
-	ebegin "Removing port ${i}${extra}"
-	bridge_delete_port "${iface}" "${i}"
-	eend $?
-    done
+	for i in ${ports}; do
+		ebegin "Removing port ${i}${extra}"
+		bridge_delete_port "${iface}" "${i}"
+		eend $?
+	done
 
-    if ${deletebridge} ; then
-	eoutdent
-	brctl delbr "${iface}" &>/dev/null
-	eend 0
-    fi
-    return 0
+	if ${deletebridge} ; then
+		eoutdent
+		brctl delbr "${iface}" &>/dev/null
+		eend 0
+	fi
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/essidnet b/net-scripts/net.modules.d/essidnet
--- a/net-scripts/net.modules.d/essidnet
+++ b/net-scripts/net.modules.d/essidnet
@@ -8,44 +8,44 @@
 
 # Load our config if it exists
 [[ -f $(add_suffix "/etc/conf.d/wireless" ) ]] \
-    && source $(add_suffix "/etc/conf.d/wireless" )
+&& source $(add_suffix "/etc/conf.d/wireless" )
 
 # void essidnet_depend(void)
 #
 # Sets up the dependancies for the module
 essidnet_depend() {
-    before interface
-    after wireless
-    installed wireless
+	before interface
+	after wireless
+	installed wireless
 }
 
 # bool essidnet_check_installed(void)
 #
 # Always returns 0 as we are "installed" by wireless in the depend function
 essidnet_check_installed() {
-    return 0
+	return 0
 }
 
 # char* essidnet_provides(void)
 #
 # Returns a string to change module definition for starting up
 essidnet_provides() {
-    echo "essidnet"
+	echo "essidnet"
 }
 
 # bool essidnet_check_depends(void)
 #
 # Checks to see if we have the needed functions
 essidnet_check_depends() {
-    local f
+	local f
 
-    for f in wireless_check_extensions wireless_get_essid wireless_get_ap_mac_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "essidnet: missing required function ${f}\n"
-	return 1
-    done
+	for f in wireless_check_extensions wireless_get_essid wireless_get_ap_mac_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "essidnet: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # bool essidnet_start(char *iface)
@@ -56,22 +56,24 @@ essidnet_check_depends() {
 # of the AP connected to. MAC configuration takes precedence
 # Always returns 0
 essidnet_pre_start() {
-    local iface="$1"
+	local iface="$1"
 
-    wireless_check_extensions "${iface}" || return 0
+	wireless_check_extensions "${iface}" || return 0
 
-    local mac=$( wireless_get_ap_mac_address "${iface}" )
-    local ESSID=$( wireless_get_essid "${iface}" )
-    local essid=$( bash_variable ${ESSID} )
-    mac="${mac//:/}"
+	local mac=$( wireless_get_ap_mac_address "${iface}" )
+	local ESSID=$( wireless_get_essid "${iface}" )
+	local essid=$( bash_variable ${ESSID} )
+	mac="${mac//:/}"
 
-    vebegin "Configuring ${iface} for ESSID \"${ESSID//\\\\/\\\\}\"" 2>/dev/null
-    configure_variables "${iface}" "${essid}" "${mac}"
+	vebegin "Configuring ${iface} for ESSID \"${ESSID//\\\\/\\\\}\"" 2>/dev/null
+	configure_variables "${iface}" "${essid}" "${mac}"
 
-    # Backwards compat for old gateway var
-    eval x=\"\$\{gateway_${essid}\}\"
-    [[ -n ${x} ]] && gateway="${iface}/${x}"
+	# Backwards compat for old gateway var
+	eval x=\"\$\{gateway_${essid}\}\"
+	[[ -n ${x} ]] && gateway="${iface}/${x}"
 
-    veend 0 2>/dev/null
-    return 0
+	veend 0 2>/dev/null
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/helpers.d/module-loader b/net-scripts/net.modules.d/helpers.d/module-loader
--- a/net-scripts/net.modules.d/helpers.d/module-loader
+++ b/net-scripts/net.modules.d/helpers.d/module-loader
@@ -13,21 +13,21 @@ conf=$(add_suffix "/etc/conf.d/net")
 
 # Guess which interface module to load - we prefer iproute2
 if [[ -x /sbin/ip ]]; then
-    interface_module="iproute2"
+	interface_module="iproute2"
 elif [[ -x /sbin/ifconfig ]]; then
-    interface_module="ifconfig"
+	interface_module="ifconfig"
 else
-    echo "Can't find a known interface module" >&2
-    exit 1
+	echo "Can't find a known interface module" >&2
+	exit 1
 fi
 
 # iwconfig is the best bet for wireless - we use wpa_supplicant
 # only if we need to
 if [[ -x /sbin/iwconfig ]]; then
-    wireless_module="iwconfig"
+	wireless_module="iwconfig"
 elif [[ -x /sbin/wpa_supplicant \
-    && -S "/var/run/wpa_supplicant/${interface}" ]]; then
-    wireless_module="wpa_supplicant"
+	&& -S "/var/run/wpa_supplicant/${interface}" ]]; then
+	wireless_module="wpa_supplicant"
 fi
 
 MODULES=( "system" )
@@ -39,7 +39,9 @@ function_wrap "${interface_module}" interface
 . "${MODULES_DIR}/system"
 
 if [[ -n ${wireless_module} ]]; then
-    . "${MODULES_DIR}/${wireless_module}"
-    function_wrap "${wireless_module}" wireless
-    . "${MODULES_DIR}/essidnet"
+	. "${MODULES_DIR}/${wireless_module}"
+	function_wrap "${wireless_module}" wireless
+	. "${MODULES_DIR}/essidnet"
 fi
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/wpa_supplicant b/net-scripts/net.modules.d/wpa_supplicant
--- a/net-scripts/net.modules.d/wpa_supplicant
+++ b/net-scripts/net.modules.d/wpa_supplicant
@@ -7,82 +7,82 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 wpa_supplicant() {
-    LC_ALL=C /sbin/wpa_supplicant "$@"
+	LC_ALL=C /sbin/wpa_supplicant "$@"
 }
 
 wpa_cli() {
-    LC_ALL=C /bin/wpa_cli "$@"
+	LC_ALL=C /bin/wpa_cli "$@"
 }
 
 # char* wpa_supplicant_provides(void)
 #
 # Returns a string to change module definition for starting up
 wpa_supplicant_provides() {
-    echo "wireless"
+	echo "wireless"
 }
 
 # void wpa_supplicant_depend(void)
 #
 # Sets up the dependancies for the module
 wpa_supplicant_depend() {
-    after macnet
-    before interface
+	after macnet
+	before interface
 }
 
 # bool wpa_supplicant_check_installed(void)
 #
 # Returns 0 if wpa_supplicant is installed, otherwise 1
 wpa_supplicant_check_installed() {
-    local report="${1:-false}" installed="0"
-    if [[ ! -x /sbin/wpa_supplicant ]]; then
-	installed="1"
-	${report} && eerror "For WPA support (wpa_supplicant) support, emerge net-wireless/wpa_supplicant"
-    fi
-    if [[ ! -e /proc/net/packet ]]; then
-	installed="1"
-	${report} && eerror "wpa_supplicant requires Packet Socket (CONFIG_PACKET=y) enabled in the kernel"
-    fi
-    return "${installed}"
+	local report="${1:-false}" installed="0"
+	if [[ ! -x /sbin/wpa_supplicant ]]; then
+		installed="1"
+		${report} && eerror "For WPA support (wpa_supplicant) support, emerge net-wireless/wpa_supplicant"
+	fi
+	if [[ ! -e /proc/net/packet ]]; then
+		installed="1"
+		${report} && eerror "wpa_supplicant requires Packet Socket (CONFIG_PACKET=y) enabled in the kernel"
+	fi
+	return "${installed}"
 }
 
 # bool wpa_supplicant_check_depends(void)
 #
 # Checks to see if we have the needed functions
 wpa_supplicant_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "wpa_supplicant: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "wpa_supplicant: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # bool wpa_supplicant_check_extensions(char *interface)
 #
 # Checks to see if wireless extensions are enabled on the interface
 wpa_supplicant_check_extensions() {
-    grep -q "$1: " /proc/net/wireless
+	grep -q "$1: " /proc/net/wireless
 }
 
 # char* wpa_supplicant_get_essid(char *interface)
 #
 # Gets the current ESSID of iface
 wpa_supplicant_get_essid() {
-    local i essid
+	local i essid
 
-    for (( i=0; i<5; i++ )); do
-	essid=$( wpa_cli -i"$1" status | sed -n -e 's/^ssid=//p' )
-	if [[ -n ${essid} ]]; then
-	    echo "${essid}"
-	    return 0
-	fi
-	sleep 1
-    done
+	for (( i=0; i<5; i++ )); do
+		essid=$( wpa_cli -i"$1" status | sed -n -e 's/^ssid=//p' )
+		if [[ -n ${essid} ]]; then
+			echo "${essid}"
+			return 0
+		fi
+		sleep 1
+	done
 
-    return 1
+	return 1
 }
 
 # char* wpa_supplicant_get_ap_mac_address(char *interface)
@@ -90,7 +90,7 @@ wpa_supplicant_get_essid() {
 # Returns the MAC address of the Access Point
 # the interface is connected to
 wpa_supplicant_get_ap_mac_address() {
-    wpa_cli -i"$1" status | sed -n -e 's/^bssid=\([^=]\+\).*/\U\1/p'
+	wpa_cli -i"$1" status | sed -n -e 's/^bssid=\([^=]\+\).*/\U\1/p'
 }
 
 # bool wpa_supplicant_associated(char *interface)
@@ -100,54 +100,54 @@ wpa_supplicant_get_ap_mac_address() {
 # correct encryption keys
 # We only need this for wpa_supplicant-0.3.x
 wpa_supplicant_associated() {
-    local -a status=( "$( wpa_cli -i"$1" status | sed -n -e 's/^\(key_mgmt\|wpa_state\|EAP state\)=\([^=]\+\).*/\U\2/p' )" )
+	local -a status=( "$( wpa_cli -i"$1" status | sed -n -e 's/^\(key_mgmt\|wpa_state\|EAP state\)=\([^=]\+\).*/\U\2/p' )" )
 
-    case "${status[0]}" in
-	"NONE")			[[ ${status[1]} == "ASSOCIATED" ]] ;;
-	"IEEE 802.1X (no WPA)")	[[ ${status[2]} == "SUCCESS" ]] ;;
-	*)			[[ ${status[1]} == "COMPLETED" ]] ;;
-    esac
+	case "${status[0]}" in
+		"NONE")			[[ ${status[1]} == "ASSOCIATED" ]] ;;
+		"IEEE 802.1X (no WPA)")	[[ ${status[2]} == "SUCCESS" ]] ;;
+		*)			[[ ${status[1]} == "COMPLETED" ]] ;;
+	esac
 
-    return $?
+	return $?
 }
 
 # void wpa_supplicant_kill(char *interface, bool report)
 #
 # Kills any existing wpa_supplicant process on the interface
 wpa_supplicant_kill() {
-    local iface="$1" report="${2:-false}" pidfile
+	local iface="$1" report="${2:-false}" pidfile
 
-    # Shutdown wpa_cli first, if it's running
-    # This is important as future versions of wpa_supplicant
-    # may send a disconnect message to wpa_cli when it shutsdown
-    pidfile="/var/run/wpa_cli-${iface}.pid"
-    if ! clean_pidfile "${pidfile}" ; then
-	${report} && ebegin "Stopping wpa_cli on ${iface}"
-	start-stop-daemon --stop --exec /bin/wpa_cli \
-	    --pidfile "${pidfile}"
-	${report} && eend "$?"
-    fi
-
-    # Now shutdown wpa_supplicant
-    pidfile="/var/run/wpa_supplicant-${iface}.pid"
-    if ! clean_pidfile "${pidfile}" ; then
-	${report} && ebegin "Stopping wpa_supplicant on ${iface}"
-	start-stop-daemon --stop --exec /sbin/wpa_supplicant \
-	    --pidfile "${pidfile}"
-	${report} && eend "$?"
-    else
-	# Support wpa_supplicant-0.3.x
-	local pid=$( pgrep -f '^/sbin/wpa_supplicant .* -i'"${iface}"'[ ]*$' )
-	if [[ -n ${pid} ]]; then
-	    ${report} && ebegin "Stopping wpa_supplicant on ${iface}"
-	    kill -s TERM "${pid}"
-	    ${report} && eend 0
+	# Shutdown wpa_cli first, if it's running
+	# This is important as future versions of wpa_supplicant
+	# may send a disconnect message to wpa_cli when it shutsdown
+	pidfile="/var/run/wpa_cli-${iface}.pid"
+	if ! clean_pidfile "${pidfile}" ; then
+		${report} && ebegin "Stopping wpa_cli on ${iface}"
+		start-stop-daemon --stop --exec /bin/wpa_cli \
+		--pidfile "${pidfile}"
+		${report} && eend "$?"
 	fi
-    fi
 
-    # If wpa_supplicant exits uncleanly, we need to remove the stale dir
-    [[ -S "/var/run/wpa_supplicant/${iface}" ]] \
-    && rm -f "/var/run/wpa_supplicant/${iface}"
+	# Now shutdown wpa_supplicant
+	pidfile="/var/run/wpa_supplicant-${iface}.pid"
+	if ! clean_pidfile "${pidfile}" ; then
+		${report} && ebegin "Stopping wpa_supplicant on ${iface}"
+		start-stop-daemon --stop --exec /sbin/wpa_supplicant \
+		--pidfile "${pidfile}"
+		${report} && eend "$?"
+	else
+		# Support wpa_supplicant-0.3.x
+		local pid=$( pgrep -f '^/sbin/wpa_supplicant .* -i'"${iface}"'[ ]*$' )
+		if [[ -n ${pid} ]]; then
+			${report} && ebegin "Stopping wpa_supplicant on ${iface}"
+			kill -s TERM "${pid}"
+			${report} && eend 0
+		fi
+	fi
+
+	# If wpa_supplicant exits uncleanly, we need to remove the stale dir
+	[[ -S "/var/run/wpa_supplicant/${iface}" ]] \
+	&& rm -f "/var/run/wpa_supplicant/${iface}"
 }
 
 # bool wpa_supplicant_associate(char *interface)
@@ -155,44 +155,44 @@ wpa_supplicant_kill() {
 # Returns 0 if wpa_supplicant associates and authenticates to an AP
 # otherwise, 1
 wpa_supplicant_associate() {
-    local iface="$1" ifvar=$( bash_variable "$1" ) timeout i
-    eval timeout=\"\$\{associate_timeout_${ifvar}\}\"
-    [[ -z ${timeout} ]] && eval timeout=\"\$\{wpa_timeout_${ifvar}:-60\}\"
+	local iface="$1" ifvar=$( bash_variable "$1" ) timeout i
+	eval timeout=\"\$\{associate_timeout_${ifvar}\}\"
+	[[ -z ${timeout} ]] && eval timeout=\"\$\{wpa_timeout_${ifvar}:-60\}\"
 
-    [[ ${timeout} == "0" ]] \
+	[[ ${timeout} == "0" ]] \
 	&& vewarn "WARNING: infinite timeout set for association on ${iface}"
-    
-    while true ; do
-	if ${action} ; then
-	    service_started "net.${iface}" && return 0
-	else
-	    if ! wpa_cli -i"${iface}" status &>/dev/null ; then
-		eend 1 "wpa_supplicant has exited unexpectedly"
-		return 1
-	    fi
-	    wpa_supplicant_associated "${iface}" && return 0
-	fi
-	sleep 1
-	(( i++ ))
-	[[ ${i} == "${timeout}" || ${i} -gt "${timeout}" ]] && break
-    done
 
-    # Spit out an appropriate error
-    if [[ ${background} != "yes" ]]; then
-	if ${action} ; then
-	    eend 1 "Failed to configure ${iface} in the background"
-	else
-	    eend 1 "Timed out"
-	fi
-    fi
+	while true ; do
+		if ${action} ; then
+			service_started "net.${iface}" && return 0
+		else
+			if ! wpa_cli -i"${iface}" status &>/dev/null ; then
+				eend 1 "wpa_supplicant has exited unexpectedly"
+				return 1
+			fi
+			wpa_supplicant_associated "${iface}" && return 0
+		fi
+		sleep 1
+		(( i++ ))
+		[[ ${i} == "${timeout}" || ${i} -gt "${timeout}" ]] && break
+	done
 
-    # exit without error with wpa_supplicant-0.4.x as we may get kickstarted
-    # when an AP comes in range
-    ${action} && exit 0
-    
-    # Kill wpa_supplicant for 0.3.x
-    wpa_supplicant_kill "${iface}"
-    return 1
+	# Spit out an appropriate error
+	if [[ ${background} != "yes" ]]; then
+		if ${action} ; then
+			eend 1 "Failed to configure ${iface} in the background"
+		else
+			eend 1 "Timed out"
+		fi
+	fi
+
+	# exit without error with wpa_supplicant-0.4.x as we may get kickstarted
+	# when an AP comes in range
+	${action} && exit 0
+
+	# Kill wpa_supplicant for 0.3.x
+	wpa_supplicant_kill "${iface}"
+	return 1
 }
 
 # bool wpa_supplicant_pre_start(char *interface)
@@ -200,142 +200,142 @@ wpa_supplicant_associate() {
 # Start wpa_supplicant on an interface and wait for association
 # Returns 0 (true) when successful, non-zero otherwise
 wpa_supplicant_pre_start() {
-    local iface="$1" opts timeout action=false
-    local cfgfile="/etc/wpa_supplicant.conf"
-    local actfile="/sbin/wpa_cli.action"
+	local iface="$1" opts timeout action=false
+	local cfgfile="/etc/wpa_supplicant.conf"
+	local actfile="/sbin/wpa_cli.action"
 
-    # We don't configure wireless if we're being called from
-    # the background
-    if ${IN_BACKGROUND} ; then
+	# We don't configure wireless if we're being called from
+	# the background
+	if ${IN_BACKGROUND} ; then
+		ESSID=$( wpa_supplicant_get_essid "${iface}" )
+		ESSIDVAR=$( bash_variable "${ESSID}" )
+		save_options "ESSID" "${ESSID}"
+		return 0
+	fi
+
+	save_options "ESSID" ""
+
+	# We only work on wirelesss interfaces
+	wpa_supplicant_check_extensions "${iface}" || return 0
+
+	# Kill off any existing wpa_supplicant on this interface
+	# This is so we can re-read the configuration file and clean any stale
+	# directories
+	wpa_supplicant_kill "${iface}" true
+
+	# Check for rf_kill - only ipw supports this at present, but other
+	# cards may in the future
+	if [[ -e "/sys/class/net/${iface}/device/rf_kill" ]]; then
+		if [[ $( < "/sys/class/net/${iface}/device/rf_kill" ) != 0 ]]; then
+			eerror "Wireless radio has been killed for interface ${iface}"
+			return 1
+		fi
+	fi
+
+	# If wireless-tools is installed, try and apply our user config
+	# This is needed for some drivers - such as hostap because they start
+	# the card in Master mode which causes problems with wpa_supplicant.
+	if [[ $( type -t iwconfig_defaults ) == "function" ]]; then
+		iwconfig_defaults "${iface}"
+		iwconfig_user_config "${iface}"
+	fi	
+
+	ebegin "Starting wpa_supplicant on ${iface}"
+
+	if [[ ! -f ${cfgfile} ]]; then
+		eend 1 "configuration file ${cfgfile} not found!"
+		return 1
+	fi
+
+	local ctrl_dir=$( sed -n -e 's/[ \t]*#.*//g;s/[ \t]*$//g;s/^ctrl_interface=//p' "${cfgfile}" )
+	if [[ ${ctrl_dir} != "/var/run/wpa_supplicant" ]]; then
+		eerror "${cfgfile} must set"
+		eerror "  ctrl_interface=/var/run/wpa_supplicant"
+		eend 1
+		return 1
+	fi
+
+	local ifvar=$( bash_variable "${iface}" )
+	eval opts=\" \$\{wpa_supplicant_${ifvar}\}\"
+	[[ ${opts} != *" -D"* ]] \
+	&& ewarn "wpa_supplicant_${ifvar} does not define a driver"
+
+	# Some drivers require the interface to be up
+	interface_up "${iface}"
+
+	version=$( wpa_cli -v | sed -n -e 's/wpa_cli v//p' )
+	version=( ${version//./ } )
+	(( version = version[0] * 1000 + version[1] * 100 + version[2] ))
+
+	# wpa_supplicant 0.4.0 and greater supports wpa_cli actions
+	# This is very handy as if and when different association mechanisms are
+	# introduced to wpa_supplicant we don't have to recode for them as
+	# wpa_cli is now responsible for informing us of success/failure.
+	# The downside of this is that we don't see the interface being configured
+	# for DHCP/static.
+	if [[ ${version} -gt 399 && -x ${actfile} ]]; then
+		opts="${opts} -W -P/var/run/wpa_supplicant-${iface}.pid"
+		action=true
+		[[ ${RC_PARALLEL_STARTUP} == "yes" ]] && background=no
+	fi
+
+	start-stop-daemon --start --exec /sbin/wpa_supplicant \
+	-- ${opts} -B -c/etc/wpa_supplicant.conf -i"${iface}"
+	eend "$?" || return 1
+
+	# Starting wpa_supplication-0.4.0, we can get wpa_cli to
+	# start/stop our scripts from wpa_supplicant messages
+	if ${action} ; then
+		mark_service_inactive "net.${iface}"
+		ebegin "Starting wpa_cli on ${iface}"
+		start-stop-daemon --start --exec /bin/wpa_cli \
+		-- -a"${actfile}" -i"${iface}" \
+		-P"/var/run/wpa_cli-${iface}.pid" -B
+		eend "$?" || return 1
+	fi
+
+	# Background wpa_supplication if required
+	if [[ ${background} == "yes" ]]; then
+		if ! ${action} ; then
+			wpa_supplicant_associate "${iface}" \
+			&& export IN_BACKGROUND=true \
+			&& /etc/init.d/net.${iface} start >/dev/null &
+		fi
+		go_background
+	fi
+
+	eindent
+	veinfo "Waiting for association"
+	eend 0
+
+	wpa_supplicant_associate "${iface}" || return 1
+
+	# Set ESSID for essidnet and report
 	ESSID=$( wpa_supplicant_get_essid "${iface}" )
 	ESSIDVAR=$( bash_variable "${ESSID}" )
 	save_options "ESSID" "${ESSID}"
-	return 0
-    fi
 
-    save_options "ESSID" ""
+	local -a status=( "$( wpa_cli -i${iface} status | sed -n -e 's/^\(bssid\|pairwise_cipher\|key_mgmt\)=\([^=]\+\).*/\U\2/p' | tr '[:lower:]' '[:upper:]' )" )
+	einfo "${iface} connected to \"${ESSID//\\\\/\\\\}\" at ${status[0]}"
 
-    # We only work on wirelesss interfaces
-    wpa_supplicant_check_extensions "${iface}" || return 0
-
-    # Kill off any existing wpa_supplicant on this interface
-    # This is so we can re-read the configuration file and clean any stale
-    # directories
-    wpa_supplicant_kill "${iface}" true
-
-    # Check for rf_kill - only ipw supports this at present, but other
-    # cards may in the future
-    if [[ -e "/sys/class/net/${iface}/device/rf_kill" ]]; then
-	if [[ $( < "/sys/class/net/${iface}/device/rf_kill" ) != 0 ]]; then
-	    eerror "Wireless radio has been killed for interface ${iface}"
-	    return 1
-	fi
-    fi
-
-    # If wireless-tools is installed, try and apply our user config
-    # This is needed for some drivers - such as hostap because they start
-    # the card in Master mode which causes problems with wpa_supplicant.
-    if [[ $( type -t iwconfig_defaults ) == "function" ]]; then
-	iwconfig_defaults "${iface}"
-	iwconfig_user_config "${iface}"
-    fi	
-
-    ebegin "Starting wpa_supplicant on ${iface}"
-
-    if [[ ! -f ${cfgfile} ]]; then
-	eend 1 "configuration file ${cfgfile} not found!"
-	return 1
-    fi
-
-    local ctrl_dir=$( sed -n -e 's/[ \t]*#.*//g;s/[ \t]*$//g;s/^ctrl_interface=//p' "${cfgfile}" )
-    if [[ ${ctrl_dir} != "/var/run/wpa_supplicant" ]]; then
-	eerror "${cfgfile} must set"
-	eerror "  ctrl_interface=/var/run/wpa_supplicant"
-	eend 1
-	return 1
-    fi
-
-    local ifvar=$( bash_variable "${iface}" )
-    eval opts=\" \$\{wpa_supplicant_${ifvar}\}\"
-    [[ ${opts} != *" -D"* ]] \
-	&& ewarn "wpa_supplicant_${ifvar} does not define a driver"
-
-    # Some drivers require the interface to be up
-    interface_up "${iface}"
-
-    version=$( wpa_cli -v | sed -n -e 's/wpa_cli v//p' )
-    version=( ${version//./ } )
-    (( version = version[0] * 1000 + version[1] * 100 + version[2] ))
-    
-    # wpa_supplicant 0.4.0 and greater supports wpa_cli actions
-    # This is very handy as if and when different association mechanisms are
-    # introduced to wpa_supplicant we don't have to recode for them as
-    # wpa_cli is now responsible for informing us of success/failure.
-    # The downside of this is that we don't see the interface being configured
-    # for DHCP/static.
-    if [[ ${version} -gt 399 && -x ${actfile} ]]; then
-	opts="${opts} -W -P/var/run/wpa_supplicant-${iface}.pid"
-	action=true
-	 [[ ${RC_PARALLEL_STARTUP} == "yes" ]] && background=no
-    fi
-
-    start-stop-daemon --start --exec /sbin/wpa_supplicant \
-        -- ${opts} -B -c/etc/wpa_supplicant.conf -i"${iface}"
-    eend "$?" || return 1
-
-    # Starting wpa_supplication-0.4.0, we can get wpa_cli to
-    # start/stop our scripts from wpa_supplicant messages
-    if ${action} ; then
-	mark_service_inactive "net.${iface}"
-	ebegin "Starting wpa_cli on ${iface}"
-	start-stop-daemon --start --exec /bin/wpa_cli \
-	-- -a"${actfile}" -i"${iface}" \
-	-P"/var/run/wpa_cli-${iface}.pid" -B
-	eend "$?" || return 1
-    fi
-
-    # Background wpa_supplication if required
-    if [[ ${background} == "yes" ]]; then
-	if ! ${action} ; then
-	    wpa_supplicant_associate "${iface}" \
-	    && export IN_BACKGROUND=true \
-	    && /etc/init.d/net.${iface} start >/dev/null &
-	fi
-	go_background
-    fi
-
-    eindent
-    veinfo "Waiting for association"
-    eend 0
-
-    wpa_supplicant_associate "${iface}" || return 1
-
-    # Set ESSID for essidnet and report
-    ESSID=$( wpa_supplicant_get_essid "${iface}" )
-    ESSIDVAR=$( bash_variable "${ESSID}" )
-    save_options "ESSID" "${ESSID}"
-
-    local -a status=( "$( wpa_cli -i${iface} status | sed -n -e 's/^\(bssid\|pairwise_cipher\|key_mgmt\)=\([^=]\+\).*/\U\2/p' | tr '[:lower:]' '[:upper:]' )" )
-    einfo "${iface} connected to \"${ESSID//\\\\/\\\\}\" at ${status[0]}"
-
-    if [[ ${status[2]} == "NONE" ]]; then
-	if [[ ${status[1]} == "NONE" ]]; then
-	    ewarn "not using any encryption"
+	if [[ ${status[2]} == "NONE" ]]; then
+		if [[ ${status[1]} == "NONE" ]]; then
+			ewarn "not using any encryption"
+		else
+			veinfo "using ${status[1]}"
+		fi
 	else
-	    veinfo "using ${status[1]}"
+		veinfo "using ${status[2]}/${status[1]}"
 	fi
-    else
-	veinfo "using ${status[2]}/${status[1]}"
-    fi
-    eoutdent
+	eoutdent
 
-    if ${action} ; then
-	local addr=$( interface_get_address "${iface}" )
-	einfo "${iface} configured with address ${addr}"
-	exit 0 
-    fi
+	if ${action} ; then
+		local addr=$( interface_get_address "${iface}" )
+		einfo "${iface} configured with address ${addr}"
+		exit 0 
+	fi
 
-    return 0
+	return 0
 }
 
 # bool wpa_supplicant_post_stop(char *iface)
@@ -343,6 +343,8 @@ wpa_supplicant_pre_start() {
 # Stops wpa_supplicant on an interface
 # Returns 0 (true) when successful, non-zero otherwise
 wpa_supplicant_post_stop() {
-    ! ${IN_BACKGROUND} && wpa_supplicant_kill "$1" true
-    return 0
+	! ${IN_BACKGROUND} && wpa_supplicant_kill "$1" true
+	return 0
 }
+
+# vim:ts=4
