added #!/bin/bash or #!/bin/sh to modules and helpers so they now get nice syntax highlighting and indenting
svn path=/trunk/; revision=1185

diff --git a/net-scripts/net.modules.d/bonding b/net-scripts/net.modules.d/bonding
--- a/net-scripts/net.modules.d/bonding
+++ b/net-scripts/net.modules.d/bonding
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -8,83 +9,83 @@
 #
 # Returns a string to change module definition for starting up
 bonding_provides() {
-	echo "bonding"
+    echo "bonding"
 }
 
 # void bonding_depend(void)
 #
 # Sets up the dependancies for the module
 bonding_depend() {
-	after interface
-	before vlan dhcp
+    after interface
+    before vlan dhcp
 }
 
 # bool bonding_check_installed(void)
 #
 # Returns 1 if ifenslave is installed, otherwise 0
 bonding_check_installed() {
-	[[ -x /sbin/ifenslave ]] && return 0
-	${1:-false} && eerror "For link aggregation (bonding) support, emerge net-misc/ifenslave"
-	return 1
+    [[ -x /sbin/ifenslave ]] && return 0
+    ${1:-false} && eerror "For link aggregation (bonding) support, emerge net-misc/ifenslave"
+    return 1
 }
 
 # bool bonding_check_depends(void)
 #
 # Checks to see if we have the needed functions
 bonding_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_up interface_down interface_del_addresses; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "bonding: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_up interface_down interface_del_addresses; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "bonding: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool bonding_post_start(char *iface)
 #
 # Bonds the interface
 bonding_pre_start() {
-	local iface=$1 slaves s ifvar=$( bash_variable $1 )
+    local iface=$1 slaves s ifvar=$( bash_variable $1 )
 
-	eval slaves=\"\$\{slaves_${ifvar}\[@\]\}\"
-	[[ -z ${slaves} ]] && return 0
+    eval slaves=\"\$\{slaves_${ifvar}\[@\]\}\"
+    [[ -z ${slaves} ]] && return 0
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	if [[ ! -f /proc/net/bonding/${iface} ]]; then
-		eerror "${iface} is not capable of bonding"
-		return 1
-	fi
+    if [[ ! -f /proc/net/bonding/${iface} ]]; then
+	eerror "${iface} is not capable of bonding"
+	return 1
+    fi
 
-	ebegin "Adding slaves to ${iface}"
-	eindent
-	einfo "${slaves}"
-	
-	# Check that our slaves exist
-	for s in ${slaves}; do
-		interface_exists ${s} && continue
-		ewarn "interface ${s} does not exist"
-		return 1
-	done
-	
-	# Must force the slaves to a particular state before adding them
-	for s in ${slaves}; do
-		interface_del_addresses ${s}
-		interface_up ${s}
-	done
+    ebegin "Adding slaves to ${iface}"
+    eindent
+    einfo "${slaves}"
 
-	# now force the master to up
-	interface_up ${iface}
+    # Check that our slaves exist
+    for s in ${slaves}; do
+	interface_exists ${s} && continue
+	ewarn "interface ${s} does not exist"
+	return 1
+    done
 
-	# finally add in slaves
-	eoutdent
-	/sbin/ifenslave ${iface} ${slaves} >${devnull}
-	eend $?
+    # Must force the slaves to a particular state before adding them
+    for s in ${slaves}; do
+	interface_del_addresses ${s}
+	interface_up ${s}
+    done
 
-	return 0 #important
+    # now force the master to up
+    interface_up ${iface}
+
+    # finally add in slaves
+    eoutdent
+    /sbin/ifenslave ${iface} ${slaves} >${devnull}
+    eend $?
+
+    return 0 #important
 }
 
 # bool bonding_pre_stop(void)
@@ -92,32 +93,32 @@ bonding_pre_start() {
 #
 # Always returns 0 (true) 
 bonding_pre_stop() {
-	local iface=$1 slaves s
+    local iface=$1 slaves s
 
-	bonding_check_installed || return 0
+    bonding_check_installed || return 0
 
-	# return silently if this is not a bonding interface
-	[[ ! -f /proc/net/bonding/${iface} ]] && return 0
+    # return silently if this is not a bonding interface
+    [[ ! -f /proc/net/bonding/${iface} ]] && return 0
 
-	# don't trust the config, get the active list instead
-	slaves=$( sed -n -e 's/^Slave Interface: //p' /proc/net/bonding/${iface} )
-	[[ -z ${slaves} ]] && return 0
+    # don't trust the config, get the active list instead
+    slaves=$( sed -n -e 's/^Slave Interface: //p' /proc/net/bonding/${iface} )
+    [[ -z ${slaves} ]] && return 0
 
-	# remove all slaves
-	ebegin "Removing slaves from ${iface}"
-	eindent
-	einfo "${slaves}"
-	eoutdent
-	/sbin/ifenslave -d ${iface} ${slaves} &>${devnull}
+    # remove all slaves
+    ebegin "Removing slaves from ${iface}"
+    eindent
+    einfo "${slaves}"
+    eoutdent
+    /sbin/ifenslave -d ${iface} ${slaves} &>${devnull}
 
-	# reset all slaves
-	for s in ${slaves}; do
-		if interface_exists ${s} ; then
-			interface_del_addresses ${s}
-			interface_down ${s}
-		fi
-	done
+    # reset all slaves
+    for s in ${slaves}; do
+	if interface_exists ${s} ; then
+	    interface_del_addresses ${s}
+	    interface_down ${s}
+	fi
+    done
 
-	eend 0
-	return 0
+    eend 0
+    return 0
 }
diff --git a/net-scripts/net.modules.d/dhclient b/net-scripts/net.modules.d/dhclient
--- a/net-scripts/net.modules.d/dhclient
+++ b/net-scripts/net.modules.d/dhclient
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,45 +8,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 dhclient() {
-	LC_ALL=C /sbin/dhclient "$@"
+    LC_ALL=C /sbin/dhclient "$@"
 }
 
 # char* dhclient_provides(void)
 #
 # Returns a string to change module definition for starting up
 dhclient_provides() {
-	echo "dhcp"
+    echo "dhcp"
 }
 
 # void dhclient_depend(void)
 #
 # Sets up the dependancies for the module
 dhclient_depend() {
-	after interface
+    after interface
 }
 
 # bool dhclient_check_installed(void)
 #
 # Returns 1 if dhclient is installed, otherwise 0
 dhclient_check_installed() {
-	[[ -x /sbin/dhclient ]] && return 0
-	${1:-false} && eerror "For DHCP (dhclient) support, emerge net-misc/dhcp"
-	return 1
+    [[ -x /sbin/dhclient ]] && return 0
+    ${1:-false} && eerror "For DHCP (dhclient) support, emerge net-misc/dhcp"
+    return 1
 }
 
 # bool dhclient_check_depends(void)
 #
 # Checks to see if we have the needed functions
 dhclient_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_get_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "dhclient: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_get_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "dhclient: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* dhclient_get_vars(char *interface)
@@ -53,7 +54,7 @@ dhclient_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 dhclient_get_vars() {
-	echo "dhclient_${1} dhcp_${1}"
+    echo "dhclient_${1} dhcp_${1}"
 }
 
 # bool dhclient_stop(char *iface)
@@ -61,34 +62,34 @@ dhclient_get_vars() {
 # Stop dhclient on an interface
 # Always returns 0
 dhclient_stop() {
-	local iface=$1 dhcp release
-	local pidfile="/var/run/dhclient-$1.pid"
-	
-	dhclient_check_installed || return 0
-	[[ ! -f ${pidfile} ]] && return 0
+    local iface=$1 dhcp release
+    local pidfile="/var/run/dhclient-$1.pid"
 
-	# We check for a dhclient process first as if we attempt to release
-	# an interface for which dhclient has obtained an IP in the past
-	# it causes a "RELEASE" event anyway.
-	local pid=$( < ${pidfile} )
+    dhclient_check_installed || return 0
+    [[ ! -f ${pidfile} ]] && return 0
 
-	local ifvar=$( bash_variable ${iface} )
-	eval dhcp=\" \$\{dhcp_${ifvar}\} \"
+    # We check for a dhclient process first as if we attempt to release
+    # an interface for which dhclient has obtained an IP in the past
+    # it causes a "RELEASE" event anyway.
+    local pid=$( < ${pidfile} )
 
-	ebegin "Stopping dhclient on ${iface}"
-	if [[ ${dhcp} == *' release '* ]]; then
-		local r=$( dhclient -q -r -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} ${iface} )
-		[[ ${r} == "deconfig" ]]
-		eend $? "dhclient returned a ${r}"
-		[[ -f /var/cache/dhcp-${iface}.lease ]] \
-			&& rm -f /var/cache/dhcp-${iface}.lease
-	else
-		kill -s TERM ${pid} 2>/dev/null
-		clean_pidfile ${pidfile}
-		eend 0
-	fi
+    local ifvar=$( bash_variable ${iface} )
+    eval dhcp=\" \$\{dhcp_${ifvar}\} \"
 
-	return 0
+    ebegin "Stopping dhclient on ${iface}"
+    if [[ ${dhcp} == *' release '* ]]; then
+	local r=$( dhclient -q -r -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} ${iface} )
+	[[ ${r} == "deconfig" ]]
+	eend $? "dhclient returned a ${r}"
+	[[ -f /var/cache/dhcp-${iface}.lease ]] \
+	&& rm -f /var/cache/dhcp-${iface}.lease
+    else
+	kill -s TERM ${pid} 2>/dev/null
+	clean_pidfile ${pidfile}
+	eend 0
+    fi
+
+    return 0
 }
 
 # bool dhclient_start(char *iface)
@@ -97,42 +98,42 @@ dhclient_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 dhclient_start() {
-	local iface=$1 opts ifvar=$( bash_variable $1 )
-	local pidfile="/var/run/dhclient-$1.pid"
+    local iface=$1 opts ifvar=$( bash_variable $1 )
+    local pidfile="/var/run/dhclient-$1.pid"
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	# Bring up DHCP for this interface (or alias)
-	ebegin "Running dhclient"
+    # Bring up DHCP for this interface (or alias)
+    ebegin "Running dhclient"
 
-	if ! clean_pidfile ${pidfile} ; then
-		ewarn "dhclient is already running on ${iface}"
-		eend 0
-		return 0
-	fi
-
-	eval opts=\"\$\{dhclient_${ifvar}\}\"
-
-	if [[ ${background} == "yes" ]]; then
-		dhclient ${opts} -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} -q ${iface} &>/dev/null &
-		eend 0
-		go_background
-	fi
-
-	local x=$( dhclient ${opts} -1 -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} -q ${iface} )
-	# We just check the last 5 letters
-	[[ ${x:${#x} - 5:5} == "bound" ]]
-	if [[ $? != 0 ]]; then
-		# We need to kill the process if we fail
-		[[ -e ${pidfile} ]] && kill -s TERM $( < ${pidfile} ) 2>/dev/null
-		eend 1
-		return 1
-	fi
+    if ! clean_pidfile ${pidfile} ; then
+	ewarn "dhclient is already running on ${iface}"
 	eend 0
-
-	# DHCP succeeded, show address retrieved
-	local addr=$( interface_get_address ${iface} )
-	einfo "${iface} received address ${addr}"
-
 	return 0
+    fi
+
+    eval opts=\"\$\{dhclient_${ifvar}\}\"
+
+    if [[ ${background} == "yes" ]]; then
+	dhclient ${opts} -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} -q ${iface} &>/dev/null &
+	eend 0
+	go_background
+    fi
+
+    local x=$( dhclient ${opts} -1 -sf ${MODULES_DIR}/helpers.d/dhclient-wrapper -pf ${pidfile} -q ${iface} )
+    # We just check the last 5 letters
+    [[ ${x:${#x} - 5:5} == "bound" ]]
+    if [[ $? != 0 ]]; then
+	# We need to kill the process if we fail
+	[[ -e ${pidfile} ]] && kill -s TERM $( < ${pidfile} ) 2>/dev/null
+	eend 1
+	return 1
+    fi
+    eend 0
+
+    # DHCP succeeded, show address retrieved
+    local addr=$( interface_get_address ${iface} )
+    einfo "${iface} received address ${addr}"
+
+    return 0
 }
diff --git a/net-scripts/net.modules.d/dhcpcd b/net-scripts/net.modules.d/dhcpcd
--- a/net-scripts/net.modules.d/dhcpcd
+++ b/net-scripts/net.modules.d/dhcpcd
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,45 +8,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 dhcpcd() {
-	LC_ALL=C /sbin/dhcpcd "$@"
+    LC_ALL=C /sbin/dhcpcd "$@"
 }
 
 # char* dhcpcd_provides(void)
 #
 # Returns a string to change module definition for starting up
 dhcpcd_provides() {
-	echo "dhcp"
+    echo "dhcp"
 }
 
 # void dhcpcd_depend(void)
 #
 # Sets up the dependancies for the module
 dhcpcd_depend() {
-	after interface
+    after interface
 }
 
 # bool dhcpcd_check_installed(void)
 #
 # Returns 1 if dhcpcd is installed, otherwise 0
 dhcpcd_check_installed() {
-	[[ -x /sbin/dhcpcd ]] && return 0
-	${1:-false} && eerror "For DHCP (dhcpcd) support, emerge net-misc/dhcpcd"
-	return 1
+    [[ -x /sbin/dhcpcd ]] && return 0
+    ${1:-false} && eerror "For DHCP (dhcpcd) support, emerge net-misc/dhcpcd"
+    return 1
 }
 
 # bool dhcpcd_check_depends(void)
 #
 # Checks to see if we have the needed functions
 dhcpcd_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_get_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "dhcpcd: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_get_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "dhcpcd: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* dhcpcd_get_vars(char *interface)
@@ -53,7 +54,7 @@ dhcpcd_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 dhcpcd_get_vars() {
-	echo "dhcpcd_${1} dhcp_${1}"
+    echo "dhcpcd_${1} dhcp_${1}"
 }
 
 # bool dhcpcd_stop(char *iface)
@@ -63,27 +64,27 @@ dhcpcd_get_vars() {
 # Returns 0 (true) when a DHCP address dropped
 # otherwise return 1
 dhcpcd_stop() {
-	local iface=$1 count signal pidfile="/var/run/dhcpcd-$1.pid" dhcp
-	
-	dhcpcd_check_installed || return 0
+    local iface=$1 count signal pidfile="/var/run/dhcpcd-$1.pid" dhcp
 
-	[[ ! -f ${pidfile} ]] && return 0
+    dhcpcd_check_installed || return 0
 
-	ebegin "Stopping dhcpcd on ${iface}"
-	local pid=$( < ${pidfile} )
+    [[ ! -f ${pidfile} ]] && return 0
 
-	local ifvar=$( bash_variable ${iface} )
-	eval dhcp=\" \$\{dhcp_${ifvar}\} \"
-	if [[ ${dhcp} == *' release '* ]]; then
-		signal="HUP"
-	else
-		signal="TERM"
-	fi
+    ebegin "Stopping dhcpcd on ${iface}"
+    local pid=$( < ${pidfile} )
 
-	kill -s ${signal} ${pid} &>/dev/null 
-	process_finished ${pid} dhcpcd
-	eend $? "timed out"
-	return $?
+    local ifvar=$( bash_variable ${iface} )
+    eval dhcp=\" \$\{dhcp_${ifvar}\} \"
+    if [[ ${dhcp} == *' release '* ]]; then
+	signal="HUP"
+    else
+	signal="TERM"
+    fi
+
+    kill -s ${signal} ${pid} &>/dev/null 
+    process_finished ${pid} dhcpcd
+    eend $? "timed out"
+    return $?
 }
 
 # bool dhcpcd_start(char *iface)
@@ -92,48 +93,48 @@ dhcpcd_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 dhcpcd_start() {
-	local iface=$1 opts hostname pidfile="/var/run/dhcpcd-$1.pid" dhcp
-	local ifvar=$( bash_variable ${iface} )
+    local iface=$1 opts hostname pidfile="/var/run/dhcpcd-$1.pid" dhcp
+    local ifvar=$( bash_variable ${iface} )
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	# Get our options
-	eval opts=\"\$\{dhcpcd_${ifvar}\}\"
+    # Get our options
+    eval opts=\"\$\{dhcpcd_${ifvar}\}\"
 
-	# Map some generic options to dhcpcd
-	eval dhcp=\" \$\{dhcp_${ifvar}\} \"
-	[[ ${dhcp} == *' nodns '* ]] && opts="${opts} -R"
-	[[ ${dhcp} == *' nontp '* ]] && opts="${opts} -N"
-	[[ ${dhcp} == *' nonis '* ]] && opts="${opts} -Y"
+    # Map some generic options to dhcpcd
+    eval dhcp=\" \$\{dhcp_${ifvar}\} \"
+    [[ ${dhcp} == *' nodns '* ]] && opts="${opts} -R"
+    [[ ${dhcp} == *' nontp '* ]] && opts="${opts} -N"
+    [[ ${dhcp} == *' nonis '* ]] && opts="${opts} -Y"
 
-	# We transmit the hostname by default
-	if [[ ${opts} != *'-h '* ]]; then
-		hostname=$( hostname )
-		[[ -n ${hostname} && ${hostname} != "(none)" && ${hostname} != "localhost" ]] \
-			&& opts="-h ${hostname} ${opts}"
-	fi
+    # We transmit the hostname by default
+    if [[ ${opts} != *'-h '* ]]; then
+	hostname=$( hostname )
+	[[ -n ${hostname} && ${hostname} != "(none)" && ${hostname} != "localhost" ]] \
+	&& opts="-h ${hostname} ${opts}"
+    fi
 
-	# Bring up DHCP for this interface (or alias)
-	ebegin "Running dhcpcd"
+    # Bring up DHCP for this interface (or alias)
+    ebegin "Running dhcpcd"
 
-	if ! clean_pidfile ${pidfile} ; then
-		ewarn "dhcpcd is already running on ${iface}"
-		eend 0
-		return 0
-	fi
-
-	if [[ ${background} == "yes" ]]; then
-		eval "dhcpcd ${opts} -c /lib/rcscripts/net.modules.d/helpers.d/dhcpcd-backgrounder ${iface}" & >/dev/null
-		eend 0
-		go_background
-	fi
-
-	eval "dhcpcd ${opts} ${iface}"
-	eend $? || return 1
-
-	# DHCP succeeded, show address retrieved
-	local addr=$( interface_get_address ${iface} )
-	einfo "${iface} received address ${addr}"
-
+    if ! clean_pidfile ${pidfile} ; then
+	ewarn "dhcpcd is already running on ${iface}"
+	eend 0
 	return 0
+    fi
+
+    if [[ ${background} == "yes" ]]; then
+	eval "dhcpcd ${opts} -c /lib/rcscripts/net.modules.d/helpers.d/dhcpcd-backgrounder ${iface}" & >/dev/null
+	eend 0
+	go_background
+    fi
+
+    eval "dhcpcd ${opts} ${iface}"
+    eend $? || return 1
+
+    # DHCP succeeded, show address retrieved
+    local addr=$( interface_get_address ${iface} )
+    einfo "${iface} received address ${addr}"
+
+    return 0
 }
diff --git a/net-scripts/net.modules.d/essidnet b/net-scripts/net.modules.d/essidnet
--- a/net-scripts/net.modules.d/essidnet
+++ b/net-scripts/net.modules.d/essidnet
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -13,38 +14,38 @@
 #
 # Sets up the dependancies for the module
 essidnet_depend() {
-	before interface
-	after wireless
-	installed wireless
+    before interface
+    after wireless
+    installed wireless
 }
 
 # bool essidnet_check_installed(void)
 #
 # Always returns 0 as we are "installed" by wireless in the depend function
 essidnet_check_installed() {
-	return 0
+    return 0
 }
 
 # char* essidnet_provides(void)
 #
 # Returns a string to change module definition for starting up
 essidnet_provides() {
-	echo "essidnet"
+    echo "essidnet"
 }
 
 # bool essidnet_check_depends(void)
 #
 # Checks to see if we have the needed functions
 essidnet_check_depends() {
-	local f
+    local f
 
-	for f in wireless_check_extensions wireless_get_essid wireless_get_ap_mac_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "essidnet: missing required function ${f}\n"
-		return 1
-	done
+    for f in wireless_check_extensions wireless_get_essid wireless_get_ap_mac_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "essidnet: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool essidnet_start(char *iface)
@@ -55,36 +56,36 @@ essidnet_check_depends() {
 # of the AP connected to. MAC configuration takes precedence
 # Always returns 0
 essidnet_pre_start() {
-	local iface=$1
+    local iface=$1
 
-	wireless_check_extensions ${iface} || return 0
+    wireless_check_extensions ${iface} || return 0
 
-	local mod func evars evar vars x i mvars mac=$( wireless_get_ap_mac_address ${iface} )
-	local ifvar=$( bash_variable ${iface} )
-	local ESSID=$( wireless_get_essid ${iface} )
-	local essid=$( bash_variable ${ESSID} )
-	mac=${mac//:/}
+    local mod func evars evar vars x i mvars mac=$( wireless_get_ap_mac_address ${iface} )
+    local ifvar=$( bash_variable ${iface} )
+    local ESSID=$( wireless_get_essid ${iface} )
+    local essid=$( bash_variable ${ESSID} )
+    mac=${mac//:/}
 
-	vebegin "Configuring ${iface} for \"${ESSID//\\\\/\\\\}\"" 2>/dev/null
+    vebegin "Configuring ${iface} for \"${ESSID//\\\\/\\\\}\"" 2>/dev/null
 
-	for mod in ${MODULES[@]}; do
-		func="${mod}_get_vars"
-		if [[ $(type -t ${func}) == "function" ]]; then
-			evars=( $( ${func} ${essid} ) )
-			mvars=( $( ${func} ${mac} ) )
-			vars=( $( ${func} ${ifvar} ) )
-			for ((i = 0; i<${#mvars[@]}; i++)); do
-				eval x=( \"\$\{mac_${mvars[i]}\[@\]\}\" )
-				[[ -z ${x} ]] && eval x=( \"\$\{${evars[i]}\[@\]\}\" )
-				[[ -n ${x} ]] && eval "${vars[i]}=( "\"\$\{x\[@\]\}\"" )"
-			done
-		fi
-	done
+    for mod in ${MODULES[@]}; do
+	func="${mod}_get_vars"
+	if [[ $(type -t ${func}) == "function" ]]; then
+	    evars=( $( ${func} ${essid} ) )
+	    mvars=( $( ${func} ${mac} ) )
+	    vars=( $( ${func} ${ifvar} ) )
+	    for ((i = 0; i<${#mvars[@]}; i++)); do
+		eval x=( \"\$\{mac_${mvars[i]}\[@\]\}\" )
+		[[ -z ${x} ]] && eval x=( \"\$\{${evars[i]}\[@\]\}\" )
+		[[ -n ${x} ]] && eval "${vars[i]}=( "\"\$\{x\[@\]\}\"" )"
+	    done
+	fi
+    done
 
-	# Backwards compat for old gateway var
-	eval x=\"\$\{gateway_${essid}\}\"
-	[[ -n ${x} ]] && gateway="${iface}/${x}"
+    # Backwards compat for old gateway var
+    eval x=\"\$\{gateway_${essid}\}\"
+    [[ -n ${x} ]] && gateway="${iface}/${x}"
 
-	veend 0 2>/dev/null
-	return 0
+    veend 0 2>/dev/null
+    return 0
 }
diff --git a/net-scripts/net.modules.d/helpers.d/dhcp b/net-scripts/net.modules.d/helpers.d/dhcp
--- a/net-scripts/net.modules.d/helpers.d/dhcp
+++ b/net-scripts/net.modules.d/helpers.d/dhcp
@@ -14,28 +14,28 @@ action="$1"
 
 # Guess which interface module to load - we prefer iproute2
 if [[ -x /sbin/ip ]]; then
-	interface_module="iproute2"
+    interface_module="iproute2"
 elif [[ -x /sbin/ifconfig ]]; then
-	interface_module="ifconfig"
+    interface_module="ifconfig"
 else
-	echo "Can't find a known interface module" >&2
-	exit 1
+    echo "Can't find a known interface module" >&2
+    exit 1
 fi
 
 # iwconfig is the best bet for wireless - we use wpa_supplicant
 # only if we need to
 if [[ -x /usr/sbin/iwconfig ]]; then
-	wireless_module="iwconfig"
+    wireless_module="iwconfig"
 elif [[ -x /usr/sbin/wpa_supplicant && -S "/var/run/wpa_supplicant/${interface}" ]]; then
-	wireless_module="wpa_supplicant"
+    wireless_module="wpa_supplicant"
 fi
 
 # Load our modules
 . "${MODULES_DIR}/${interface_module}"
 function_wrap "${interface_module}" interface
 if [[ -n ${wireless_module} ]]; then
-	. "${MODULES_DIR}/${wireless_module}"
-	function_wrap "${wireless_module}" wireless
+    . "${MODULES_DIR}/${wireless_module}"
+    function_wrap "${wireless_module}" wireless
 fi
 
 auto_interface=${auto_interface:-"yes"}
@@ -44,53 +44,53 @@ auto_interface=${auto_interface:-"yes"}
 interface_is_up "${interface}" || interface_up "${interface}"
 
 case "${action}" in
-	"bound"|"renew")
-		# We handle these actions below
-		;;
-	"deconfig")
-		interface_del_addresses "${interface}"
-		mark_service_inactive "net.${interface}"
-		if [[ ${auto_interface} == "yes" ]]; then
-			remove_state "${interface}"
-			best_interface=$( select_best_interface )
-			apply_state "${best_interface}"
-		fi
-		echo "${action}"
-		exit 0
-		;;
-	"nak")
-		echo "${action}"
-		exit 0
-		;;
-	"leasefail")
-		mark_service_inactive "net.${interface}"
-		echo "${action}"
-		exit 0
-		;;
-	*)
-		echo "${action}"
-		echo "We don't handle that action" >&2
-		exit 1
-		;;
+    "bound"|"renew")
+    # We handle these actions below
+    ;;
+    "deconfig")
+    interface_del_addresses "${interface}"
+    mark_service_inactive "net.${interface}"
+    if [[ ${auto_interface} == "yes" ]]; then
+	remove_state "${interface}"
+	best_interface=$( select_best_interface )
+	apply_state "${best_interface}"
+    fi
+    echo "${action}"
+    exit 0
+    ;;
+    "nak")
+    echo "${action}"
+    exit 0
+    ;;
+    "leasefail")
+    mark_service_inactive "net.${interface}"
+    echo "${action}"
+    exit 0
+    ;;
+    *)
+    echo "${action}"
+    echo "We don't handle that action" >&2
+    exit 1
+    ;;
 esac
 
 # Map wireless ESSID variables to interface variables
 if wireless_check_extensions "${interface}" ; then
-        MODULES=( "${interface_module}" "essidnet" "system" )
-        source ${MODULES_DIR}/essidnet
-        essidnet_pre_start ${interface}
+    MODULES=( "${interface_module}" "essidnet" "system" )
+    source ${MODULES_DIR}/essidnet
+    essidnet_pre_start ${interface}
 fi
 
 # Calculate the metric for our routes
 ifvar=$( bash_variable ${interface} )
 eval metric=\"\$\{metric_${ifvar}\}\"
 if [[ -z ${metric} ]]; then
-	if [[ ${auto_interface} == "yes" ]]; then
-		metric=$( calculate_metric ${interface} )
-	else
-		metric=0
-	fi
-	eval metric_${ifvar}="${metric}"
+    if [[ ${auto_interface} == "yes" ]]; then
+	metric=$( calculate_metric ${interface} )
+    else
+	metric=0
+    fi
+    eval metric_${ifvar}="${metric}"
 fi
 
 # Configure our IP address
@@ -103,8 +103,8 @@ broadcast=${broadcast// }
 # If we don't have our address then we flush it and then add our new one
 curip=$( interface_get_address ${interface} )
 if [[ ${curip} != "${ip}/${cidr}" ]] ; then
-	interface_del_addresses ${interface}
-	interface_add_address ${interface} "${ip}/${cidr}" ${broadcast}
+    interface_del_addresses ${interface}
+    interface_add_address ${interface} "${ip}/${cidr}" ${broadcast}
 fi
 
 # Store the address in a cache for future usage
@@ -113,13 +113,13 @@ chmod 600 /var/cache/dhcp-${interface}.lease
 
 # Configure our default route - we only have 1 default route
 for r in ${router}; do
-	interface_default_route ${interface} ${r} ${metric:-0} && break
+    interface_default_route ${interface} ${r} ${metric:-0} && break
 done
 
 # Configure our hostname - but only if we need it
 if [[ -n ${hostname} ]]; then
-	x=$( /bin/hostname )
-	[[ ${x} == "(none)" || ${x} == "localhost" ]] && /bin/hostname "${hostname}"
+    x=$( /bin/hostname )
+    [[ ${x} == "(none)" || ${x} == "localhost" ]] && /bin/hostname "${hostname}"
 fi
 
 # Only setup the information we're told to
@@ -130,9 +130,9 @@ eval dhcp=\" \$\{dhcp_${ifvar}\} \"
 [[ ${dhcp} != *' nonis '* ]] && system_nis "${interface}"
 
 if [[ ${auto_interface} == "yes" ]]; then
-	save_state ${interface}
-	best_interface=$( select_best_interface )
-	apply_state ${best_interface}
+    save_state ${interface}
+    best_interface=$( select_best_interface )
+    apply_state ${best_interface}
 fi
 
 mark_service_started net.${interface}
diff --git a/net-scripts/net.modules.d/iproute2 b/net-scripts/net.modules.d/iproute2
--- a/net-scripts/net.modules.d/iproute2
+++ b/net-scripts/net.modules.d/iproute2
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,41 +8,41 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 ip() {
-	LC_ALL=C /sbin/ip "$@"
+    LC_ALL=C /sbin/ip "$@"
 }
 
 iproute2_tunnel() {
-	LC_ALL=C /sbin/ip tunnel "$@"
+    LC_ALL=C /sbin/ip tunnel "$@"
 }
 
 # void iproute2_depend(void)
 #
 # Sets up the dependancies for the module
 iproute2_depend() {
-	after macchanger wireless
+    after macchanger wireless
 }
 
 # bool iproute2_check_installed(void)
 #
 # Returns 1 if iproute2 is installed, otherwise 0
 iproute2_check_installed() {
-	local report=${1:-false} installed=0
-	if [[ ! -x /sbin/ip ]]; then
-		installed=1
-		${report} && eerror "For iproute2 support, emerge sys-apps/iproute2"
-	fi
-	if [[ ! -e /proc/net/netlink ]]; then
-		installed=1
-		${report} && eerror "iproute2 requires NetLink enabled in the kernel"
-	fi
-	return ${installed} 
+    local report=${1:-false} installed=0
+    if [[ ! -x /sbin/ip ]]; then
+	installed=1
+	${report} && eerror "For iproute2 support, emerge sys-apps/iproute2"
+    fi
+    if [[ ! -e /proc/net/netlink ]]; then
+	installed=1
+	${report} && eerror "iproute2 requires NetLink enabled in the kernel"
+    fi
+    return ${installed} 
 }
 
 # char* iproute2_provides(void)
 #
 # Returns a string to change module definition for starting up
 iproute2_provides() {
-	echo "interface"
+    echo "interface"
 }
 
 # char* iproute2_module(void)
@@ -50,47 +51,47 @@ iproute2_provides() {
 # This is needed by dhclient as we run different scripts
 # based on the interface
 iproute2_module() {
-	echo "iproute2"
+    echo "iproute2"
 }
 
 # bool iproute2_check_depends(void)
 #
 # Checks to see if we have the needed functions
 iproute2_check_depends() {
-	local f
+    local f
 
-	for f in interface_device; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "iproute2: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_device; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "iproute2: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool iproute2_exists(char *interface, bool report)
 #
 # Returns 1 if the interface exists, otherwise 0
 iproute2_exists() {
-	local e=$( ip addr show label $1 ) report=${2:-false}
-	[[ -n ${e} ]] && return 0
+    local e=$( ip addr show label $1 ) report=${2:-false}
+    [[ -n ${e} ]] && return 0
 
-	${report} && eerror "$1 does not exist"
-	return 1
+    ${report} && eerror "$1 does not exist"
+    return 1
 }
 
 # void iproute2_up(char *interface)
 #
 # provides a generic interface for bringing interfaces up
 iproute2_up() {
-	ip link set up dev $1
+    ip link set up dev $1
 }
 
 # void iproute2_down(char *interface)
 #
 # provides a generic interface for bringing interfaces up
 iproute2_down() {
-	ip link set down dev $1
+    ip link set down dev $1
 }
 
 # bool ifproute2_is_up(char *iface, bool withaddress)
@@ -99,19 +100,19 @@ iproute2_down() {
 # If withaddress is true then the interface has to have an IPv4 address
 # assigned as well
 iproute2_is_up() {
-	local check="\<UP\>" addr=${2:-false}
-	${addr} && check="${check}.*inet "
-	ip addr show $1 | grep -Eq "${check}" && return 0
-	return 1
+    local check="\<UP\>" addr=${2:-false}
+    ${addr} && check="${check}.*inet "
+    ip addr show $1 | grep -Eq "${check}" && return 0
+    return 1
 }
 
 # void iproute2_set_flag(char *iface, char *flag, bool enabled)
 #
 # Sets or disables the interface flag 
 iproute2_set_flag() {
-	local enable=$3 opt="on"
-	${enable} || opt="off"
-	ip link set $1 $2 ${opt}
+    local enable=$3 opt="on"
+    ${enable} || opt="off"
+    ip link set $1 $2 ${opt}
 }
 
 # void iproute2_get_address(char *interface)
@@ -119,23 +120,23 @@ iproute2_set_flag() {
 # Fetch the address retrieved by DHCP.  If successful, echoes the
 # address on stdout, otherwise echoes nothing.
 iproute2_get_address() {
-	ip -family inet addr show $1 \
-		| sed -n -e 's/.*inet \([^ ]*\).*/\1/p'
+    ip -family inet addr show $1 \
+    | sed -n -e 's/.*inet \([^ ]*\).*/\1/p'
 }
 
 # void iproute2_get_mac_address(char *interface)
 #
 # Fetch the mac address assingned to the network card
 iproute2_get_mac_address() {
-	ip link show $1 \
-		| sed -n -e 's/^.*\<\(..:..:..:..:..:..\)\>.*/\U\1/p'
+    ip link show $1 \
+    | sed -n -e 's/^.*\<\(..:..:..:..:..:..\)\>.*/\U\1/p'
 }
 
 # void iproute2_set_mac_address(char *interface, char *mac)
 #
 # Assigned the mac address to the network card
 iproute2_set_mac_address() {
-	ip link set address $2 dev $1
+    ip link set address $2 dev $1
 }
 
 # void iproute2_get_aliases_rev(char *interface)
@@ -144,17 +145,17 @@ iproute2_set_mac_address() {
 # Outputs a space-separated list on stdout, in reverse order, for
 # example "eth0:2 eth0:1"
 iproute2_get_aliases_rev() {
-	local iface=$( interface_device $1 )
-	ip addr show dev ${iface} | grep -o "${iface}:[0-9].*" | tac
+    local iface=$( interface_device $1 )
+    ip addr show dev ${iface} | grep -o "${iface}:[0-9].*" | tac
 }
 
 # bool iproute2_del_addresses(char *interface, bool report)
 #
 # Remove addresses from interface.
 iproute2_del_addresses() {
-	ip addr flush label $1 scope global &>/dev/null
-	ip addr flush label $1 scope host &>/dev/null
-	return 0
+    ip addr flush label $1 scope global &>/dev/null
+    ip addr flush label $1 scope host &>/dev/null
+    return 0
 }
 
 # char* iproute2_get_vars(char *interface)
@@ -162,27 +163,27 @@ iproute2_del_addresses() {
 # Returns a string spaced with possible user set
 # configuration variables
 iproute2_get_vars() {
-	echo "config_$1 routes_$1 fallback_$1 metric_$1 ipaddr_$1 ipaddr_fallback_$1 iproute_$1 inet6_$1"
+    echo "config_$1 routes_$1 fallback_$1 metric_$1 ipaddr_$1 ipaddr_fallback_$1 iproute_$1 inet6_$1"
 }
 
 # bool iproute2_get_old_config(char *iface)
 #
 # Returns config and config_fallback for the given interface
 iproute2_get_old_config() {
-	local ifvar=$( bash_variable $1 ) inet6
+    local ifvar=$( bash_variable $1 ) inet6
 
-	# iproute2-style config vars
-	eval config=( \"\$\{ipaddr_${ifvar}\[@\]\}\" )
-	eval config_fallback=( \"\$\{ipaddr_fallback_${ifvar}\[@\]\}\" )
-	eval inet6=( \"\$\{inet6_${ifvar}\[@\]\}\" )
+    # iproute2-style config vars
+    eval config=( \"\$\{ipaddr_${ifvar}\[@\]\}\" )
+    eval config_fallback=( \"\$\{ipaddr_fallback_${ifvar}\[@\]\}\" )
+    eval inet6=( \"\$\{inet6_${ifvar}\[@\]\}\" )
 
-	# BACKWARD COMPATIBILITY: check for space-separated inet6 addresses
-	[[ ${#inet6[@]} == 1 && ${inet6} == *' '* ]] && inet6=( ${inet6} )
+    # BACKWARD COMPATIBILITY: check for space-separated inet6 addresses
+    [[ ${#inet6[@]} == 1 && ${inet6} == *' '* ]] && inet6=( ${inet6} )
 
-	# Add inet6 addresses to our config if required
-	[[ -n ${inet6} ]] && config=( "${config[@]}" "${inet6[@]}" )
+    # Add inet6 addresses to our config if required
+    [[ -n ${inet6} ]] && config=( "${config[@]}" "${inet6[@]}" )
 
-	return 0
+    return 0
 }
 
 # bool iproute2_iface_stop(char *interface)
@@ -191,14 +192,14 @@ iproute2_get_old_config() {
 #
 # Returns 0 (true) when successful, non-zero (false) on failure
 iproute2_iface_stop() {
-	local label=$1 iface=$( interface_device $1 )
+    local label=$1 iface=$( interface_device $1 )
 
-	# Shut down the link if this isn't an alias or vlan
-	if [[ ${label} == ${iface} ]]; then
-		iproute2_down ${iface}
-		return $?
-	fi
-	return 0
+    # Shut down the link if this isn't an alias or vlan
+    if [[ ${label} == ${iface} ]]; then
+	iproute2_down ${iface}
+	return $?
+    fi
+    return 0
 }
 
 # bool iproute2_add_address(char *interface, char *options ...)
@@ -206,67 +207,67 @@ iproute2_iface_stop() {
 # Adds an the specified address to the interface
 # returns 0 on success and non-zero on failure
 iproute2_add_address() {
-	local iface=$1 x
+    local iface=$1 x
 
-	iproute2_exists ${iface} true || return 1
+    iproute2_exists ${iface} true || return 1
 
-	# Extract the config
-	local -a config=( "$@" )
-	config=( ${config[@]:1} )
+    # Extract the config
+    local -a config=( "$@" )
+    config=( ${config[@]:1} )
 
-	# Convert an ifconfig line to iproute2
-	local n=${#config[@]};
-	for (( x=0; x<n; x++ )); do
-		case ${config[x]} in
-			netmask)
-				config[0]="${config[0]}/$( netmask2cidr ${config[x+1]} )"
-				unset config[x] config[x+1]
-				;;
-			mtu)
-				ip link set mtu ${config[x+1]} dev ${iface}
-				unset config[x] config[x+1]
-				;;
-		esac
-	done
-	config=( "${config[@]//pointtopoint/peer}" )
+    # Convert an ifconfig line to iproute2
+    local n=${#config[@]};
+    for (( x=0; x<n; x++ )); do
+	case ${config[x]} in
+	    netmask)
+	    config[0]="${config[0]}/$( netmask2cidr ${config[x+1]} )"
+	    unset config[x] config[x+1]
+	    ;;
+	    mtu)
+	    ip link set mtu ${config[x+1]} dev ${iface}
+	    unset config[x] config[x+1]
+	    ;;
+	esac
+    done
+    config=( "${config[@]//pointtopoint/peer}" )
 
-	# Always scope lo addresses as host unless specified otherwise
-	[[ ${iface} == "lo" && " ${config[@]} " != *' scope '* ]] \
-		&& config=( "${config[@]}" "scope host" )
+    # Always scope lo addresses as host unless specified otherwise
+    [[ ${iface} == "lo" && " ${config[@]} " != *' scope '* ]] \
+    && config=( "${config[@]}" "scope host" )
 
-        # Work out a broadcast if none supplied
-	[[ ${config[@]} != *' brd '* && ${config[@]} != *' broadcast '* ]] \
-	    && config=( "${config[@]}" "brd +" )
+    # Work out a broadcast if none supplied
+    [[ ${config[@]} != *' brd '* && ${config[@]} != *' broadcast '* ]] \
+    && config=( "${config[@]}" "brd +" )
 
-	# Make sure interface is marked UP
-	# This is required for IPv6 addresses
-	iproute2_up ${iface}
+    # Make sure interface is marked UP
+    # This is required for IPv6 addresses
+    iproute2_up ${iface}
 
-	# Some kernels like to apply lo with an address when they are brought up
-	local r
-	if [[ ${iface} == "lo" && ${config[@]} == "127.0.0.1/8 brd 127.255.255.255 scope host" ]]; then
-		ip addr add dev ${iface} ${config[@]} 2>/dev/null
-		r=0
-	else
-		ip addr add dev ${iface} ${config[@]}
-		r=$?
-	fi
+    # Some kernels like to apply lo with an address when they are brought up
+    local r
+    if [[ ${iface} == "lo" && ${config[@]} == "127.0.0.1/8 brd 127.255.255.255 scope host" ]]; then
+	ip addr add dev ${iface} ${config[@]} 2>/dev/null
+	r=0
+    else
+	ip addr add dev ${iface} ${config[@]}
+	r=$?
+    fi
 
-	local metric ifvar=$( bash_variable ${iface} )
-	# Remove the newly added route and replace with our metric
-	eval metric=\"\$\{metric_${ifvar}\}\"
-	[[ ${metric} == 0 || ${auto_interface} != "yes" ]] && return ${r}
-	
-	local network=$( ip_network ${config[0]} )
-	[[ -z ${network} ]] && return ${r}
+    local metric ifvar=$( bash_variable ${iface} )
+    # Remove the newly added route and replace with our metric
+    eval metric=\"\$\{metric_${ifvar}\}\"
+    [[ ${metric} == 0 || ${auto_interface} != "yes" ]] && return ${r}
 
-	local cidr=${config[0]}
-	cidr=${cidr##*/}
-	
-	ip route del ${network}/${cidr} dev ${iface}
-	ip route add ${network}/${cidr} metric ${metric} dev ${iface}
-	
-	return ${r}
+    local network=$( ip_network ${config[0]} )
+    [[ -z ${network} ]] && return ${r}
+
+    local cidr=${config[0]}
+    cidr=${cidr##*/}
+
+    ip route del ${network}/${cidr} dev ${iface}
+    ip route add ${network}/${cidr} metric ${metric} dev ${iface}
+
+    return ${r}
 }
 
 # bool iproute2_post_start(char *interface)
@@ -274,42 +275,42 @@ iproute2_add_address() {
 # Runs any post_start stuff on our interface and adds routes
 # Always returns 0
 iproute2_post_start() {
-	local iface=$1 ifvar=$( bash_variable $1 ) routes e r metric m
+    local iface=$1 ifvar=$( bash_variable $1 ) routes e r metric m
 
-	# Make sure interface is marked UP
-	iproute2_up ${iface}
+    # Make sure interface is marked UP
+    iproute2_up ${iface}
 
-	eval routes=( \"\$\{routes_${ifvar}\[@\]\}\" )
-	eval metric=\"\$\{metric_${ifvar}\:-0}\"
+    eval routes=( \"\$\{routes_${ifvar}\[@\]\}\" )
+    eval metric=\"\$\{metric_${ifvar}\:-0}\"
 
-	# Test for old style ipaddr variable
-	if [[ -z ${routes} ]]; then
-		eval routes=( \"\$\{iproute_${ifvar}\[@\]\}\" )
-	fi
+    # Test for old style ipaddr variable
+    if [[ -z ${routes} ]]; then
+	eval routes=( \"\$\{iproute_${ifvar}\[@\]\}\" )
+    fi
 
-	[[ -z ${routes} ]] && return 0
+    [[ -z ${routes} ]] && return 0
 
-	# Set routes with ip route -- this might also include default route
-	einfo "Adding routes"
-	eindent
-	for x in "${routes[@]}"; do
-		ebegin "${x}"
+    # Set routes with ip route -- this might also include default route
+    einfo "Adding routes"
+    eindent
+    for x in "${routes[@]}"; do
+	ebegin "${x}"
 
-		# Support net-tools routing too
-		x=${x//gw/via}
-		x=${x//-A inet6}
-		x=${x//-net}
-		[[ ${x} == *'-host'* ]] && x="${x//-host} scope host"
+	# Support net-tools routing too
+	x=${x//gw/via}
+	x=${x//-A inet6}
+	x=${x//-net}
+	[[ ${x} == *'-host'* ]] && x="${x//-host} scope host"
 
-		# Add a metric if we don't have one
-		[[ ${x} != *' metric '* ]] && x="${x} metric ${metric}"
-	
-		ip route append ${x} dev ${iface}
-		eend $?
-	done
-	eoutdent
+	# Add a metric if we don't have one
+	[[ ${x} != *' metric '* ]] && x="${x} metric ${metric}"
 
-	return 0
+	ip route append ${x} dev ${iface}
+	eend $?
+    done
+    eoutdent
+
+    return 0
 }
 
 # void iproute2_default_route(char* interface, char* gateway_ip, int metric)
@@ -317,8 +318,8 @@ iproute2_post_start() {
 # Force default route to the specified gateway, optionally on
 # the given interface
 iproute2_default_route() {
-	local metric=${3:-0}
+    local metric=${3:-0}
 
-	ip route change default via $2 metric ${metric} dev $1 2>/dev/null \
-	|| ip route append default via $2 metric ${metric} dev $1 2>/dev/null
+    ip route change default via $2 metric ${metric} dev $1 2>/dev/null \
+    || ip route append default via $2 metric ${metric} dev $1 2>/dev/null
 }
diff --git a/net-scripts/net.modules.d/iptunnel b/net-scripts/net.modules.d/iptunnel
--- a/net-scripts/net.modules.d/iptunnel
+++ b/net-scripts/net.modules.d/iptunnel
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -8,37 +9,37 @@
 #
 # Returns a string to change module definition for starting up
 iptunnel_provides() {
-	echo "iptunnel"
+    echo "iptunnel"
 }
 
 # void iptunnel_depend(void)
 #
 # Sets up the dependancies for the module
 iptunnel_depend() {
-	after wireless
-	before interface
+    after wireless
+    before interface
 }
 
 # bool iptunnel_check_installed(void)
 #
 # Tunnelling is provided by the interface
 iptunnel_check_installed() {
-	return 0
+    return 0
 }
 
 # bool iptunnel_check_depends(void)
 #
 # Checks to see if we have the needed functions
 iptunnel_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_tunnel; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "iptunnel: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_tunnel; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "iptunnel: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* iptunnel_get_vars(char *interface)
@@ -46,23 +47,23 @@ iptunnel_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 iptunnel_get_vars() {
-	echo "iptunnel_$1"
+    echo "iptunnel_$1"
 }
 
 # bool iptunnel_pre_start(char *iface)
 #
 # Create the device, give it the right perms
 iptunnel_pre_start() {
-	local iface=$1 opts ifvar=$( bash_variable $1 )
+    local iface=$1 opts ifvar=$( bash_variable $1 )
 
-	# Get our options
-	eval opts=\"\$\{iptunnel_${ifvar}\}\"
-	[[ -z ${opts} ]] && return 0
+    # Get our options
+    eval opts=\"\$\{iptunnel_${ifvar}\}\"
+    [[ -z ${opts} ]] && return 0
 
-	ebegin "Creating tunnel ${iface}"
-	interface_tunnel add ${iface} ${opts}
-	eend $?
-	return $?
+    ebegin "Creating tunnel ${iface}"
+    interface_tunnel add ${iface} ${opts}
+    eend $?
+    return $?
 
 }
 
@@ -70,13 +71,13 @@ iptunnel_pre_start() {
 #
 # Removes the device
 iptunnel_stop() {
-	local iface=$1
-	
-	interface_exists ${iface} || return 0
-	[[ -z $( interface_tunnel show ${iface} 2>/dev/null ) ]] && return 0
-	
-	ebegin "Destroying tunnel ${iface}"
-	interface_tunnel del ${iface}
-	eend $?
-	return $?
+    local iface=$1
+
+    interface_exists ${iface} || return 0
+    [[ -z $( interface_tunnel show ${iface} 2>/dev/null ) ]] && return 0
+
+    ebegin "Destroying tunnel ${iface}"
+    interface_tunnel del ${iface}
+    eend $?
+    return $?
 }
diff --git a/net-scripts/net.modules.d/macchanger b/net-scripts/net.modules.d/macchanger
--- a/net-scripts/net.modules.d/macchanger
+++ b/net-scripts/net.modules.d/macchanger
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -8,14 +9,14 @@
 #
 # Returns a string to change module definition for starting up
 macchanger_provides() {
-	echo "macchanger"
+    echo "macchanger"
 }
 
 # void macchanger_depend(void)
 #
 # Sets up the dependancies for the module
 macchanger_depend() {
-	before interface wireless
+    before interface wireless
 }
 
 # bool macchanger_check_installed(void)
@@ -23,101 +24,100 @@ macchanger_depend() {
 # macchanger is always installed as an interface can change to a specific
 # mac address, and an interface is always installed
 macchanger_check_installed() {
-	return 0
+    return 0
 }
 
 # bool macchanger_check_depends(void)
 #
 # Checks to see if we have the needed functions
 macchanger_check_depends() {
-	local f
+    local f
 
-	for f in interface_get_mac_address interface_set_mac_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "macchanger: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_get_mac_address interface_set_mac_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "macchanger: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool macchanger_pre_start(char *iface)
 #
 # Configures the MAC address for iface 
 macchanger_pre_start() {
-	# We don't change MAC addresses from background
-	${IN_BACKGROUND} && return 0
+    # We don't change MAC addresses from background
+    ${IN_BACKGROUND} && return 0
 
-	local iface=$1 mac opts ifvar=$( bash_variable $1 )
+    local iface=$1 mac opts ifvar=$( bash_variable $1 )
 
-	eval mac=\"\$\{mac_${ifvar}\}\"
-	[[ -z ${mac} ]] && return 0
+    eval mac=\"\$\{mac_${ifvar}\}\"
+    [[ -z ${mac} ]] && return 0
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	ebegin "Changing MAC address of ${iface}"
+    ebegin "Changing MAC address of ${iface}"
 
-	mac=$( echo ${mac} | tr '[:upper:]' '[:lower:]' )
-	case "${mac}" in
-		# specific mac-addr, i wish there were a shorter way to specify this 
-		[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f])
-			# We don't need macchanger to change to a specific mac address
-			interface_set_mac_address ${iface} ${mac}
-			eend $?
-			if [[ $? == 0 ]]; then
-				mac=$( interface_get_mac_address ${iface} )
-				eindent
-				einfo "changed to ${mac}"
-				eoutdent
-				return 0
-			fi
-			;;
-				
-
-		# increment MAC address, default macchanger behavior
-		increment) opts="${opts}" ;;
-
-		# randomize just the ending bytes
-		random-ending) opts="${opts} -e" ;;
-
-		# keep the same kind of physical layer (eg fibre, copper)
-		random-samekind) opts="${opts} -a" ;;
-
-		# randomize to any known vendor of any physical layer type
-		random-anykind) opts="${opts} -A" ;;
-
-		# fully random bytes
-		random-full) opts="${opts} -r" ;;
-
-		# default case is just to pass on all the options
-		*) opts="${opts} ${mac}" ;;
-	esac
-
-	if [[ ! -x /sbin/macchanger ]]; then
-		eerror "For changing MAC addresses, emerge net-analyzer/macchanger"
-		return 1
+    mac=$( echo ${mac} | tr '[:upper:]' '[:lower:]' )
+    case "${mac}" in
+	# specific mac-addr, i wish there were a shorter way to specify this 
+	[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f])
+	# We don't need macchanger to change to a specific mac address
+	interface_set_mac_address ${iface} ${mac}
+	eend $?
+	if [[ $? == 0 ]]; then
+	    mac=$( interface_get_mac_address ${iface} )
+	    eindent
+	    einfo "changed to ${mac}"
+	    eoutdent
+	    return 0
 	fi
+	;;
 
-	# The interface needs to be up for macchanger to work most of the time
-	interface_down ${iface}
+	# increment MAC address, default macchanger behavior
+	increment) opts="${opts}" ;;
 
+	# randomize just the ending bytes
+	random-ending) opts="${opts} -e" ;;
+
+	# keep the same kind of physical layer (eg fibre, copper)
+	random-samekind) opts="${opts} -a" ;;
+
+	# randomize to any known vendor of any physical layer type
+	random-anykind) opts="${opts} -A" ;;
+
+	# fully random bytes
+	random-full) opts="${opts} -r" ;;
+
+	# default case is just to pass on all the options
+	*) opts="${opts} ${mac}" ;;
+    esac
+
+    if [[ ! -x /sbin/macchanger ]]; then
+	eerror "For changing MAC addresses, emerge net-analyzer/macchanger"
+	return 1
+    fi
+
+    # The interface needs to be up for macchanger to work most of the time
+    interface_down ${iface}
+
+    mac=$( /sbin/macchanger ${opts} ${iface} | sed -n -e 's/^Faked MAC:.*\<\(..:..:..:..:..:..\)\>.*/\U\1/p' )
+
+    # Sometimes the interface needs to be up ....
+    if [[ -z ${mac} ]]; then
+	interface_up ${iface}
 	mac=$( /sbin/macchanger ${opts} ${iface} | sed -n -e 's/^Faked MAC:.*\<\(..:..:..:..:..:..\)\>.*/\U\1/p' )
+    fi
 
-	# Sometimes the interface needs to be up ....
-	if [[ -z ${mac} ]]; then
-		interface_up ${iface}
-		mac=$( /sbin/macchanger ${opts} ${iface} | sed -n -e 's/^Faked MAC:.*\<\(..:..:..:..:..:..\)\>.*/\U\1/p' )
-	fi
+    if [[ -z ${mac} ]]; then
+	eend 1 "Failed to set MAC address"
+	return 1
+    fi
 
-	if [[ -z ${mac} ]]; then
-		eend 1 "Failed to set MAC address"
-		return 1
-	fi
+    eend 0
+    eindent
+    einfo "changed to ${mac}"
+    eoutdent
 
-	eend 0
-	eindent
-	einfo "changed to ${mac}"
-	eoutdent
-
-	return 0 #important
+    return 0 #important
 }
diff --git a/net-scripts/net.modules.d/pump b/net-scripts/net.modules.d/pump
--- a/net-scripts/net.modules.d/pump
+++ b/net-scripts/net.modules.d/pump
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,45 +8,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 pump() {
-	LC_ALL=C /sbin/pump "$@"
+    LC_ALL=C /sbin/pump "$@"
 }
 
 # char* pump_provides(void)
 #
 # Returns a string to change module definition for starting up
 pump_provides() {
-	echo "dhcp"
+    echo "dhcp"
 }
 
 # void pump_depend(void)
 #
 # Sets up the dependancies for the module
 pump_depend() {
-	after interface
+    after interface
 }
 
 # bool pump_check_installed(void)
 #
 # Returns 1 if pump is installed, otherwise 0
 pump_check_installed() {
-	[[ -x /sbin/pump ]] && return 0
-	${1:-false} && eerror "For DHCP (pump) support, emerge net-misc/pump"
-	return 1
+    [[ -x /sbin/pump ]] && return 0
+    ${1:-false} && eerror "For DHCP (pump) support, emerge net-misc/pump"
+    return 1
 }
 
 # bool pump_check_depends(void)
 #
 # Checks to see if we have the needed functions
 pump_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_get_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "pump: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_get_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "pump: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* pump_get_vars(char *interface)
@@ -53,7 +54,7 @@ pump_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 pump_get_vars() {
-	echo "pump_$1 dhcp_$1"
+    echo "pump_$1 dhcp_$1"
 }
 
 # bool pump_stop(char *iface)
@@ -62,26 +63,26 @@ pump_get_vars() {
 # Return 0 if pump is not running or we stop it successfully
 # Otherwise 1
 pump_stop() {
-	local iface=$1 count e
-	
-	pump_check_installed || return 0
+    local iface=$1 count e
 
-	# We check for a pump process first as querying for status
-	# causes pump to spawn a process
-	pidof pump &>/dev/null || return 0
+    pump_check_installed || return 0
 
-	e=$( pump --status --interface ${iface} 2>/dev/null | grep ${iface} )
-	[[ -z ${e} ]] && return 1
-	
-	ebegin "Stopping pump on ${iface}"
-	for ((count = 0; count < 9; count = count + 1)); do
-		e=$( pump --release --interface ${iface} 2>/dev/null )
-		[[ -z ${e} ]] && break
-		sleep 1
-	done
-	[[ ${count} -lt 9 ]]
-	eend $? "Timed out"
-	return $?
+    # We check for a pump process first as querying for status
+    # causes pump to spawn a process
+    pidof pump &>/dev/null || return 0
+
+    e=$( pump --status --interface ${iface} 2>/dev/null | grep ${iface} )
+    [[ -z ${e} ]] && return 1
+
+    ebegin "Stopping pump on ${iface}"
+    for ((count = 0; count < 9; count = count + 1)); do
+	e=$( pump --release --interface ${iface} 2>/dev/null )
+	[[ -z ${e} ]] && break
+	sleep 1
+    done
+    [[ ${count} -lt 9 ]]
+    eend $? "Timed out"
+    return $?
 }
 
 # bool pump_start(char *iface)
@@ -91,38 +92,38 @@ pump_stop() {
 # Returns 0 (true) when a dhcp address is obtained, otherwise
 # the return value from pump
 pump_start() {
-	local iface=$1 opts hostname dhcp ifvar=$( bash_variable $1 )
+    local iface=$1 opts hostname dhcp ifvar=$( bash_variable $1 )
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	eval opts=\"\$\{pump_${ifvar}\}\"
+    eval opts=\"\$\{pump_${ifvar}\}\"
 
-	# Map some generic options to pump
-	eval dhcp=\" \$\{dhcp_${ifvar}\} \"
-	[[ ${dhcp} == *' nodns '* ]] && opts="${opts} --no-dns"
+    # Map some generic options to pump
+    eval dhcp=\" \$\{dhcp_${ifvar}\} \"
+    [[ ${dhcp} == *' nodns '* ]] && opts="${opts} --no-dns"
 
-	# We transmit the hostname by default
-	if [[ ${opts} != *'-h '* && ${opts} != '*--hostname='* ]]; then
-		hostname=$( hostname )
-		[[ -n ${hostname} && ${hostname} != "(none)" && ${hostname} != localhost ]] \
-			&& opts="--hostname=${hostname} ${opts}"
-	fi
+    # We transmit the hostname by default
+    if [[ ${opts} != *'-h '* && ${opts} != '*--hostname='* ]]; then
+	hostname=$( hostname )
+	[[ -n ${hostname} && ${hostname} != "(none)" && ${hostname} != localhost ]] \
+	&& opts="--hostname=${hostname} ${opts}"
+    fi
 
-	# Bring up DHCP for this interface (or alias)
-	ebegin "Running pump"
-	pump ${opts} --win-client-ident --interface ${iface}
-	eend $? || return $?
+    # Bring up DHCP for this interface (or alias)
+    ebegin "Running pump"
+    pump ${opts} --win-client-ident --interface ${iface}
+    eend $? || return $?
 
-	# pump succeeded, show address retrieved
-	local addr=$( interface_get_address ${iface} )
-	einfo "${iface} received address ${addr}"
+    # pump succeeded, show address retrieved
+    local addr=$( interface_get_address ${iface} )
+    einfo "${iface} received address ${addr}"
 
-	eval peer=\"\$\{dhcp_ntp_${iface}\}\"
-	[[ -z ${peer} ]] && eval peer=\"\$\{dhcp_ntp\}\"
-	if [[ ${peer} != "no" ]]; then
-		eval ntp_servers_${ifvar}=$( pump -i ${iface} --status | sed -n -e 's/^.*Ntpservers: //p' )
-		system_ntp
-	fi
+    eval peer=\"\$\{dhcp_ntp_${iface}\}\"
+    [[ -z ${peer} ]] && eval peer=\"\$\{dhcp_ntp\}\"
+    if [[ ${peer} != "no" ]]; then
+	eval ntp_servers_${ifvar}=$( pump -i ${iface} --status | sed -n -e 's/^.*Ntpservers: //p' )
+	system_ntp
+    fi
 
-	return 0
+    return 0
 }
diff --git a/net-scripts/net.modules.d/udhcpc b/net-scripts/net.modules.d/udhcpc
--- a/net-scripts/net.modules.d/udhcpc
+++ b/net-scripts/net.modules.d/udhcpc
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,45 +8,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 udhcpc() {
-	LC_ALL=C /sbin/udhcpc "$@"
+    LC_ALL=C /sbin/udhcpc "$@"
 }
 
 # char* udhcpc_provides(void)
 #
 # Returns a string to change module definition for starting up
 udhcpc_provides() {
-	echo "dhcp"
+    echo "dhcp"
 }
 
 # void udhcpc_depend(void)
 #
 # Sets up the dependancies for the module
 udhcpc_depend() {
-	after interface
+    after interface
 }
 
 # bool udhcpc_check_installed(void)
 #
 # Returns 1 if udhcpc is installed, otherwise 0
 udhcpc_check_installed() {
-	[[ -x /sbin/udhcpc ]] && return 0
-	${1:-false} && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
-	return 1
+    [[ -x /sbin/udhcpc ]] && return 0
+    ${1:-false} && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
+    return 1
 }
 
 # bool udhcpc_check_depends(void)
 #
 # Checks to see if we have the needed functions
 udhcpc_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists interface_get_address; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "udhcpc: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists interface_get_address; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "udhcpc: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* udhcpc_get_vars(char *interface)
@@ -53,7 +54,7 @@ udhcpc_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 udhcpc_get_vars() {
-	echo "udhcpc_$1 dhcp_$1"
+    echo "udhcpc_$1 dhcp_$1"
 }
 
 # bool udhcpc_stop(char *iface)
@@ -61,35 +62,35 @@ udhcpc_get_vars() {
 # Stops udhcpc running on an interface
 # Return 1 if we fail to stop udhcpc (if it's running) otherwise 0
 udhcpc_stop() {
-	local iface=$1 count release pidfile="/var/run/udhcpc-$1.pid" dhcp
+    local iface=$1 count release pidfile="/var/run/udhcpc-$1.pid" dhcp
 
-	udhcpc_check_installed || return 0
-	[[ ! -f ${pidfile} ]] && return 0
+    udhcpc_check_installed || return 0
+    [[ ! -f ${pidfile} ]] && return 0
 
-	ebegin "Stopping udhcpc on ${iface}"
-	local pid=$( < ${pidfile} ) e=true
+    ebegin "Stopping udhcpc on ${iface}"
+    local pid=$( < ${pidfile} ) e=true
 
-	local ifvar=$( bash_variable ${iface} )
-	# Release the lease if told to
-	eval dhcp=\" \$\{dhcp_${ifvar}\} \"
-	if [[ ${dhcp} == *' release '* ]]; then
-		kill -s USR2 ${pid} &>/dev/null
-		[[ -f /var/cache/dhcp-${iface}.lease ]] \
-			&& rm /var/cache/dhcp-${iface}.lease
-	fi
+    local ifvar=$( bash_variable ${iface} )
+    # Release the lease if told to
+    eval dhcp=\" \$\{dhcp_${ifvar}\} \"
+    if [[ ${dhcp} == *' release '* ]]; then
+	kill -s USR2 ${pid} &>/dev/null
+	[[ -f /var/cache/dhcp-${iface}.lease ]] \
+	&& rm /var/cache/dhcp-${iface}.lease
+    fi
 
-	kill -s TERM ${pid} &>/dev/null
+    kill -s TERM ${pid} &>/dev/null
 
-	# udhcp-0.9.8-r3 and earlier do not process signals correctly
-	# so we need to kill them off
-	if [[ -d /proc/${pid} ]]; then
-		kill -s KILL ${pid} &>/dev/null
-		[[ -d /proc/${pid} ]] && e=false
-	fi
+    # udhcp-0.9.8-r3 and earlier do not process signals correctly
+    # so we need to kill them off
+    if [[ -d /proc/${pid} ]]; then
+	kill -s KILL ${pid} &>/dev/null
+	[[ -d /proc/${pid} ]] && e=false
+    fi
 
-	${e}
-	eend $?
-	return $?
+    ${e}
+    eend $?
+    return $?
 }
 
 # bool udhcpc_start(char *iface)
@@ -98,48 +99,48 @@ udhcpc_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 udhcpc_start() {
-	local iface=$1 opts hostname pidfile="/var/run/udhcpc-$1.pid"
-	local cachefile="/var/cache/dhcp-${1}.lease" x
+    local iface=$1 opts hostname pidfile="/var/run/udhcpc-$1.pid"
+    local cachefile="/var/cache/dhcp-${1}.lease" x
 
-	interface_exists ${iface} true || return 1
+    interface_exists ${iface} true || return 1
 
-	local ifvar=$( bash_variable ${iface} ) opts hostname
-	eval opts=\"\$\{udhcpc_${ifvar}\}\"
+    local ifvar=$( bash_variable ${iface} ) opts hostname
+    eval opts=\"\$\{udhcpc_${ifvar}\}\"
 
-	if [[ ${opts} != *'--hostname='* ]]; then
-		hostname=$( hostname )
-		[[ -n ${hostname} && ${hostname} != "(none)" ]] && opts="${opts} --hostname=${hostname}"
-	fi
+    if [[ ${opts} != *'--hostname='* ]]; then
+	hostname=$( hostname )
+	[[ -n ${hostname} && ${hostname} != "(none)" ]] && opts="${opts} --hostname=${hostname}"
+    fi
 
-	# Bring up DHCP for this interface (or alias)
-	ebegin "Running udhcpc"
+    # Bring up DHCP for this interface (or alias)
+    ebegin "Running udhcpc"
 
-	if ! clean_pidfile ${pidfile} ; then
-		ewarn "udhcpc is already running on ${iface}"
-		eend 0
-		return 0
-	fi
-
-	# Try and load the cache if it exists
-	if [[ -f ${cachefile} && ${opts} != *'--request='* && ${opts} != *'-r '* ]]; then
-		x=$( < ${cachefile} )
-		[[ -n ${x} ]] && opts="${opts} --request=${x}"
-	fi
-
-	if [[ ${background} == "yes" ]]; then
-		eval "udhcpc ${opts} --script=${MODULES_DIR}/helpers.d/udhcpc-wrapper --pidfile=${pidfile} --interface=${iface}" &>/dev/null &
-		eend 0
-		go_background
-	fi
-
-	x=$( eval "udhcpc ${opts} --now --script=${MODULES_DIR}/helpers.d/udhcpc-wrapper --pidfile=${pidfile} --interface=${iface}" )
-	# We just check the last 5 letters
-	[[ ${x:((${#x} - 5)):5} == "bound" ]]
-	eend $? || return 1
-
-	# DHCP succeeded, show address retrieved
-	local addr=$( interface_get_address ${iface} )
-	einfo "${iface} received address ${addr}"
-
+    if ! clean_pidfile ${pidfile} ; then
+	ewarn "udhcpc is already running on ${iface}"
+	eend 0
 	return 0
+    fi
+
+    # Try and load the cache if it exists
+    if [[ -f ${cachefile} && ${opts} != *'--request='* && ${opts} != *'-r '* ]]; then
+	x=$( < ${cachefile} )
+	[[ -n ${x} ]] && opts="${opts} --request=${x}"
+    fi
+
+    if [[ ${background} == "yes" ]]; then
+	eval "udhcpc ${opts} --script=${MODULES_DIR}/helpers.d/udhcpc-wrapper --pidfile=${pidfile} --interface=${iface}" &>/dev/null &
+	eend 0
+	go_background
+    fi
+
+    x=$( eval "udhcpc ${opts} --now --script=${MODULES_DIR}/helpers.d/udhcpc-wrapper --pidfile=${pidfile} --interface=${iface}" )
+    # We just check the last 5 letters
+    [[ ${x:((${#x} - 5)):5} == "bound" ]]
+    eend $? || return 1
+
+    # DHCP succeeded, show address retrieved
+    local addr=$( interface_get_address ${iface} )
+    einfo "${iface} received address ${addr}"
+
+    return 0
 }
diff --git a/net-scripts/net.modules.d/vlan b/net-scripts/net.modules.d/vlan
--- a/net-scripts/net.modules.d/vlan
+++ b/net-scripts/net.modules.d/vlan
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,46 +8,46 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 vconfig() {
-	LC_ALL=C /sbin/vconfig "$@"
+    LC_ALL=C /sbin/vconfig "$@"
 }
 
 # char* vlan_provides(void)
 #
 # Returns a string to change module definition for starting up
 vlan_provides() {
-	echo "vlan"
+    echo "vlan"
 }
 
 # void vlan_depend(void)
 #
 # Sets up the dependancies for the module
 vlan_depend() {
-	after interface
-	before dhcp
+    after interface
+    before dhcp
 }
 
 # bool vlan_check_installed(void)
 #
 # Returns 1 if vconfig is installed, otherwise 0
 vlan_check_installed() {
-	[[ -x /sbin/vconfig ]] && return 0
-	${1:-false} && eerror "For VLAN (802.1q) support, emerge net-misc/vconfig"
-	return 1
+    [[ -x /sbin/vconfig ]] && return 0
+    ${1:-false} && eerror "For VLAN (802.1q) support, emerge net-misc/vconfig"
+    return 1
 }
 
 # bool vlan_check_depends(void)
 #
 # Checks to see if we have the needed functions
 vlan_check_depends() {
-	local f
+    local f
 
-	for f in iface_start iface_stop; do
-		[[ $( type -t ${f} ) == function ]] && continue
-		eerror "vlan: missing required function ${f}\n"
-		return 1
-	done
+    for f in iface_start iface_stop; do
+	[[ $( type -t ${f} ) == function ]] && continue
+	eerror "vlan: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # char* vlan_get_vars(char *interface)
@@ -54,7 +55,7 @@ vlan_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 vlan_get_vars() {
-	echo "vlans_$1 iface_$1_vlans"
+    echo "vlans_$1 iface_$1_vlans"
 }
 
 # char* vlan_get_vlans(char *interface)
@@ -62,7 +63,7 @@ vlan_get_vars() {
 # Fetch the configured vlans for an interface.  Outputs a space
 # separated list on stdout.  For example "eth0.1 eth0.2 eth0.3"
 vlan_get_vlans() {
-	 sed -n -e 's/^\(.*[0-9]\) \(.* \) .*'$1'$/\1/p' /proc/net/vlan/config 2>/dev/null
+    sed -n -e 's/^\(.*[0-9]\) \(.* \) .*'$1'$/\1/p' /proc/net/vlan/config 2>/dev/null
 }
 
 # bool vlan_check_kernel(void)
@@ -70,39 +71,39 @@ vlan_get_vlans() {
 # Checks to see if the 802.1q module is present - if not try and load it
 # Returns 1 if there is a problem
 vlan_check_kernel() {
-	[[ -d /proc/net/vlan ]] && return 0
-	/sbin/modprobe 8021q &>/dev/null
-	[[ -d /proc/net/vlan ]] && return 0
-	eerror "VLAN (802.1q) support is not present in this kernel"
-	return 1
+    [[ -d /proc/net/vlan ]] && return 0
+    /sbin/modprobe 8021q &>/dev/null
+    [[ -d /proc/net/vlan ]] && return 0
+    eerror "VLAN (802.1q) support is not present in this kernel"
+    return 1
 }
 
 #bool vlan_pre_start(char *iface)
 #
 # Setup vconfig
 vlan_pre_start() {
-	local iface=$1 opts i x e ifvar=$( bash_variable $1 )
+    local iface=$1 opts i x e ifvar=$( bash_variable $1 )
 
-	eval opts=( \"\$\{vconfig_${ifvar}\[@\]\}\" )
-	[[ -z ${opts} ]] && return 0
+    eval opts=( \"\$\{vconfig_${ifvar}\[@\]\}\" )
+    [[ -z ${opts} ]] && return 0
 
-	vlan_check_kernel || return 1
+    vlan_check_kernel || return 1
 
-	for (( i=0; i<${#opts[@]}; i++ )); do
-		if [[ ${opts[i]} == 'set_name_type'* ]]; then
-			x=${opts[i]}
-		else
-			x=${opts[i]/ / ${iface} }
-			[[ ${x} == ${opts[i]} ]] && x="${x} ${iface}"
-		fi
-		e=$( vconfig ${x} 2>&1 1>/dev/null )
-		[[ -z ${e} ]] && continue
-		eerror "vconfig ${x}"
-		eerror "${e}"
-		return 1
-	done
+    for (( i=0; i<${#opts[@]}; i++ )); do
+	if [[ ${opts[i]} == 'set_name_type'* ]]; then
+	    x=${opts[i]}
+	else
+	    x=${opts[i]/ / ${iface} }
+	    [[ ${x} == ${opts[i]} ]] && x="${x} ${iface}"
+	fi
+	e=$( vconfig ${x} 2>&1 1>/dev/null )
+	[[ -z ${e} ]] && continue
+	eerror "vconfig ${x}"
+	eerror "${e}"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool vlan_post_start(char *iface)
@@ -111,34 +112,34 @@ vlan_pre_start() {
 #
 # Always returns 0 (true) 
 vlan_post_start() {
-	local iface=$1 vlan vlans vlans_old e ifname ifvar=$( bash_variable $1 )
+    local iface=$1 vlan vlans vlans_old e ifname ifvar=$( bash_variable $1 )
 
-	eval vlans=\"\$\{vlans_${ifvar}\}\"
+    eval vlans=\"\$\{vlans_${ifvar}\}\"
 
-	# BACKWARD COMPATIBILITY: check for old vlan variable name
-	eval vlans_old=\"\$\{iface_${ifvar}_vlans\}\"
-	[[ -n ${vlans_old} && -z ${vlans} ]] && vlans=${vlans_old}
+    # BACKWARD COMPATIBILITY: check for old vlan variable name
+    eval vlans_old=\"\$\{iface_${ifvar}_vlans\}\"
+    [[ -n ${vlans_old} && -z ${vlans} ]] && vlans=${vlans_old}
 
-	[[ -z ${vlans} ]] && return 0
+    [[ -z ${vlans} ]] && return 0
 
-	vlan_check_kernel || return 1
+    vlan_check_kernel || return 1
 
-	# Start vlans for this interface
-	for vlan in ${vlans}; do
-		einfo "Adding VLAN ${vlan} to ${iface}"
-		e=$( vconfig add ${iface} ${vlan} 2>&1 1>/dev/null )
-		if [[ -n ${e} ]] ; then
-			eend 1 ${e}
-			continue
-		fi
-		eend 0
+    # Start vlans for this interface
+    for vlan in ${vlans}; do
+	einfo "Adding VLAN ${vlan} to ${iface}"
+	e=$( vconfig add ${iface} ${vlan} 2>&1 1>/dev/null )
+	if [[ -n ${e} ]] ; then
+	    eend 1 ${e}
+	    continue
+	fi
+	eend 0
 
-		# We need to work out the interface name of our new vlan id
-		ifname=$( sed -n -e 's/^\(.*[0-9] \) *| '${vlan}' *| .*'${iface}'$/\1/p' /proc/net/vlan/config )
-		iface_start ${ifname}
-	done
+	# We need to work out the interface name of our new vlan id
+	ifname=$( sed -n -e 's/^\(.*[0-9] \) *| '${vlan}' *| .*'${iface}'$/\1/p' /proc/net/vlan/config )
+	iface_start ${ifname}
+    done
 
-	return 0
+    return 0
 }
 
 # bool vlan_pre_stop(char *iface)
@@ -147,15 +148,15 @@ vlan_post_start() {
 #
 # Always returns 0 (true) 
 vlan_pre_stop() {
-	local iface=$1 vlan
+    local iface=$1 vlan
 
-	vlan_check_installed || return 0
+    vlan_check_installed || return 0
 
-	for vlan in $( vlan_get_vlans ${iface} ); do
-		einfo "Removing VLAN ${vlan##*.} from ${iface}"
-		iface_stop ${vlan}
-		vconfig rem ${vlan}
-	done
+    for vlan in $( vlan_get_vlans ${iface} ); do
+	einfo "Removing VLAN ${vlan##*.} from ${iface}"
+	iface_stop ${vlan}
+	vconfig rem ${vlan}
+    done
 
-	return 0
+    return 0
 }
diff --git a/net-scripts/net.modules.d/wpa_supplicant b/net-scripts/net.modules.d/wpa_supplicant
--- a/net-scripts/net.modules.d/wpa_supplicant
+++ b/net-scripts/net.modules.d/wpa_supplicant
@@ -1,3 +1,4 @@
+#!/bin/bash
 # Copyright (c) 2004-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Header$
@@ -7,82 +8,82 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 wpa_supplicant() {
-	LC_ALL=C /usr/sbin/wpa_supplicant "$@"
+    LC_ALL=C /usr/sbin/wpa_supplicant "$@"
 }
 
 wpa_cli() {
-	LC_ALL=C /usr/bin/wpa_cli "$@"
+    LC_ALL=C /usr/bin/wpa_cli "$@"
 }
 
 # char* wpa_supplicant_provides(void)
 #
 # Returns a string to change module definition for starting up
 wpa_supplicant_provides() {
-	echo "wireless"
+    echo "wireless"
 }
 
 # void wpa_supplicant_depend(void)
 #
 # Sets up the dependancies for the module
 wpa_supplicant_depend() {
-	after macchanger
-	before interface
+    after macchanger
+    before interface
 }
 
 # bool wpa_supplicant_check_installed(void)
 #
 # Returns 0 if wpa_supplicant is installed, otherwise 1
 wpa_supplicant_check_installed() {
-	local report=${1:-false} installed=0
-	if [[ ! -x /usr/sbin/wpa_supplicant ]]; then
-		installed=1
-		${report} && eerror "For WPA support (wpa_supplicant) support, emerge net-wireless/wpa-supplicant"
-	fi
-	if [[ ! -e /proc/net/packet ]]; then
-		installed=1
-		${report} && eerror "wpa_supplicant requires Packet Socket (CONFIG_PACKET=y) enabled in the kernel"
-	fi
-	return ${installed}
+    local report=${1:-false} installed=0
+    if [[ ! -x /usr/sbin/wpa_supplicant ]]; then
+	installed=1
+	${report} && eerror "For WPA support (wpa_supplicant) support, emerge net-wireless/wpa-supplicant"
+    fi
+    if [[ ! -e /proc/net/packet ]]; then
+	installed=1
+	${report} && eerror "wpa_supplicant requires Packet Socket (CONFIG_PACKET=y) enabled in the kernel"
+    fi
+    return ${installed}
 }
 
 # bool wpa_supplicant_check_depends(void)
 #
 # Checks to see if we have the needed functions
 wpa_supplicant_check_depends() {
-	local f
+    local f
 
-	for f in interface_exists; do
-		[[ $( type -t ${f} ) == "function" ]] && continue
-		eerror "wpa_supplicant: missing required function ${f}\n"
-		return 1
-	done
+    for f in interface_exists; do
+	[[ $( type -t ${f} ) == "function" ]] && continue
+	eerror "wpa_supplicant: missing required function ${f}\n"
+	return 1
+    done
 
-	return 0
+    return 0
 }
 
 # bool wpa_supplicant_check_extensions(char *interface)
 #
 # Checks to see if wireless extensions are enabled on the interface
 wpa_supplicant_check_extensions() {
-	grep -q "$1: " /proc/net/wireless
+    grep -q "$1: " /proc/net/wireless
 }
 
 # char* wpa_supplicant_get_essid(char *interface)
 #
 # Gets the current ESSID of iface
 wpa_supplicant_get_essid() {
-	local i essid
+    local i essid
 
-	for (( i=0; i<5; i++ )); do
-		essid=$( wpa_cli -i$1 status | sed -n -e 's/^ssid=//p' )
-		if [[ -n ${essid} ]]; then
-			echo ${essid}
-			return 0
-		fi
-		sleep 1
-	done
+    for (( i=0; i<5; i++ )); do
+	essid=$( wpa_cli -i$1 status | sed -n -e 's/^ssid=//p' )
+	if [[ -n ${essid} ]]; then
+	    echo ${essid}
+	    return 0
+	fi
+	sleep 1
+    done
 
-	return 1
+    return 1
 }
 
 # char* wpa_supplicant_get_ap_mac_address(char *interface)
@@ -90,7 +91,7 @@ wpa_supplicant_get_essid() {
 # Returns the MAC address of the Access Point
 # the interface is connected to
 wpa_supplicant_get_ap_mac_address() {
-	wpa_cli -i$1 status | sed -n -e 's/^bssid=\([^=]\+\).*/\U\1/p'
+    wpa_cli -i$1 status | sed -n -e 's/^bssid=\([^=]\+\).*/\U\1/p'
 }
 
 # bool wpa_supplicant_associated(char *interface)
@@ -100,54 +101,54 @@ wpa_supplicant_get_ap_mac_address() {
 # correct encryption keys
 # We only need this for wpa_supplicant-0.3.x
 wpa_supplicant_associated() {
-	local -a status=( "$( wpa_cli -i$1 status | sed -n -e 's/^\(key_mgmt\|wpa_state\|EAP state\)=\([^=]\+\).*/\U\2/p' )" )
+    local -a status=( "$( wpa_cli -i$1 status | sed -n -e 's/^\(key_mgmt\|wpa_state\|EAP state\)=\([^=]\+\).*/\U\2/p' )" )
 
-	case ${status[0]} in
-		"NONE")			[[ ${status[1]} == "ASSOCIATED" ]] ;;
-		"IEEE 802.1X (no WPA)")	[[ ${status[2]} == "SUCCESS" ]] ;;
-		*)			[[ ${status[1]} == "COMPLETED" ]] ;;
-	esac
+    case ${status[0]} in
+	"NONE")			[[ ${status[1]} == "ASSOCIATED" ]] ;;
+	"IEEE 802.1X (no WPA)")	[[ ${status[2]} == "SUCCESS" ]] ;;
+	*)			[[ ${status[1]} == "COMPLETED" ]] ;;
+    esac
 
-	return $?
+    return $?
 }
 
 # void wpa_supplicant_kill(char *interface, bool report)
 #
 # Kills any existing wpa_supplicant process on the interface
 wpa_supplicant_kill() {
-	local iface=$1 report=${2:-false} pidfile
+    local iface=$1 report=${2:-false} pidfile
 
-	# Shutdown wpa_cli first, if it's running
-	# This is important as future versions of wpa_supplicant
-	# may send a disconnect message to wpa_cli when it shutsdown
-	pidfile="/var/run/wpa_cli-${iface}.pid"
-	if ! clean_pidfile ${pidfile} ; then
-		${report} && ebegin "Stopping wpa_cli on ${iface}"
-		start-stop-daemon --stop --exec /usr/bin/wpa_cli \
-			--pidfile ${pidfile} 
-		${report} && eend $?
-	fi
+    # Shutdown wpa_cli first, if it's running
+    # This is important as future versions of wpa_supplicant
+    # may send a disconnect message to wpa_cli when it shutsdown
+    pidfile="/var/run/wpa_cli-${iface}.pid"
+    if ! clean_pidfile ${pidfile} ; then
+	${report} && ebegin "Stopping wpa_cli on ${iface}"
+	start-stop-daemon --stop --exec /usr/bin/wpa_cli \
+	    --pidfile ${pidfile} 
+	${report} && eend $?
+    fi
 
-	# Now shutdown wpa_supplicant
-	pidfile="/var/run/wpa_supplicant-${iface}.pid"
-	if ! clean_pidfile ${pidfile} ; then
-		${report} && ebegin "Stopping wpa_supplicant on ${iface}"
-		start-stop-daemon --stop --exec /usr/sbin/wpa_supplicant \
-			--pidfile ${pidfile}
-		${report} && eend $?
-	else
-		# Support wpa_supplicant-0.3.x
-		local pid=$( pgrep -f "^/usr/sbin/wpa_supplicant .* -i${iface}[ ]*$" )
-		if [[ -n ${pid} ]]; then
-			${report} && ebegin "Stopping wpa_supplicant on ${iface}"
-			kill -s TERM ${pid}
-			${report} && eend 0
-		fi
+    # Now shutdown wpa_supplicant
+    pidfile="/var/run/wpa_supplicant-${iface}.pid"
+    if ! clean_pidfile ${pidfile} ; then
+	${report} && ebegin "Stopping wpa_supplicant on ${iface}"
+	start-stop-daemon --stop --exec /usr/sbin/wpa_supplicant \
+	    --pidfile ${pidfile}
+	${report} && eend $?
+    else
+	# Support wpa_supplicant-0.3.x
+	local pid=$( pgrep -f "^/usr/sbin/wpa_supplicant .* -i${iface}[ ]*$" )
+	if [[ -n ${pid} ]]; then
+	    ${report} && ebegin "Stopping wpa_supplicant on ${iface}"
+	    kill -s TERM ${pid}
+	    ${report} && eend 0
 	fi
-	
-	# If wpa_supplicant exits uncleanly, we need to remove the stale dir
-	[[ -S /var/run/wpa_supplicant/${iface} ]] \
-		&& rm -f /var/run/wpa_supplicant/${iface}
+    fi
+
+    # If wpa_supplicant exits uncleanly, we need to remove the stale dir
+    [[ -S /var/run/wpa_supplicant/${iface} ]] \
+    && rm -f /var/run/wpa_supplicant/${iface}
 }
 
 # bool wpa_supplicant_associate(char *interface)
@@ -155,27 +156,27 @@ wpa_supplicant_kill() {
 # Returns 0 if wpa_supplicant associates and authenticates to an AP
 # otherwise, 1
 wpa_supplicant_associate() {
-	local iface=$1 ifvar=$( bash_variable $1 ) timeout i
+    local iface=$1 ifvar=$( bash_variable $1 ) timeout i
 
-	eval timeout=\"\$\{wpa_timeout_${ifvar}:-60\}\"
-	for (( i=0; i<${timeout}; i++ )); do
-		if ! wpa_cli -i${iface} status &>/dev/null ; then
-			eend 1 "wpa_supplicant has exited unexpectedly"
-			return 1
-		fi
-		wpa_supplicant_associated ${iface} && break
-		sleep 1
-	done
-	if [[ ${i} == ${timeout} ]]; then
-		if ! wpa_supplicant_associated ${iface}; then
-			[[ ${background} != yes ]] && eend 1 "timed out"
-
-			# We now need to kill the process
-			wpa_supplicant_kill ${iface}
-
-			return 1
-		fi
+    eval timeout=\"\$\{wpa_timeout_${ifvar}:-60\}\"
+    for (( i=0; i<${timeout}; i++ )); do
+	if ! wpa_cli -i${iface} status &>/dev/null ; then
+	    eend 1 "wpa_supplicant has exited unexpectedly"
+	    return 1
 	fi
+	wpa_supplicant_associated ${iface} && break
+	sleep 1
+    done
+    if [[ ${i} == ${timeout} ]]; then
+	if ! wpa_supplicant_associated ${iface}; then
+	    [[ ${background} != yes ]] && eend 1 "timed out"
+
+	    # We now need to kill the process
+	    wpa_supplicant_kill ${iface}
+
+	    return 1
+	fi
+    fi
 }
 
 # bool wpa_supplicant_pre_start(char *interface)
@@ -183,119 +184,119 @@ wpa_supplicant_associate() {
 # Start wpa_supplicant on an interface and wait for association
 # Returns 0 (true) when successful, non-zero otherwise
 wpa_supplicant_pre_start() {
-	local iface=$1 opts timeout action
-	local cfgfile="/etc/wpa_supplicant.conf"
-	local actfile="/usr/sbin/wpa_cli.action"
+    local iface=$1 opts timeout action
+    local cfgfile="/etc/wpa_supplicant.conf"
+    local actfile="/usr/sbin/wpa_cli.action"
 
-	# We don't configure wireless if we're being called from
-	# the background
-	if ${IN_BACKGROUND} ; then
-	        ESSID=$( wpa_supplicant_get_essid $1 )
-		ESSIDVAR=$( bash_variable "${ESSID}" )
-		save_options "ESSID" "${ESSID}"
-		return 0
-	fi
-
-	save_options "ESSID" ""
-	
-	# We only work on wirelesss interfaces
-	wpa_supplicant_check_extensions ${iface} || return 0
-
-	# Kill off any existing wpa_supplicant on this interface
-	# This is so we can re-read the configuration file and clean any stale
-	# directories
-	wpa_supplicant_kill ${iface} true
-
-	# If wireless-tools is installed, try and apply our user config
-	# This is needed for some drivers - such as hostap because they start
-	# the card in Master mode which causes problems with wpa_supplicant.
-	if [[ $( type -t iwconfig_defaults ) == "function" ]]; then
-		iwconfig_defaults ${iface}
-		iwconfig_user_config ${iface}
-	fi	
-
-	ebegin "Starting wpa_supplicant on ${iface}"
-
-	if [[ ! -f ${cfgfile} ]]; then
-		eend 1 "configuration file ${cfgfile} not found!"
-		return 1
-	fi
-
-	local ctrl_dir=$( sed -n -e 's/[ \t]*#.*//g;s/[ \t]*$//g;s/^ctrl_interface=//p' ${cfgfile} )
-	if [[ ${ctrl_dir} != "/var/run/wpa_supplicant" ]]; then
-		eerror "${cfgfile} must set"
-		eerror "  ctrl_interface=/var/run/wpa_supplicant"
-		eend 1
-		return 1
-	fi
-
-	local ifvar=$( bash_variable ${iface} )
-	eval opts=\" \$\{wpa_supplicant_${ifvar}\}\"
-	[[ ${opts} != *' -D'* ]] && ewarn "wpa_supplicant_${ifvar} does not define a driver"
-	
-	# Some drivers require the interface to be up
-	interface_up ${iface}
-
-	version=$( wpa_cli -v | sed -n -e 's/wpa_cli v//p' )
-	version=( ${version//./ } )
-	(( version = version[0] * 1000 + version[1] * 100 + version[2] ))
-	# wpa_supplicant 0.4.0 and greater supports wpa_cli actions
-	if [[ ${version} -gt 399 && -x ${actfile} ]]; then
-		opts="${opts} -W -P/var/run/wpa_supplicant-${iface}.pid"
-		action=true
-	fi
-
-	start-stop-daemon --start --exec /usr/sbin/wpa_supplicant \
-		-- ${opts} -B -c/etc/wpa_supplicant.conf -i${iface}
-	eend $? || return 1
-
-# Starting wpa_supplication-0.4.0, we can get wpa_cli to
-	# start/stop our scripts from wpa_supplicant messages
-	if [[ ${action} ]]; then
-		ebegin "Starting wpa_cli on ${iface}"
-		start-stop-daemon --start --exec /usr/bin/wpa_cli \
-			-- -a${actfile} -i${iface} \
-			-P/var/run/wpa_cli-${iface}.pid -B
-		eend $? || return 1
-		go_background
-	fi
-
-	# Background wpa_supplication if required
-	if [[ ${background} == "yes" ]]; then
-		wpa_supplicant_associate ${iface} \
-			&& export IN_BACKGROUND=true \
-			&& /etc/init.d/net.${iface} start >/dev/null &
-		go_background
-	fi
-
-	eindent
-	veinfo "Waiting for association"
-	eend 0
-
-	wpa_supplicant_associate ${iface} || return 1
-
-	# Set ESSID for essidnet and report
-	ESSID=$( wpa_supplicant_get_essid ${iface} )
+    # We don't configure wireless if we're being called from
+    # the background
+    if ${IN_BACKGROUND} ; then
+	ESSID=$( wpa_supplicant_get_essid $1 )
 	ESSIDVAR=$( bash_variable "${ESSID}" )
 	save_options "ESSID" "${ESSID}"
-	
-	local -a status=( "$( wpa_cli -i${iface} status | sed -n -e 's/^\(bssid\|pairwise_cipher\|key_mgmt\)=\([^=]\+\).*/\U\2/p' | tr '[:lower:]' '[:upper:]' )" )
-	einfo "${iface} connected to \"${ESSID//\\\\/\\\\}\" at ${status[0]}"
-
-	if [[ ${status[2]} == "NONE" ]]; then
-		if [[ ${status[1]} == "NONE" ]]; then
-			ewarn "not using any encryption"
-		else
-			veinfo "using ${status[1]}"
-		fi
-	else
-		veinfo "using ${status[2]}/${status[1]}"
-	fi
-	eoutdent
-
-	[[ -x /usr/sbin/wpa_monitor ]] && /usr/sbin/wpa_monitor -i${iface}
-
 	return 0
+    fi
+
+    save_options "ESSID" ""
+
+    # We only work on wirelesss interfaces
+    wpa_supplicant_check_extensions ${iface} || return 0
+
+    # Kill off any existing wpa_supplicant on this interface
+    # This is so we can re-read the configuration file and clean any stale
+    # directories
+    wpa_supplicant_kill ${iface} true
+
+    # If wireless-tools is installed, try and apply our user config
+    # This is needed for some drivers - such as hostap because they start
+    # the card in Master mode which causes problems with wpa_supplicant.
+    if [[ $( type -t iwconfig_defaults ) == "function" ]]; then
+	iwconfig_defaults ${iface}
+	iwconfig_user_config ${iface}
+    fi	
+
+    ebegin "Starting wpa_supplicant on ${iface}"
+
+    if [[ ! -f ${cfgfile} ]]; then
+	eend 1 "configuration file ${cfgfile} not found!"
+	return 1
+    fi
+
+    local ctrl_dir=$( sed -n -e 's/[ \t]*#.*//g;s/[ \t]*$//g;s/^ctrl_interface=//p' ${cfgfile} )
+    if [[ ${ctrl_dir} != "/var/run/wpa_supplicant" ]]; then
+	eerror "${cfgfile} must set"
+	eerror "  ctrl_interface=/var/run/wpa_supplicant"
+	eend 1
+	return 1
+    fi
+
+    local ifvar=$( bash_variable ${iface} )
+    eval opts=\" \$\{wpa_supplicant_${ifvar}\}\"
+    [[ ${opts} != *' -D'* ]] && ewarn "wpa_supplicant_${ifvar} does not define a driver"
+
+    # Some drivers require the interface to be up
+    interface_up ${iface}
+
+    version=$( wpa_cli -v | sed -n -e 's/wpa_cli v//p' )
+    version=( ${version//./ } )
+    (( version = version[0] * 1000 + version[1] * 100 + version[2] ))
+    # wpa_supplicant 0.4.0 and greater supports wpa_cli actions
+    if [[ ${version} -gt 399 && -x ${actfile} ]]; then
+	opts="${opts} -W -P/var/run/wpa_supplicant-${iface}.pid"
+	action=true
+    fi
+
+    start-stop-daemon --start --exec /usr/sbin/wpa_supplicant \
+        -- ${opts} -B -c/etc/wpa_supplicant.conf -i${iface}
+    eend $? || return 1
+
+    # Starting wpa_supplication-0.4.0, we can get wpa_cli to
+    # start/stop our scripts from wpa_supplicant messages
+    if [[ ${action} ]]; then
+	ebegin "Starting wpa_cli on ${iface}"
+	start-stop-daemon --start --exec /usr/bin/wpa_cli \
+	    -- -a${actfile} -i${iface} \
+	    -P/var/run/wpa_cli-${iface}.pid -B
+	eend $? || return 1
+	go_background
+    fi
+
+    # Background wpa_supplication if required
+    if [[ ${background} == "yes" ]]; then
+	wpa_supplicant_associate ${iface} \
+	   && export IN_BACKGROUND=true \
+	   && /etc/init.d/net.${iface} start >/dev/null &
+	go_background
+    fi
+
+    eindent
+    veinfo "Waiting for association"
+    eend 0
+
+    wpa_supplicant_associate ${iface} || return 1
+
+    # Set ESSID for essidnet and report
+    ESSID=$( wpa_supplicant_get_essid ${iface} )
+    ESSIDVAR=$( bash_variable "${ESSID}" )
+    save_options "ESSID" "${ESSID}"
+
+    local -a status=( "$( wpa_cli -i${iface} status | sed -n -e 's/^\(bssid\|pairwise_cipher\|key_mgmt\)=\([^=]\+\).*/\U\2/p' | tr '[:lower:]' '[:upper:]' )" )
+    einfo "${iface} connected to \"${ESSID//\\\\/\\\\}\" at ${status[0]}"
+
+    if [[ ${status[2]} == "NONE" ]]; then
+	if [[ ${status[1]} == "NONE" ]]; then
+	    ewarn "not using any encryption"
+	else
+	    veinfo "using ${status[1]}"
+	fi
+    else
+	veinfo "using ${status[2]}/${status[1]}"
+    fi
+    eoutdent
+
+    [[ -x /usr/sbin/wpa_monitor ]] && /usr/sbin/wpa_monitor -i${iface}
+
+    return 0
 }
 
 # bool wpa_supplicant_pre_stop(char *iface)
@@ -304,8 +305,8 @@ wpa_supplicant_pre_start() {
 # We don't query for the current ESSID as it may have changed to another
 # one
 wpa_supplicant_pre_stop() {
-        ESSID=$( get_options "ESSID" )
-	ESSIDVAR=$( bash_variable "${ESSID}" )
+    ESSID=$( get_options "ESSID" )
+    ESSIDVAR=$( bash_variable "${ESSID}" )
 }	
 
 # bool wpa_supplicant_post_stop(char *iface)
@@ -313,6 +314,6 @@ wpa_supplicant_pre_stop() {
 # Stops wpa_supplicant on an interface
 # Returns 0 (true) when successful, non-zero otherwise
 wpa_supplicant_post_stop() {
-	! ${IN_BACKGROUND} && wpa_supplicant_kill $1 true
-	return 0
+    ! ${IN_BACKGROUND} && wpa_supplicant_kill $1 true
+    return 0
 }
