Merge updates from HEAD
svn path=/branches/rc-scripts-1_6/; revision=757

diff --git a/net-scripts/net.modules.d/dhclient b/net-scripts/net.modules.d/dhclient
--- a/net-scripts/net.modules.d/dhclient
+++ b/net-scripts/net.modules.d/dhclient
@@ -1,5 +1,5 @@
 # DHCP (net-misc/dhcp) module for net-scripts
-# Version 1.0.5
+# Version 1.0.6
 # Copyright (c) 2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License V2
 # Contributed by Roy Marples (uberlord@gentoo.org)
@@ -22,7 +22,6 @@ dhclient_provides() {
 # Sets up the dependancies for the module
 dhclient_depend() {
 	after interface
-	need interface
 }
 
 # bool dhclient_check_installed(void)
@@ -62,7 +61,7 @@ dhclient_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 dhclient_get_vars() {
-	echo "dhclient_${1} peer_dns_${1} peer_nis_${1} peer_ntp_${1}"
+	echo "dhclient_${1} dhcp_${1}"
 }
 
 # bool dhclient_stop(char *iface)
@@ -127,10 +126,16 @@ dhclient_start() {
 	fi
 
 	eval opts=\"\$\{dhclient_${ifvar}\}\"
-	local x=$( dhclient ${opts} -sf ${script} -pf ${pidfile} -q ${iface} )
+	local x=$( dhclient ${opts} -1 -sf ${script} -pf ${pidfile} -q ${iface} )
 	# We just check the last 5 letters
 	[[ ${x:${#x} - 5:5} == bound ]]
-	eend $? || return 1
+	if [[ $? != 0 ]]; then
+		# We need to kill the process if we fail
+		kill -s TERM $( cat ${pidfile} ) 2>/dev/null
+		eend 1
+		return 1
+	fi
+	eend 0
 
 	# DHCP succeeded, show address retrieved
 	local addr=$( interface_get_address ${iface} )
