Added # vim:ts=4 to all net-script files and re-indented
/dep{cache,tree} are now chmodded 0644 so users can read them

svn path=/trunk/; revision=1382

diff --git a/net-scripts/net.modules.d/dhclient b/net-scripts/net.modules.d/dhclient
--- a/net-scripts/net.modules.d/dhclient
+++ b/net-scripts/net.modules.d/dhclient
@@ -7,45 +7,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 dhclient() {
-    LC_ALL=C /sbin/dhclient "$@"
+	LC_ALL=C /sbin/dhclient "$@"
 }
 
 # char* dhclient_provides(void)
 #
 # Returns a string to change module definition for starting up
 dhclient_provides() {
-    echo "dhcp"
+	echo "dhcp"
 }
 
 # void dhclient_depend(void)
 #
 # Sets up the dependancies for the module
 dhclient_depend() {
-    after interface
+	after interface
 }
 
 # bool dhclient_check_installed(void)
 #
 # Returns 1 if dhclient is installed, otherwise 0
 dhclient_check_installed() {
-    [[ -x /sbin/dhclient ]] && return 0
-    ${1:-false} && eerror "For DHCP (dhclient) support, emerge net-misc/dhcp"
-    return 1
+	[[ -x /sbin/dhclient ]] && return 0
+	${1:-false} && eerror "For DHCP (dhclient) support, emerge net-misc/dhcp"
+	return 1
 }
 
 # bool dhclient_check_depends(void)
 #
 # Checks to see if we have the needed functions
 dhclient_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_get_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "dhclient: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_get_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "dhclient: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # char* dhclient_get_vars(char *interface)
@@ -53,7 +53,7 @@ dhclient_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 dhclient_get_vars() {
-    echo "dhclient_$1 dhcp_$1"
+	echo "dhclient_$1 dhcp_$1"
 }
 
 # bool dhclient_stop(char *iface)
@@ -61,36 +61,36 @@ dhclient_get_vars() {
 # Stop dhclient on an interface
 # Always returns 0
 dhclient_stop() {
-    local iface="$1" d
-    local pidfile="/var/run/dhclient-${iface}.pid"
+	local iface="$1" d
+	local pidfile="/var/run/dhclient-${iface}.pid"
 
-    dhclient_check_installed || return 0
-    [[ ! -f ${pidfile} ]] && return 0
+	dhclient_check_installed || return 0
+	[[ ! -f ${pidfile} ]] && return 0
 
-    # We check for a dhclient process first as if we attempt to release
-    # an interface for which dhclient has obtained an IP in the past
-    # it causes a "RELEASE" event anyway.
-    local pid=$( < "${pidfile}" )
+	# We check for a dhclient process first as if we attempt to release
+	# an interface for which dhclient has obtained an IP in the past
+	# it causes a "RELEASE" event anyway.
+	local pid=$( < "${pidfile}" )
 
-    local ifvar=$( bash_variable "${iface}" )
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
+	local ifvar=$( bash_variable "${iface}" )
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
 
-    ebegin "Stopping dhclient on ${iface}"
-    if [[ ${d} == *" release "* ]]; then
-	local r=$( dhclient -q -r -pf "${pidfile}" \
-	    -sf "${MODULES_DIR}/helpers.d/dhclient-wrapper" "${iface}" )
-	[[ ${r} == "deconfig" ]]
-	eend $? "dhclient returned a ${r}"
-	[[ -f "/var/cache/dhcp-${iface}.lease" ]] \
-	&& rm -f "/var/cache/dhcp-${iface}.lease"
-    else
-	kill -s TERM "${pid}" 2>/dev/null
-	clean_pidfile "${pidfile}"
-	eend 0
-    fi
+	ebegin "Stopping dhclient on ${iface}"
+	if [[ ${d} == *" release "* ]]; then
+		local r=$( dhclient -q -r -pf "${pidfile}" \
+		-sf "${MODULES_DIR}/helpers.d/dhclient-wrapper" "${iface}" )
+		[[ ${r} == "deconfig" ]]
+		eend $? "dhclient returned a ${r}"
+		[[ -f "/var/cache/dhcp-${iface}.lease" ]] \
+		&& rm -f "/var/cache/dhcp-${iface}.lease"
+	else
+		kill -s TERM "${pid}" 2>/dev/null
+		clean_pidfile "${pidfile}"
+		eend 0
+	fi
 
-    return 0
+	return 0
 }
 
 # bool dhclient_start(char *iface)
@@ -99,96 +99,98 @@ dhclient_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 dhclient_start() {
-    local iface="$1" opts ifvar=$( bash_variable "$1" )
-    local pidfile="/var/run/dhclient-${iface}.pid" edit=""
-    local cffile="/etc/dhcp/dhclient.conf"
-    local d
+	local iface="$1" opts ifvar=$( bash_variable "$1" )
+	local pidfile="/var/run/dhclient-${iface}.pid" edit=""
+	local cffile="/etc/dhcp/dhclient.conf"
+	local d
 
-    interface_exists "${iface}" true || return 1
+	interface_exists "${iface}" true || return 1
 
-    eval edit=\"\$\{dhclient_edit_config_${ifvar}\}\"
-    [[ -z ${edit} ]] && eval edit="${dhclient_edit_config:-no}"
-    if [[ ${edit} == "yes" || ${edit} == "true" ]]; then
-	edit=true
-    else
-	edit=false
-    fi
-
-    # Load our options
-    eval opts=\" \$\{dhclient_${ifvar}\} \"
-
-    # Work out our cffile
-    x="${opts##* -cf }"
-    if [[ ${x} != "${opts}" ]]; then
-	x="${x%% *}"
-	if [[ -n ${x} ]]; then
-	    cffile="${x}"
-	    opts="${opts//-cf ${cffile}/}"
+	eval edit=\"\$\{dhclient_edit_config_${ifvar}\}\"
+	[[ -z ${edit} ]] && eval edit="${dhclient_edit_config:-no}"
+	if [[ ${edit} == "yes" || ${edit} == "true" ]]; then
+		edit=true
+	else
+		edit=false
 	fi
-    fi
-    opts="${opts} -cf ${cffile}"
-    
-    # Ensure that the cffile does not contain any script lines
-    # as that will stop our helpers from running
-    if [[ -e ${cffile} ]] ; then
-	if grep -q "^[ \t]*script " "${cffile}" 2>/dev/null ; then
-	    if ${edit} ; then
-		sed -i '/^[ \t]*script /d' "${cffile}" || return 1
-	    else
-		eerror "You have to remove the script parameter from ${cffile}"
-		return 1
-	    fi
+
+	# Load our options
+	eval opts=\" \$\{dhclient_${ifvar}\} \"
+
+	# Work out our cffile
+	x="${opts##* -cf }"
+	if [[ ${x} != "${opts}" ]]; then
+		x="${x%% *}"
+		if [[ -n ${x} ]]; then
+			cffile="${x}"
+			opts="${opts//-cf ${cffile}/}"
+		fi
 	fi
-    else
-	${edit} && touch "${cffile}" 2>/dev/null
-    fi
+	opts="${opts} -cf ${cffile}"
 
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
-
-    # Send our hostname by editing cffile
-    if ${edit} && [[ -e ${cffile} && ${d} != *" nosendhost "* ]] ; then
-	local hostname=$( hostname )
-	if [[ ${hostname} != "(none)" && ${hostname} != "localhost" ]]; then
-	    sed -i '/^[ \t]*send[ \t]*host-name[ \t]*/d' "${cffile}"
-	    if [[ -s ${cffile} ]]; then
-		sed -i '1 isend host-name "'"${hostname}"'";' "${cffile}"
-	    else
-		echo "send host-name \"${hostname}\";" > "${cffile}"
-	    fi
+	# Ensure that the cffile does not contain any script lines
+	# as that will stop our helpers from running
+	if [[ -e ${cffile} ]] ; then
+		if grep -q "^[ \t]*script " "${cffile}" 2>/dev/null ; then
+			if ${edit} ; then
+				sed -i '/^[ \t]*script /d' "${cffile}" || return 1
+			else
+				eerror "You have to remove the script parameter from ${cffile}"
+				return 1
+			fi
+		fi
+	else
+		${edit} && touch "${cffile}" 2>/dev/null
 	fi
-    fi
 
-    # Bring up DHCP for this interface (or alias)
-    ebegin "Running dhclient"
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
 
-    # Stop dhclient if it's already running
-    dhclient_stop "${iface}"
-    
-    if [[ ${background} == "yes" ]]; then
-	eval dhclient ${opts} -pf "${pidfile}" -q \
-	    -sf "${MODULES_DIR}/helpers.d/dhclient-wrapper" \
-	    "${iface}" &>/dev/null &
-	eend 0
-	go_background
-    fi
+	# Send our hostname by editing cffile
+	if ${edit} && [[ -e ${cffile} && ${d} != *" nosendhost "* ]] ; then
+		local hostname=$( hostname )
+		if [[ ${hostname} != "(none)" && ${hostname} != "localhost" ]]; then
+			sed -i '/^[ \t]*send[ \t]*host-name[ \t]*/d' "${cffile}"
+			if [[ -s ${cffile} ]]; then
+				sed -i '1 isend host-name "'"${hostname}"'";' "${cffile}"
+			else
+				echo "send host-name \"${hostname}\";" > "${cffile}"
+			fi
+		fi
+	fi
 
-    local x=$( eval dhclient ${opts} -1 -pf "${pidfile}" \
+	# Bring up DHCP for this interface (or alias)
+	ebegin "Running dhclient"
+
+	# Stop dhclient if it's already running
+	dhclient_stop "${iface}"
+
+	if [[ ${background} == "yes" ]]; then
+		eval dhclient ${opts} -pf "${pidfile}" -q \
+		-sf "${MODULES_DIR}/helpers.d/dhclient-wrapper" \
+		"${iface}" &>/dev/null &
+		eend 0
+		go_background
+	fi
+
+	local x=$( eval dhclient ${opts} -1 -pf "${pidfile}" \
 	-sf "${MODULES_DIR}/helpers.d/dhclient-wrapper" -q "${iface}" 2>&1 )
-    # We just check the last 5 letters
-    [[ ${x:${#x} - 5:5} == "bound" ]]
-    if [[ $? != "0" ]]; then
-	echo "${x}"
-	# We need to kill the process if we fail
-	[[ -e ${pidfile} ]] && kill -s TERM $( < "${pidfile}" ) 2>/dev/null
-	eend 1
-	return 1
-    fi
-    eend 0
+	# We just check the last 5 letters
+	[[ ${x:${#x} - 5:5} == "bound" ]]
+	if [[ $? != "0" ]]; then
+		echo "${x}"
+		# We need to kill the process if we fail
+		[[ -e ${pidfile} ]] && kill -s TERM $( < "${pidfile}" ) 2>/dev/null
+		eend 1
+		return 1
+	fi
+	eend 0
 
-    # DHCP succeeded, show address retrieved
-    local addr=$( interface_get_address "${iface}" )
-    einfo "${iface} received address ${addr}"
+	# DHCP succeeded, show address retrieved
+	local addr=$( interface_get_address "${iface}" )
+	einfo "${iface} received address ${addr}"
 
-    return 0
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/dhcpcd b/net-scripts/net.modules.d/dhcpcd
--- a/net-scripts/net.modules.d/dhcpcd
+++ b/net-scripts/net.modules.d/dhcpcd
@@ -7,53 +7,53 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 dhcpcd() {
-    LC_ALL=C /sbin/dhcpcd "$@"
+	LC_ALL=C /sbin/dhcpcd "$@"
 }
 
 # char* dhcpcd_provides(void)
 #
 # Returns a string to change module definition for starting up
 dhcpcd_provides() {
-    echo "dhcp"
+	echo "dhcp"
 }
 
 # void dhcpcd_depend(void)
 #
 # Sets up the dependancies for the module
 dhcpcd_depend() {
-    after interface
+	after interface
 }
 
 # bool dhcpcd_check_installed(void)
 #
 # Returns 1 if dhcpcd is installed, otherwise 0
 dhcpcd_check_installed() {
-    if [[ -x /sbin/dhcpcd ]]; then
-        if dhcpcd -h 2>&1 | grep -q "etcDir" ; then
-	    return 0
-	else
-	    ${1:-false} && eerror "We require dhcpcd-1.3.22_p4-r10"
-	    return 1
+	if [[ -x /sbin/dhcpcd ]]; then
+		if dhcpcd -h 2>&1 | grep -q "etcDir" ; then
+			return 0
+		else
+			${1:-false} && eerror "We require dhcpcd-1.3.22_p4-r10"
+			return 1
+		fi
 	fi
-    fi
-	
-    ${1:-false} && eerror "For DHCP (dhcpcd) support, emerge net-misc/dhcpcd"
-    return 1
+
+	${1:-false} && eerror "For DHCP (dhcpcd) support, emerge net-misc/dhcpcd"
+	return 1
 }
 
 # bool dhcpcd_check_depends(void)
 #
 # Checks to see if we have the needed functions
 dhcpcd_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_get_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "dhcpcd: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_get_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "dhcpcd: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # char* dhcpcd_get_vars(char *interface)
@@ -61,7 +61,7 @@ dhcpcd_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 dhcpcd_get_vars() {
-    echo "dhcpcd_$1 dhcp_$1"
+	echo "dhcpcd_$1 dhcp_$1"
 }
 
 # bool dhcpcd_stop(char *iface)
@@ -71,29 +71,29 @@ dhcpcd_get_vars() {
 # Returns 0 (true) when a DHCP address dropped
 # otherwise return 1
 dhcpcd_stop() {
-    local iface=$1 count signal pidfile="/var/run/dhcpcd-$1.pid" d
+	local iface=$1 count signal pidfile="/var/run/dhcpcd-$1.pid" d
 
-    dhcpcd_check_installed || return 0
+	dhcpcd_check_installed || return 0
 
-    [[ ! -f ${pidfile} ]] && return 0
+	[[ ! -f ${pidfile} ]] && return 0
 
-    ebegin "Stopping dhcpcd on ${iface}"
-    local pid=$( < "${pidfile}" )
+	ebegin "Stopping dhcpcd on ${iface}"
+	local pid=$( < "${pidfile}" )
 
-    local ifvar=$( bash_variable "${iface}" )
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
-    
-    if [[ ${d} == *" release "* ]]; then
-	signal="HUP"
-    else
-	signal="TERM"
-    fi
+	local ifvar=$( bash_variable "${iface}" )
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
 
-    kill -s "${signal}" "${pid}" &>/dev/null 
-    process_finished "${pid}" dhcpcd
-    eend $? "timed out"
-    return $?
+	if [[ ${d} == *" release "* ]]; then
+		signal="HUP"
+	else
+		signal="TERM"
+	fi
+
+	kill -s "${signal}" "${pid}" &>/dev/null 
+	process_finished "${pid}" dhcpcd
+	eend $? "timed out"
+	return $?
 }
 
 # bool dhcpcd_start(char *iface)
@@ -102,63 +102,65 @@ dhcpcd_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 dhcpcd_start() {
-    local iface="$1" opts hostname pidfile="/var/run/dhcpcd-$1.pid"
-    local ifvar=$( bash_variable "${iface}" ) metric d
+	local iface="$1" opts hostname pidfile="/var/run/dhcpcd-$1.pid"
+	local ifvar=$( bash_variable "${iface}" ) metric d
 
-    interface_exists "${iface}" true || return 1
+	interface_exists "${iface}" true || return 1
 
-    # Get our options
-    eval opts=\" \$\{dhcpcd_${ifvar}\} \"
+	# Get our options
+	eval opts=\" \$\{dhcpcd_${ifvar}\} \"
 
-    # Map some generic options to dhcpcd
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
-    [[ ${d} == *" nodns "* ]] && opts="${opts} -R"
-    [[ ${d} == *" nontp "* ]] && opts="${opts} -N"
-    [[ ${d} == *" nonis "* ]] && opts="${opts} -Y"
-    [[ ${d} == *" nogateway "* ]] && opts="${opts} -G"
+	# Map some generic options to dhcpcd
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
+	[[ ${d} == *" nodns "* ]] && opts="${opts} -R"
+	[[ ${d} == *" nontp "* ]] && opts="${opts} -N"
+	[[ ${d} == *" nonis "* ]] && opts="${opts} -Y"
+	[[ ${d} == *" nogateway "* ]] && opts="${opts} -G"
 
-    # We transmit the hostname by default
-    if [[ ${d} != *" nosendhost "* && ${opts} != *" -h "* ]]; then
-	hostname=$( hostname )
-	[[ -n ${hostname} && ${hostname} != "(none)" \
-	&& ${hostname} != "localhost" ]] \
-	&& opts="-h \"${hostname}\" ${opts}"
-    fi
+	# We transmit the hostname by default
+	if [[ ${d} != *" nosendhost "* && ${opts} != *" -h "* ]]; then
+		hostname=$( hostname )
+		[[ -n ${hostname} && ${hostname} != "(none)" \
+		&& ${hostname} != "localhost" ]] \
+		&& opts="-h \"${hostname}\" ${opts}"
+	fi
 
-    # Stop dhcpcd from bringing the interface down when we exit
-    opts="${opts} -o"
+	# Stop dhcpcd from bringing the interface down when we exit
+	opts="${opts} -o"
 
-    # Add our route metric
-    eval metric=\"\$\{metric_${ifvar}\}\"
-    [[ -n ${metric} ]] && opts="${opts} -m ${metric}"
+	# Add our route metric
+	eval metric=\"\$\{metric_${ifvar}\}\"
+	[[ -n ${metric} ]] && opts="${opts} -m ${metric}"
 
-    # Instruct dhcpcd to use our wrapper 
-    opts="${opts} -c \"/lib/rcscripts/net.modules.d/helpers.d/dhcpcd-wrapper\""
-    
-    # Instruct dhcpcd to create it's files in our state dir
-    opts="${opts} -e \"${statedir}/${iface}\""
+	# Instruct dhcpcd to use our wrapper 
+	opts="${opts} -c \"/lib/rcscripts/net.modules.d/helpers.d/dhcpcd-wrapper\""
 
-    # Bring up DHCP for this interface (or alias)
-    ebegin "Running dhcpcd"
+	# Instruct dhcpcd to create it's files in our state dir
+	opts="${opts} -e \"${statedir}/${iface}\""
 
-    # Halt any existing dhcpcd process
-    dhcpcd_stop "${iface}"
+	# Bring up DHCP for this interface (or alias)
+	ebegin "Running dhcpcd"
 
-    [[ ! -d "${statedir}/${iface}" ]] && mkdir -m 0755 -p "${statedir}/${iface}"
-    
-    if [[ ${background} == "yes" ]]; then
-	eval dhcpcd ${opts} ${iface} &
-	eend 0
-	go_background
-    fi
+	# Halt any existing dhcpcd process
+	dhcpcd_stop "${iface}"
 
-    eval dhcpcd ${opts} ${iface}
-    eend $? || return 1
+	[[ ! -d "${statedir}/${iface}" ]] && mkdir -m 0755 -p "${statedir}/${iface}"
 
-    # DHCP succeeded, show address retrieved
-    local addr=$( interface_get_address "${iface}" )
-    einfo "${iface} received address ${addr}"
+	if [[ ${background} == "yes" ]]; then
+		eval dhcpcd ${opts} ${iface} &
+		eend 0
+		go_background
+	fi
 
-    return 0
+	eval dhcpcd ${opts} ${iface}
+	eend $? || return 1
+
+	# DHCP succeeded, show address retrieved
+	local addr=$( interface_get_address "${iface}" )
+	einfo "${iface} received address ${addr}"
+
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/ifconfig b/net-scripts/net.modules.d/ifconfig
--- a/net-scripts/net.modules.d/ifconfig
+++ b/net-scripts/net.modules.d/ifconfig
@@ -7,38 +7,38 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 ifconfig() {
-    LC_ALL=C /sbin/ifconfig "$@"
+	LC_ALL=C /sbin/ifconfig "$@"
 }
 
 ifconfig_tunnel() {
-    LC_ALL=C /sbin/iptunnel "$@"
+	LC_ALL=C /sbin/iptunnel "$@"
 }
 
 route() {
-    LC_ALL=C /sbin/route "$@"
+	LC_ALL=C /sbin/route "$@"
 }
 
 # void ifconfig_depend(void)
 #
 # Sets up the dependancies for the module
 ifconfig_depend() {
-    after macnet wireless
+	after macnet wireless
 }
 
 # bool ifconfig_check_installed(void)
 #
 # Returns 1 if ifconfig is installed, otherwise 0
 ifconfig_check_installed() {
-    [[ -x /sbin/ifconfig ]] && return 0
-    ${1:-false} && eerror "For ifconfig support, emerge sys-apps/net-tools"
-    return 1
+	[[ -x /sbin/ifconfig ]] && return 0
+	${1:-false} && eerror "For ifconfig support, emerge sys-apps/net-tools"
+	return 1
 }
 
 # char* ifconfig_provides(void)
 #
 # Returns a string to change module definition for starting up
 ifconfig_provides() {
-    echo "interface"
+	echo "interface"
 }
 
 # char* ifconfig_module(void)
@@ -47,38 +47,38 @@ ifconfig_provides() {
 # This is needed by dhclient as we run different scripts
 # based on the interface
 ifconfig_module() {
-    echo "ifconfig"
+	echo "ifconfig"
 }
 
 # bool ifconfig_check_depends(void)
 #
 # Checks to see if we have the needed functions
 ifconfig_check_depends() {
-    return 0
+	return 0
 }
 
 # bool ifconfig_exists(char *interface, bool report)
 #
 # Returns 1 if the interface exists, otherwise 0
 ifconfig_exists() {
-    local e=$( ifconfig -a | grep -o "^$1" ) report="${2:-false}"
-    [[ -n ${e} ]] && return 0
-    ${report} && eerror "$1 does not exist"
-    return 1
+	local e=$( ifconfig -a | grep -o "^$1" ) report="${2:-false}"
+	[[ -n ${e} ]] && return 0
+	${report} && eerror "$1 does not exist"
+	return 1
 }
 
 # void ifconfig_up(char *iface)
 #
 # provides a generic interface for bringing interfaces up
 ifconfig_up() {
-    ifconfig "$1" up
+	ifconfig "$1" up
 }
 
 # void ifconfig_down(char *iface)
 #
 # provides a generic interface for bringing interfaces down
 ifconfig_down() {
-    ifconfig "$1" down
+	ifconfig "$1" down
 }
 
 # bool ifconfig_is_up(char *iface, bool withaddress)
@@ -87,19 +87,19 @@ ifconfig_down() {
 # If withaddress is true then the interface has to have an IPv4 address
 # assigned as well
 ifconfig_is_up() {
-    local check="\<UP\>" addr="${2:-false}"
-    ${addr} && check="\<inet addr:.*${check}"
-    ifconfig "$1" | grep -Eq "${check}" && return 0
-    return 1
+	local check="\<UP\>" addr="${2:-false}"
+	${addr} && check="\<inet addr:.*${check}"
+	ifconfig "$1" | grep -Eq "${check}" && return 0
+	return 1
 }
 
 # void ifconfig_set_flag(char *iface, char *flag, bool enabled)
 #
 # Sets or disables the interface flag 
 ifconfig_set_flag() {
-    local iface="$1" flag="$2" enable="$3"
-    ${enable} || flag="-${flag}"
-    ifconfig "${iface}" "${flag}"
+	local iface="$1" flag="$2" enable="$3"
+	${enable} || flag="-${flag}"
+	ifconfig "${iface}" "${flag}"
 }
 
 # void ifconfig_get_address(char *interface)
@@ -107,24 +107,24 @@ ifconfig_set_flag() {
 # Fetch the address retrieved by DHCP.  If successful, echoes the
 # address on stdout, otherwise echoes nothing.
 ifconfig_get_address() {
-    local -a x=( $( ifconfig "$1" \
+	local -a x=( $( ifconfig "$1" \
 	| sed -n -e 's/.*inet addr:\([^ ]*\).*Mask:\([^ ]*\).*/\1 \2/p' ) )
-    x[1]=$( netmask2cidr "${x[1]}" )
-    echo "${x[0]}/${x[1]}"
+	x[1]=$( netmask2cidr "${x[1]}" )
+	echo "${x[0]}/${x[1]}"
 }
 
 # void ifconfig_get_mac_address(char *interface)
 #
 # Fetch the mac address assingned to the network card
 ifconfig_get_mac_address() {
-    ifconfig "$1" | sed -n -e 's/.*HWaddr .*\<\(..:..:..:..:..:..\)\>.*/\U\1/p'
+	ifconfig "$1" | sed -n -e 's/.*HWaddr .*\<\(..:..:..:..:..:..\)\>.*/\U\1/p'
 }
 
 # void ifconfig_set_mac_address(char *interface, char *mac)
 #
 # Assigned the mac address to the network card
 ifconfig_set_mac_address() {
-    ifconfig "$1" hw ether "$2"
+	ifconfig "$1" hw ether "$2"
 }
 
 # int ifconfig_set_name(char *interface, char *new_name)
@@ -132,16 +132,16 @@ ifconfig_set_mac_address() {
 # Renames the interface
 # This will not work if the interface is setup!
 ifconfig_set_name() {
-    [[ -z $2 ]] && return 1
-    local current="$1" new="$2"
-    
-    local mac=$( ifconfig_get_mac_address "${current}" )
-    if [[ -z ${mac} ]]; then
-	eerror "${iface} does not have a MAC address"
-	return 1
-    fi
-    
-    /sbin/nameif "${new}" "${mac}"
+	[[ -z $2 ]] && return 1
+	local current="$1" new="$2"
+
+	local mac=$( ifconfig_get_mac_address "${current}" )
+	if [[ -z ${mac} ]]; then
+		eerror "${iface} does not have a MAC address"
+		return 1
+	fi
+
+	/sbin/nameif "${new}" "${mac}"
 }
 
 # void ifconfig_get_aliases_rev(char *interface)
@@ -150,7 +150,7 @@ ifconfig_set_name() {
 # Outputs a space-separated list on stdout, in reverse order, for
 # example "eth0:2 eth0:1"
 ifconfig_get_aliases_rev() {
-    ifconfig | grep -o "^$1:[0-9]* " | tac
+	ifconfig | grep -o "^$1:[0-9]* " | tac
 }
 
 # bool ifconfig_del_addresses(char *interface, bool onlyinet)
@@ -160,29 +160,29 @@ ifconfig_get_aliases_rev() {
 # (false) if there were no addresses to remove.
 # If onlyinet is true then we only delete IPv4 / inet addresses
 ifconfig_del_addresses() {
-    local iface="$1" i onlyinet="${2:-false}"
-    # We don't remove addresses from aliases
-    [[ ${iface} == *:* ]] && return 0
+	local iface="$1" i onlyinet="${2:-false}"
+	# We don't remove addresses from aliases
+	[[ ${iface} == *:* ]] && return 0
 
-    # If the interface doesn't exist, don't try and delete
-    ifconfig_exists "${iface}" || return 0
+	# If the interface doesn't exist, don't try and delete
+	ifconfig_exists "${iface}" || return 0
 
-    # iproute2 can add many addresses to an iface unlike ifconfig ...
-    # iproute2 added addresses cause problems for ifconfig
-    # as we delete an address, a new one appears, so we have to
-    # keep polling
-    while ifconfig "${iface}" | grep -q -m1 -o 'inet addr:[^ ]*' ; do
-	ifconfig "${iface}" 0.0.0.0 || break
-    done
-
-    # Remove IPv6 addresses
-    if ! ${onlyinet} ; then
-	for i in $( ifconfig "${iface}" \
-	    | sed -n -e 's/^.*inet6 addr: \([^ ]*\) Scope:[^L].*/\1/p' ) ; do
-	    /sbin/ifconfig "${iface}" inet6 del "${i}"
+	# iproute2 can add many addresses to an iface unlike ifconfig ...
+	# iproute2 added addresses cause problems for ifconfig
+	# as we delete an address, a new one appears, so we have to
+	# keep polling
+	while ifconfig "${iface}" | grep -q -m1 -o 'inet addr:[^ ]*' ; do
+		ifconfig "${iface}" 0.0.0.0 || break
 	done
-    fi
-    return 0
+
+	# Remove IPv6 addresses
+	if ! ${onlyinet} ; then
+		for i in $( ifconfig "${iface}" \
+			| sed -n -e 's/^.*inet6 addr: \([^ ]*\) Scope:[^L].*/\1/p' ) ; do
+			/sbin/ifconfig "${iface}" inet6 del "${i}"
+		done
+	fi
+	return 0
 }
 
 # char* ifconfig_get_vars(char *interface)
@@ -190,49 +190,49 @@ ifconfig_del_addresses() {
 # Returns a string spaced with possible user set
 # configuration variables
 ifconfig_get_vars() {
-    echo "config_$1 routes_$1 fallback_$1 metric_$1 ifconfig_$1 \
-    ifconfig_fallback_$1 routes_$1 inet6_$1 iface_$1 alias_$1 \
-    broadcast_$1 netmask_$1"
-    # The depreciated gateway var has to be handled by
-    # each module if needed
+	echo "config_$1 routes_$1 fallback_$1 metric_$1 ifconfig_$1 \
+	ifconfig_fallback_$1 routes_$1 inet6_$1 iface_$1 alias_$1 \
+	broadcast_$1 netmask_$1"
+	# The depreciated gateway var has to be handled by
+	# each module if needed
 }
 
 # bool ifconfig_get_old_config(char *iface)
 #
 # Returns config and config_fallback for the given interface
 ifconfig_get_old_config() {
-    local iface="$1" ifvar=$( bash_variable "$1" ) i inet6
+	local iface="$1" ifvar=$( bash_variable "$1" ) i inet6
 
-    eval config=( \"\$\{ifconfig_${ifvar}\[@\]\}\" )
-    eval config_fallback=( \"\$\{ifconfig_fallback_${ifvar}\[@\]\}\" )
-    eval inet6=( \"\$\{inet6_${ifvar}\[@\]\}\" )
+	eval config=( \"\$\{ifconfig_${ifvar}\[@\]\}\" )
+	eval config_fallback=( \"\$\{ifconfig_fallback_${ifvar}\[@\]\}\" )
+	eval inet6=( \"\$\{inet6_${ifvar}\[@\]\}\" )
 
-    # BACKWARD COMPATIBILITY: populate the config_IFACE array
-    # if iface_IFACE is set (fex. iface_eth0 instead of ifconfig_eth0)
-    eval i=\"\$\{iface_${ifvar}\}\"
-    if [[ -n ${i} && -z ${config} ]]; then
-	# Make sure these get evaluated as arrays
-	local -a aliases broadcasts netmasks
+	# BACKWARD COMPATIBILITY: populate the config_IFACE array
+	# if iface_IFACE is set (fex. iface_eth0 instead of ifconfig_eth0)
+	eval i=\"\$\{iface_${ifvar}\}\"
+	if [[ -n ${i} && -z ${config} ]]; then
+		# Make sure these get evaluated as arrays
+		local -a aliases broadcasts netmasks
 
-	# Start with the primary interface
-	config=( "${i}" )
+		# Start with the primary interface
+		config=( "${i}" )
 
-	# ..then add aliases
-	eval aliases=( \$\{alias_${ifvar}\} )
-	eval broadcasts=( \$\{broadcast_${ifvar}\} )
-	eval netmasks=( \$\{netmask_${ifvar}\} )
-	for (( i=0; i<${#aliases[@]}; i++ )); do
-	    config[i+1]="${aliases[i]} ${broadcasts[i]:+broadcast ${broadcasts[i]}} ${netmasks[i]:+netmask ${netmasks[i]}}"
-	done
-    fi
+		# ..then add aliases
+		eval aliases=( \$\{alias_${ifvar}\} )
+		eval broadcasts=( \$\{broadcast_${ifvar}\} )
+		eval netmasks=( \$\{netmask_${ifvar}\} )
+		for (( i=0; i<${#aliases[@]}; i++ )); do
+			config[i+1]="${aliases[i]} ${broadcasts[i]:+broadcast ${broadcasts[i]}} ${netmasks[i]:+netmask ${netmasks[i]}}"
+		done
+	fi
 
-    # BACKWARD COMPATIBILITY: check for space-separated inet6 addresses
-    [[ ${#inet6[@]} == 1 && ${inet6} == *' '* ]] &&  inet6=( ${inet6} )
+	# BACKWARD COMPATIBILITY: check for space-separated inet6 addresses
+	[[ ${#inet6[@]} == 1 && ${inet6} == *' '* ]] &&  inet6=( ${inet6} )
 
-    # Add inet6 addresses to our config if required
-    [[ -n ${inet6} ]] && config=( "${config[@]}" "${inet6[@]}" )
+	# Add inet6 addresses to our config if required
+	[[ -n ${inet6} ]] && config=( "${config[@]}" "${inet6[@]}" )
 
-    return 0
+	return 0
 }
 
 # bool ifconfig_iface_stop(char *interface)
@@ -241,19 +241,19 @@ ifconfig_get_old_config() {
 #
 # Returns 0 (true) when successful, non-zero (false) on failure
 ifconfig_iface_stop() {
-    # If an alias is already down, then "ifconfig eth0:1 down"
-    # will try to bring it up with an address of "down" which
-    # fails.  Do some double-checking before returning error
-    # status
-    ifconfig_is_up "$1" || return 0
-    ifconfig_down "$1" && return 0
+	# If an alias is already down, then "ifconfig eth0:1 down"
+	# will try to bring it up with an address of "down" which
+	# fails.  Do some double-checking before returning error
+	# status
+	ifconfig_is_up "$1" || return 0
+	ifconfig_down "$1" && return 0
 
-    # It is sometimes impossible to transition an alias from the
-    # UP state... particularly if the alias has no address.  So
-    # ignore the failure, which should be okay since the entire
-    # interface will be shut down eventually.
-    [[ $1 == *:* ]] && return 0
-    return 1
+	# It is sometimes impossible to transition an alias from the
+	# UP state... particularly if the alias has no address.  So
+	# ignore the failure, which should be okay since the entire
+	# interface will be shut down eventually.
+	[[ $1 == *:* ]] && return 0
+	return 1
 }
 
 # bool ifconfig_post_start(char *iface)
@@ -265,151 +265,153 @@ ifconfig_iface_stop() {
 # fail, the routine should still return success to indicate that
 # net.eth0 was successful
 ifconfig_post_start() {
-    local iface="$1" ifvar=$( bash_variable "$1" ) routes x metric mtu
-    eval metric=\"\$\{metric_${ifvar}\}\"
+	local iface="$1" ifvar=$( bash_variable "$1" ) routes x metric mtu
+	eval metric=\"\$\{metric_${ifvar}\}\"
 
-    # Make sure interface is marked UP
-    ifconfig_up "${iface}"
+	# Make sure interface is marked UP
+	ifconfig_up "${iface}"
 
-    # MTU support
-    eval mtu=\"\$\{mtu_${ifvar}\}\"
-    [[ -n ${mtu} ]] && ifconfig "${iface}" mtu "${mtu}"
+	# MTU support
+	eval mtu=\"\$\{mtu_${ifvar}\}\"
+	[[ -n ${mtu} ]] && ifconfig "${iface}" mtu "${mtu}"
 
-    eval routes=( \"\$\{routes_${ifvar}\[@\]\}\" )
+	eval routes=( \"\$\{routes_${ifvar}\[@\]\}\" )
 
-    # BACKWARD COMPATIBILITY: set the default gateway
-    if [[ ${gateway} == "${iface}/"* ]]; then
-	# We don't add the old gateway if one has been set in routes_IFACE
-	local gw=true
+	# BACKWARD COMPATIBILITY: set the default gateway
+	if [[ ${gateway} == "${iface}/"* ]]; then
+		# We don't add the old gateway if one has been set in routes_IFACE
+		local gw=true
+		for x in "${routes[@]}"; do
+			[[ ${x} != *"default gw"* ]] && continue
+			gw=false
+			break
+		done
+		${gw} && routes=( "${routes[@]}" "default gw ${gateway#*/}" )
+	fi
+
+	[[ -z ${routes} ]] && return 0
+
+	# Add routes for this interface, might even include default gw
+	einfo "Adding routes"
+	eindent
 	for x in "${routes[@]}"; do
-	    [[ ${x} != *"default gw"* ]] && continue
-	    gw=false
-	    break
+		ebegin "${x}"
+
+		# Support iproute2 style routes
+		x="${x//via/gw} "
+		x="${x//scope * / }"
+
+		# Assume we're a net device unless told otherwise
+		[[ " ${x} " != *" -net "* && " ${x} " != *" -host "* ]] && x="-net ${x}"
+
+		# Support adding IPv6 addresses easily
+		[[ ${x} == *:* && ${x} != *"-A inet6"* ]] && x="-A inet6 ${x}"
+
+		# Add a metric if we don't have one
+		[[ ${x} != *" metric "* ]] && x="${x} metric ${metric}"
+
+		route add ${x} dev "${iface}"
+		eend $?
 	done
-	${gw} && routes=( "${routes[@]}" "default gw ${gateway#*/}" )
-    fi
+	eoutdent
 
-    [[ -z ${routes} ]] && return 0
-
-    # Add routes for this interface, might even include default gw
-    einfo "Adding routes"
-    eindent
-    for x in "${routes[@]}"; do
-	ebegin "${x}"
-
-	# Support iproute2 style routes
-	x="${x//via/gw} "
-	x="${x//scope * / }"
-
-	# Assume we're a net device unless told otherwise
-	[[ " ${x} " != *" -net "* && " ${x} " != *" -host "* ]] && x="-net ${x}"
-
-	# Support adding IPv6 addresses easily
-	[[ ${x} == *:* && ${x} != *"-A inet6"* ]] && x="-A inet6 ${x}"
-
-	# Add a metric if we don't have one
-	[[ ${x} != *" metric "* ]] && x="${x} metric ${metric}"
-
-	route add ${x} dev "${iface}"
-	eend $?
-    done
-    eoutdent
-
-    return 0
+	return 0
 }
 
 # bool ifconfig_add_address(char *iface, char *options ...)
 #
 # Adds the given address to the interface
 ifconfig_add_address() {
-    local iface="$1" i=0 r e
+	local iface="$1" i=0 r e
 
-    ifconfig_exists "${iface}" true || return 1
+	ifconfig_exists "${iface}" true || return 1
 
-    # Extract the config
-    local -a config=( "$@" )
-    config=( ${config[@]:1} )
+	# Extract the config
+	local -a config=( "$@" )
+	config=( ${config[@]:1} )
 
-    if [[ ${config[0]} == *:* ]]; then
-	# Support IPv6 - nice and simple
-	config[0]="inet6 add ${config[0]}"
-    else
-	# IPv4 is tricky - ifconfig requires an aliased device
-	# for multiple addresses
-	if ifconfig "${iface}" | grep -Eq "\<inet addr:.*" ; then
-	    # Get the last alias made for the interface and add 1 to it
-	    i=$( ifconfig | tac | grep -m 1 -o "^${iface}:[0-9]*" \
-		| sed -n -e 's/'"${iface}"'://p' )
-	    i="${i:-0}"
-	    (( i++ ))
-	    iface="${iface}:${i}"
+	if [[ ${config[0]} == *:* ]]; then
+		# Support IPv6 - nice and simple
+		config[0]="inet6 add ${config[0]}"
+	else
+		# IPv4 is tricky - ifconfig requires an aliased device
+		# for multiple addresses
+		if ifconfig "${iface}" | grep -Eq "\<inet addr:.*" ; then
+			# Get the last alias made for the interface and add 1 to it
+			i=$( ifconfig | tac | grep -m 1 -o "^${iface}:[0-9]*" \
+			| sed -n -e 's/'"${iface}"'://p' )
+			i="${i:-0}"
+			(( i++ ))
+			iface="${iface}:${i}"
+		fi
+
+		# ifconfig doesn't like CIDR addresses
+		local ip="${config[0]%%/*}" cidr="${config[0]##*/}" netmask
+		if [[ -n ${cidr} && ${cidr} != "${ip}" ]]; then
+			netmask=$( cidr2netmask "${cidr}" )
+			config[0]="${ip} netmask ${netmask}"
+		fi	
+
+		# Support iproute2 style config where possible
+		r="${config[@]}"
+		config=( ${r//brd +/} )
+		config=( "${config[@]//brd/broadcast}" )
+		config=( "${config[@]//peer/pointtopoint}" )
 	fi
 
-	# ifconfig doesn't like CIDR addresses
-	local ip="${config[0]%%/*}" cidr="${config[0]##*/}" netmask
-	if [[ -n ${cidr} && ${cidr} != "${ip}" ]]; then
-	    netmask=$( cidr2netmask "${cidr}" )
-	    config[0]="${ip} netmask ${netmask}"
-	fi	
+	# Some kernels like to apply lo with an address when they are brought up
+	if [[ ${iface} == "lo" \
+		|| ${config[@]} == "127.0.0.1/8 broadcast 127.255.255.255" ]]; then
+		ifconfig "${iface}" ${config[@]} 2>/dev/null
+		r="0"
+	else
+		e=$( ifconfig "${iface}" ${config[@]} 2>&1 )
+		r="$?"
+		[[ ${r} != "0" ]] && echo "${e}" > /dev/stderr
+	fi
 
-	# Support iproute2 style config where possible
-	r="${config[@]}"
-	config=( ${r//brd +/} )
-	config=( "${config[@]//brd/broadcast}" )
-	config=( "${config[@]//peer/pointtopoint}" )
-    fi
+	[[ ${r} != "0" || ${config[0]} == "inet6"* || ${iface} == *:* ]] \
+	&& return ${r}
 
-    # Some kernels like to apply lo with an address when they are brought up
-    if [[ ${iface} == "lo" \
-	|| ${config[@]} == "127.0.0.1/8 broadcast 127.255.255.255" ]]; then
-	ifconfig "${iface}" ${config[@]} 2>/dev/null
-	r="0"
-    else
-	e=$( ifconfig "${iface}" ${config[@]} 2>&1 )
-	r="$?"
-	[[ ${r} != "0" ]] && echo "${e}" > /dev/stderr
-    fi
+	local metric ifvar=$( bash_variable "${iface}" )
+	# Remove the newly added route and replace with our metric
+	eval metric=\"\$\{metric_${ifvar}\}\"
+	[[ ${metric} == "0" || ${RC_AUTO_INTERFACE} != "yes" ]] && return ${r}
 
-    [[ ${r} != "0" || ${config[0]} == "inet6"* || ${iface} == *:* ]] \
-    && return ${r}
+	if [[ -z ${netmask} ]]; then
+		for (( i=1; i<${#config[@]}-1; i++ )); do
+			if [[ ${config[i]} == "netmask" ]]; then
+				netmask="${config[i+1]}"
+				cidr=$( netmask2cidr "${netmask}" )
+				break
+			fi
+		done
+		[[ -z ${netmask} ]] && return ${r}
+	fi
 
-    local metric ifvar=$( bash_variable "${iface}" )
-    # Remove the newly added route and replace with our metric
-    eval metric=\"\$\{metric_${ifvar}\}\"
-    [[ ${metric} == "0" || ${RC_AUTO_INTERFACE} != "yes" ]] && return ${r}
+	local network=$( ip_network "${ip}" "${netmask}" )
 
-    if [[ -z ${netmask} ]]; then
-	for (( i=1; i<${#config[@]}-1; i++ )); do
-	    if [[ ${config[i]} == "netmask" ]]; then
-		netmask="${config[i+1]}"
-		cidr=$( netmask2cidr "${netmask}" )
-		break
-	    fi
-	done
-	[[ -z ${netmask} ]] && return ${r}
-    fi
+	if route del -net "${network}/${cidr}" metric 0 dev "${iface}" \
+		2>/dev/null ; then
+		route add -net "${network}/${cidr}" metric "${metric}" dev "${iface}"
+	fi
 
-    local network=$( ip_network "${ip}" "${netmask}" )
-
-    if route del -net "${network}/${cidr}" metric 0 dev "${iface}" \
-	2>/dev/null ; then
-	route add -net "${network}/${cidr}" metric "${metric}" dev "${iface}"
-    fi
-
-    return ${r}
+	return ${r}
 }
 
 # void ifconfig_default_route(char* interface, char* gateway_ip, int metric)
 #
 # Force default route to the specified gateway
 ifconfig_default_route() {
-    local metric="${3:-0}"
+	local metric="${3:-0}"
 
-    # Delete any existing default routes
-    while true ; do
-	route del default metric "${metric}" dev "$1" 2>/dev/null || break
-    done
+	# Delete any existing default routes
+	while true ; do
+		route del default metric "${metric}" dev "$1" 2>/dev/null || break
+	done
 
-    # Then we add our route
-    route add default gw "$2" metric "${metric}" dev "$1"
+	# Then we add our route
+	route add default gw "$2" metric "${metric}" dev "$1"
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/ipppd b/net-scripts/net.modules.d/ipppd
--- a/net-scripts/net.modules.d/ipppd
+++ b/net-scripts/net.modules.d/ipppd
@@ -8,39 +8,39 @@
 #
 # Returns a string to change module definition for starting up
 ipppd_provides() {
-    echo "isdn"
+	echo "isdn"
 }
 
 # void ipppd_depend(void)
 #
 # Sets up the dependancies for the module
 ipppd_depend() {
-    after macnet
-    before interface
+	after macnet
+	before interface
 }
 
 # bool ipppd_check_installed(void)
 #
 # Returns 1 if isnd4k-utils is installed, otherwise 0
 ipppd_check_installed() {
-    [[ -x /usr/sbin/ipppd ]] && return 0
-    ${1:-false} && eerror "For ISDN (ipppd) support, emerge net-dialup/isdn4k-utils"
-    return 1
+	[[ -x /usr/sbin/ipppd ]] && return 0
+	${1:-false} && eerror "For ISDN (ipppd) support, emerge net-dialup/isdn4k-utils"
+	return 1
 }
 
 # bool ipppd_check_depends(void)
 #
 # Checks to see if we have the needed functions
 ipppd_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_type clean_pidfile; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "ipppd: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_type clean_pidfile; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "ipppd: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # bool ipppd_start(char *iface)
@@ -49,31 +49,31 @@ ipppd_check_depends() {
 #
 # Returns 0 (true) when successful, non-zero otherwise
 ipppd_pre_start() {
-    local iface="$1" opts itype=$( interface_type "$1" )
-    local pidfile="/var/run/ipppd-${iface}.pid"
+	local iface="$1" opts itype=$( interface_type "$1" )
+	local pidfile="/var/run/ipppd-${iface}.pid"
 
-    # Check that we are a valid isdn interface
-    [[ ${itype} != "ippp" && ${itype} != "isdn" ]] && return 0
+	# Check that we are a valid isdn interface
+	[[ ${itype} != "ippp" && ${itype} != "isdn" ]] && return 0
 
-    # Check that the interface exists
-    interface_exists "${iface}" true || return 1
+	# Check that the interface exists
+	interface_exists "${iface}" true || return 1
 
-    if ! clean_pidfile "${pidfile}" ; then
-	ewarn "ipppd is already running on ${iface}"
-	eend 0
-	return 0
-    fi
+	if ! clean_pidfile "${pidfile}" ; then
+		ewarn "ipppd is already running on ${iface}"
+		eend 0
+		return 0
+	fi
 
-    local ifvar=$( bash_variable "${iface}" )
-    # Might or might not be set in conf.d/net
-    eval opts=\"\$\{ipppd_${ifvar}\}\"
+	local ifvar=$( bash_variable "${iface}" )
+	# Might or might not be set in conf.d/net
+	eval opts=\"\$\{ipppd_${ifvar}\}\"
 
-    einfo "Starting ipppd for ${iface}"
-    /usr/sbin/ipppd "${opts}" pidfile "${pidfile}" \
+	einfo "Starting ipppd for ${iface}"
+	/usr/sbin/ipppd "${opts}" pidfile "${pidfile}" \
 	file "/etc/ppp/options.${iface}" >/dev/null
-    eend $? || return $?
+	eend $? || return $?
 
-    return 0
+	return 0
 }
 
 # bool ipppd_stop(char *iface)
@@ -81,21 +81,23 @@ ipppd_pre_start() {
 # Stop isdn on an interface
 # Returns 0 (true) when successful, non-zero otherwise
 ipppd_stop() {
-    local iface="$1" pidfile="/var/run/ipppd-$1.pid"
+	local iface="$1" pidfile="/var/run/ipppd-$1.pid"
 
-    ipppd_check_installed || return 0
-    [[ ! -f ${pidfile} ]] && return 0
+	ipppd_check_installed || return 0
+	[[ ! -f ${pidfile} ]] && return 0
 
-    clean_pidfile "${pidfile}" && return 0
-    local pid=$( < "${pidfile}" ) r=0
+	clean_pidfile "${pidfile}" && return 0
+	local pid=$( < "${pidfile}" ) r=0
 
-    einfo "Stopping ipppd for ${iface}"
-    kill -s TERM "${pid}"
-    if ! process_finished "${pid}" ipppd 10 ; then
-	kill -s KILL "${pid}"
-	process_finished "${pid}" ipppd 10 || r=1
-    fi
+	einfo "Stopping ipppd for ${iface}"
+	kill -s TERM "${pid}"
+	if ! process_finished "${pid}" ipppd 10 ; then
+		kill -s KILL "${pid}"
+		process_finished "${pid}" ipppd 10 || r=1
+	fi
 
-    eend ${r}
-    return ${r}
+	eend ${r}
+	return ${r}
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/macnet b/net-scripts/net.modules.d/macnet
--- a/net-scripts/net.modules.d/macnet
+++ b/net-scripts/net.modules.d/macnet
@@ -10,37 +10,37 @@
 #
 # Sets up the dependancies for the module
 macnet_depend() {
-    before interface wireless
-    after macchanger 
+	before interface wireless
+	after macchanger 
 }
 
 # bool macnet_check_installed(void)
 #
 # Always returns 0 as we are "installed" by wireless in the depend function
 macnet_check_installed() {
-    return 0
+	return 0
 }
 
 # char* macnet_provides(void)
 #
 # Returns a string to change module definition for starting up
 macnet_provides() {
-    echo "macnet"
+	echo "macnet"
 }
 
 # bool macnet_check_depends(void)
 #
 # Checks to see if we have the needed functions
 macnet_check_depends() {
-    local f
+	local f
 
-    for f in interface_get_mac_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "macnet: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_get_mac_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "macnet: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # bool macnet_start(char *iface)
@@ -50,21 +50,23 @@ macnet_check_depends() {
 # We can override each variable here from a given MAC address of the interface
 # Always returns 0
 macnet_pre_start() {
-    local iface="$1"
+	local iface="$1"
 
-    interface_exists "${iface}" || return 0
+	interface_exists "${iface}" || return 0
 
-    # We need to bring the interface up for some interfaces, otherwise the MAC
-    # address isn't consistent - mainly wireless cards with firmware uploading.
-    interface_up "${iface}"
+	# We need to bring the interface up for some interfaces, otherwise the MAC
+	# address isn't consistent - mainly wireless cards with firmware uploading.
+	interface_up "${iface}"
 
-    local mac=$( interface_get_mac_address "${iface}" )
-    [[ -z ${mac} ]] && return 0
-    
-    vebegin "Configuring ${iface} for MAC address ${mac}" 2>/dev/null
-    mac="${mac//:}"
-    configure_variables "${iface}" "${mac}"
-    veend 0 2>/dev/null
-    
-    return 0
+	local mac=$( interface_get_mac_address "${iface}" )
+	[[ -z ${mac} ]] && return 0
+
+	vebegin "Configuring ${iface} for MAC address ${mac}" 2>/dev/null
+	mac="${mac//:}"
+	configure_variables "${iface}" "${mac}"
+	veend 0 2>/dev/null
+
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/pump b/net-scripts/net.modules.d/pump
--- a/net-scripts/net.modules.d/pump
+++ b/net-scripts/net.modules.d/pump
@@ -7,45 +7,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 pump() {
-    LC_ALL=C /sbin/pump "$@"
+	LC_ALL=C /sbin/pump "$@"
 }
 
 # char* pump_provides(void)
 #
 # Returns a string to change module definition for starting up
 pump_provides() {
-    echo "dhcp"
+	echo "dhcp"
 }
 
 # void pump_depend(void)
 #
 # Sets up the dependancies for the module
 pump_depend() {
-    after interface
+	after interface
 }
 
 # bool pump_check_installed(void)
 #
 # Returns 1 if pump is installed, otherwise 0
 pump_check_installed() {
-    [[ -x /sbin/pump ]] && return 0
-    ${1:-false} && eerror "For DHCP (pump) support, emerge net-misc/pump"
-    return 1
+	[[ -x /sbin/pump ]] && return 0
+	${1:-false} && eerror "For DHCP (pump) support, emerge net-misc/pump"
+	return 1
 }
 
 # bool pump_check_depends(void)
 #
 # Checks to see if we have the needed functions
 pump_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_get_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "pump: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_get_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "pump: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # char* pump_get_vars(char *interface)
@@ -53,7 +53,7 @@ pump_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 pump_get_vars() {
-    echo "pump_$1 dhcp_$1"
+	echo "pump_$1 dhcp_$1"
 }
 
 # bool pump_stop(char *iface)
@@ -62,23 +62,23 @@ pump_get_vars() {
 # Return 0 if pump is not running or we stop it successfully
 # Otherwise 1
 pump_stop() {
-    local iface="$1" count e
+	local iface="$1" count e
 
-    pump_check_installed || return 0
+	pump_check_installed || return 0
 
-    # We check for a pump process first as querying for status
-    # causes pump to spawn a process
-    pidof /sbin/pump &>/dev/null || return 0
+	# We check for a pump process first as querying for status
+	# causes pump to spawn a process
+	pidof /sbin/pump &>/dev/null || return 0
 
-    # Check that pump is running on the interface
-    pump --status --interface "${iface}" 2>/dev/null \
+	# Check that pump is running on the interface
+	pump --status --interface "${iface}" 2>/dev/null \
 	| grep -q "^Device ${iface}" || return 0
 
-    # Pump always releases the lease
-    ebegin "Stopping pump on ${iface}"
-    pump --release --interface "${iface}"
-    eend "$?" "Failed to stop pump"
-    return "$?"
+	# Pump always releases the lease
+	ebegin "Stopping pump on ${iface}"
+	pump --release --interface "${iface}"
+	eend "$?" "Failed to stop pump"
+	return "$?"
 }
 
 # bool pump_start(char *iface)
@@ -88,47 +88,49 @@ pump_stop() {
 # Returns 0 (true) when a dhcp address is obtained, otherwise
 # the return value from pump
 pump_start() {
-    local iface="$1" opts d ifvar=$( bash_variable "$1" ) search
+	local iface="$1" opts d ifvar=$( bash_variable "$1" ) search
 
-    interface_exists "${iface}" true || return 1
+	interface_exists "${iface}" true || return 1
 
-    eval opts=\" \$\{pump_${ifvar}\} \"
+	eval opts=\" \$\{pump_${ifvar}\} \"
 
-    # Map some generic options to pump
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
-    [[ ${d} == *" nodns "* ]] && opts="${opts} --no-dns"
-    [[ ${d} == *" nogateway "* ]] && opts="${opts} --no-gateway"
-    [[ ${d} == *" nontp "* ]] && opts="${opts} --no-ntp"
+	# Map some generic options to pump
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
+	[[ ${d} == *" nodns "* ]] && opts="${opts} --no-dns"
+	[[ ${d} == *" nogateway "* ]] && opts="${opts} --no-gateway"
+	[[ ${d} == *" nontp "* ]] && opts="${opts} --no-ntp"
 
-    eval search=\"\$\{dns_search_path_${ifvar}\}\"
-    [[ -n ${search} ]] && opts="${opts} --search-path='"${search}"'"
+	eval search=\"\$\{dns_search_path_${ifvar}\}\"
+	[[ -n ${search} ]] && opts="${opts} --search-path='"${search}"'"
 
-    # Add our route metric
-    eval metric=\"\$\{metric_${ifvar}\}\"
-    [[ -n ${metric} ]] && opts="${opts} --route-metric ${metric}"
+	# Add our route metric
+	eval metric=\"\$\{metric_${ifvar}\}\"
+	[[ -n ${metric} ]] && opts="${opts} --route-metric ${metric}"
 
-    [[ ! -d "${statedir}/${iface}" ]] && mkdir -m 0755 -p "${statedir}/${iface}"
+	[[ ! -d "${statedir}/${iface}" ]] && mkdir -m 0755 -p "${statedir}/${iface}"
 
-    opts="${opts} --win-client-ident --etc-dir=${statedir}/${iface}"
-    opts="${opts} --script /lib/rcscripts/net.modules.d/helpers.d/pump-wrapper"
-    opts="${opts} --keep-up --interface ${iface}"
-    
-    # Bring up DHCP for this interface (or alias)
-    ebegin "Running pump"
+	opts="${opts} --win-client-ident --etc-dir=${statedir}/${iface}"
+	opts="${opts} --script /lib/rcscripts/net.modules.d/helpers.d/pump-wrapper"
+	opts="${opts} --keep-up --interface ${iface}"
 
-    if [[ ${background} == "yes" ]]; then
-	eval pump ${opts} &
-	eend 0
-	go_background
-    fi
-  
-    eval pump ${opts}
-    eend "$?" || return "$?"
+	# Bring up DHCP for this interface (or alias)
+	ebegin "Running pump"
 
-    # pump succeeded, show address retrieved
-    local addr=$( interface_get_address "${iface}" )
-    einfo "${iface} received address ${addr}"
+	if [[ ${background} == "yes" ]]; then
+		eval pump ${opts} &
+		eend 0
+		go_background
+	fi
 
-    return 0
+	eval pump ${opts}
+	eend "$?" || return "$?"
+
+	# pump succeeded, show address retrieved
+	local addr=$( interface_get_address "${iface}" )
+	einfo "${iface} received address ${addr}"
+
+	return 0
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/rename b/net-scripts/net.modules.d/rename
--- a/net-scripts/net.modules.d/rename
+++ b/net-scripts/net.modules.d/rename
@@ -8,29 +8,29 @@
 #
 # Returns a string to change module definition for starting up
 rename_provides() {
-    echo "rename"
+	echo "rename"
 }
 
 # void rename_depend(void)
 #
 # Sets up the dependancies for the module
 rename_depend() {
-    after macchanger macnet
-    before wireless interface
+	after macchanger macnet
+	before wireless interface
 }
 
 # bool rename_check_installed(void)
 #
 # We are always installed
 rename_check_installed() {
-    return 0 
+	return 0 
 }
 
 # bool rename_check_depends(void)
 #
 # Checks to see if we have the needed functions
 rename_check_depends() {
-    return 0
+	return 0
 }
 
 # char* rename_get_vars(char *interface)
@@ -38,47 +38,49 @@ rename_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 rename_get_vars() {
-    echo "rename_$1"
+	echo "rename_$1"
 }
 
 # bool rename_pre_start(char *iface)
 #
 # Checks to see if we have to rename the interface 
 rename_pre_start() {
-    local iface="$1" newname="" mac ifvar=$( bash_variable "$1" )
+	local iface="$1" newname="" mac ifvar=$( bash_variable "$1" )
 
-    interface_exists "${iface}" || return 0
+	interface_exists "${iface}" || return 0
 
-    eval newname=\"\$\{rename_${ifvar}\}\"
-    [[ -z ${newname} || ${iface} == "${newname}" ]] && return 0
+	eval newname=\"\$\{rename_${ifvar}\}\"
+	[[ -z ${newname} || ${iface} == "${newname}" ]] && return 0
 
-    # We cannot rename vlan interfaces as /proc/net/vlan/config always
-    # returns the old interface name. We don't bail out though as it's
-    # not critical that the interface gets renamed.
-    if [[ -d /proc/net/vlan/config ]] ; then
-	if grep -q "^eth0.2 " /proc/net/vlan/config ; then
-	    eerror "Cannot rename VLAN interfaces"
-	    return 0
+	# We cannot rename vlan interfaces as /proc/net/vlan/config always
+	# returns the old interface name. We don't bail out though as it's
+	# not critical that the interface gets renamed.
+	if [[ -d /proc/net/vlan/config ]] ; then
+		if grep -q "^eth0.2 " /proc/net/vlan/config ; then
+			eerror "Cannot rename VLAN interfaces"
+			return 0
+		fi
 	fi
-    fi
-    
-    ebegin "Renaming \"${iface}\" to \"${newname}\""
 
-    # Ensure that we have an init script
-    [[ ! -e "/etc/init.d/net.${newname}" ]] \
+	ebegin "Renaming \"${iface}\" to \"${newname}\""
+
+	# Ensure that we have an init script
+	[[ ! -e "/etc/init.d/net.${newname}" ]] \
 	&& ( cd /etc/init.d ; ln -s net.lo "net.${newname}" )
 
-    # Ensure that the interface is down and without any addresses or we
-    # will not work
-    interface_del_addresses "${iface}"
-    interface_down "${iface}"
-    interface_set_name "${iface}" "${newname}"
-    eend "$?" "Failed to rename interface" || return 1
+	# Ensure that the interface is down and without any addresses or we
+	# will not work
+	interface_del_addresses "${iface}"
+	interface_down "${iface}"
+	interface_set_name "${iface}" "${newname}"
+	eend "$?" "Failed to rename interface" || return 1
 
-    # Mark us as stopped, start the new interface and bail cleanly
-    mark_service_stopped "net.${iface}"
-    einfo "Stopped configuration of ${iface} due to renaming"
-    service_stopped "net.${newname}" && start_service "net.${newname}"
-    
-    exit 1 
+	# Mark us as stopped, start the new interface and bail cleanly
+	mark_service_stopped "net.${iface}"
+	einfo "Stopped configuration of ${iface} due to renaming"
+	service_stopped "net.${newname}" && start_service "net.${newname}"
+
+	exit 1 
 }
+
+# vim:ts=4
diff --git a/net-scripts/net.modules.d/udhcpc b/net-scripts/net.modules.d/udhcpc
--- a/net-scripts/net.modules.d/udhcpc
+++ b/net-scripts/net.modules.d/udhcpc
@@ -7,45 +7,45 @@
 # Fix any potential localisation problems
 # Note that LC_ALL trumps LC_anything_else according to locale(7)
 udhcpc() {
-    LC_ALL=C /sbin/udhcpc "$@"
+	LC_ALL=C /sbin/udhcpc "$@"
 }
 
 # char* udhcpc_provides(void)
 #
 # Returns a string to change module definition for starting up
 udhcpc_provides() {
-    echo "dhcp"
+	echo "dhcp"
 }
 
 # void udhcpc_depend(void)
 #
 # Sets up the dependancies for the module
 udhcpc_depend() {
-    after interface
+	after interface
 }
 
 # bool udhcpc_check_installed(void)
 #
 # Returns 1 if udhcpc is installed, otherwise 0
 udhcpc_check_installed() {
-    [[ -x /sbin/udhcpc ]] && return 0
-    ${1:-false} && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
-    return 1
+	[[ -x /sbin/udhcpc ]] && return 0
+	${1:-false} && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
+	return 1
 }
 
 # bool udhcpc_check_depends(void)
 #
 # Checks to see if we have the needed functions
 udhcpc_check_depends() {
-    local f
+	local f
 
-    for f in interface_exists interface_get_address; do
-	[[ $( type -t "${f}" ) == "function" ]] && continue
-	eerror "udhcpc: missing required function ${f}\n"
-	return 1
-    done
+	for f in interface_exists interface_get_address; do
+		[[ $( type -t "${f}" ) == "function" ]] && continue
+		eerror "udhcpc: missing required function ${f}\n"
+		return 1
+	done
 
-    return 0
+	return 0
 }
 
 # char* udhcpc_get_vars(char *interface)
@@ -53,7 +53,7 @@ udhcpc_check_depends() {
 # Returns a string spaced with possible user set
 # configuration variables
 udhcpc_get_vars() {
-    echo "udhcpc_$1 dhcp_$1"
+	echo "udhcpc_$1 dhcp_$1"
 }
 
 # bool udhcpc_stop(char *iface)
@@ -61,31 +61,31 @@ udhcpc_get_vars() {
 # Stops udhcpc running on an interface
 # Return 1 if we fail to stop udhcpc (if it's running) otherwise 0
 udhcpc_stop() {
-    local iface="$1" pidfile="/var/run/udhcpc-$1.pid" d
+	local iface="$1" pidfile="/var/run/udhcpc-$1.pid" d
 
-    udhcpc_check_installed || return 0
-    [[ ! -f ${pidfile} ]] && return 0
+	udhcpc_check_installed || return 0
+	[[ ! -f ${pidfile} ]] && return 0
 
-    ebegin "Stopping udhcpc on ${iface}"
-    local pid=$( < "${pidfile}" ) e=true
+	ebegin "Stopping udhcpc on ${iface}"
+	local pid=$( < "${pidfile}" ) e=true
 
-    local ifvar=$( bash_variable "${iface}" )
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
+	local ifvar=$( bash_variable "${iface}" )
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
 
-    if [[ ${d} == *" release "* ]]; then
-	kill -s USR2 "${pid}" &>/dev/null
-	[[ -f "/var/cache/dhcp-${iface}.lease" ]] \
-	&& rm "/var/cache/dhcp-${iface}.lease"
-    fi
+	if [[ ${d} == *" release "* ]]; then
+		kill -s USR2 "${pid}" &>/dev/null
+		[[ -f "/var/cache/dhcp-${iface}.lease" ]] \
+		&& rm "/var/cache/dhcp-${iface}.lease"
+	fi
 
-    kill -s TERM "${pid}" &>/dev/null
+	kill -s TERM "${pid}" &>/dev/null
 
-    [[ -f ${pidfile} ]] && rm -f "${pidfile}"
+	[[ -f ${pidfile} ]] && rm -f "${pidfile}"
 
-    ${e}
-    eend "$?"
-    return "$?"
+	${e}
+	eend "$?"
+	return "$?"
 }
 
 # bool udhcpc_start(char *iface)
@@ -94,58 +94,60 @@ udhcpc_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 udhcpc_start() {
-    local iface="$1" opts pidfile="/var/run/udhcpc-$1.pid"
-    local cachefile="/var/cache/dhcp-$1.lease" d
+	local iface="$1" opts pidfile="/var/run/udhcpc-$1.pid"
+	local cachefile="/var/cache/dhcp-$1.lease" d
 
-    interface_exists "${iface}" true || return 1
+	interface_exists "${iface}" true || return 1
 
-    local ifvar=$( bash_variable "${iface}" ) opts hostname
-    eval opts=\"\$\{udhcpc_${ifvar}\}\"
+	local ifvar=$( bash_variable "${iface}" ) opts hostname
+	eval opts=\"\$\{udhcpc_${ifvar}\}\"
 
-    eval d=\" \$\{dhcp_${ifvar}\} \"
-    [[ ${d} == "  " ]] && d=" ${dhcp} "
-    
-    if [[ ${d} != *" nosendhost "* ]]; then
-	if [[ ! " ${opts}" =~ " -([hH] |-hostname=)" ]]; then
-	    local hostname=$( hostname )
-	    [[ -n ${hostname} && ${hostname} != "(none)" \
-	    && ${hostname} != "localhost" ]] \
-	    && opts="${opts} --hostname=${hostname}"
+	eval d=\" \$\{dhcp_${ifvar}\} \"
+	[[ ${d} == "  " ]] && d=" ${dhcp} "
+
+	if [[ ${d} != *" nosendhost "* ]]; then
+		if [[ ! " ${opts}" =~ " -([hH] |-hostname=)" ]]; then
+			local hostname=$( hostname )
+			[[ -n ${hostname} && ${hostname} != "(none)" \
+			&& ${hostname} != "localhost" ]] \
+			&& opts="${opts} --hostname=${hostname}"
+		fi
 	fi
-    fi
 
-    # Bring up DHCP for this interface (or alias)
-    ebegin "Running udhcpc"
+	# Bring up DHCP for this interface (or alias)
+	ebegin "Running udhcpc"
 
-    # Stop any instance of udhcpc on this interface
-    udhcpc_stop "${interface}"
+	# Stop any instance of udhcpc on this interface
+	udhcpc_stop "${interface}"
 
-    # Try and load the cache if it exists
-    if [[ -f ${cachefile} ]]; then
-	if [[ " ${opts}" != *" --request="* && " ${opts} " != *" -r "* ]]; then
-	   local x=$( < "${cachefile}" )
-	    [[ -n ${x} ]] && opts="${opts} --request=${x}"
+	# Try and load the cache if it exists
+	if [[ -f ${cachefile} ]]; then
+		if [[ " ${opts}" != *" --request="* && " ${opts} " != *" -r "* ]]; then
+			local x=$( < "${cachefile}" )
+			[[ -n ${x} ]] && opts="${opts} --request=${x}"
+		fi
 	fi
-    fi
 
-    if [[ ${background} == "yes" ]]; then
-	eval udhcpc ${opts} --script="${MODULES_DIR}/helpers.d/udhcpc-wrapper" \
-	--pidfile="${pidfile}" --interface="${iface}" &>/dev/null &
-	eend 0
-	go_background
-    fi
+	if [[ ${background} == "yes" ]]; then
+		eval udhcpc ${opts} --script="${MODULES_DIR}/helpers.d/udhcpc-wrapper" \
+		--pidfile="${pidfile}" --interface="${iface}" &>/dev/null &
+		eend 0
+		go_background
+	fi
 
-    x=$( eval udhcpc ${opts} --now --pidfile="${pidfile}" \
+	x=$( eval udhcpc ${opts} --now --pidfile="${pidfile}" \
 	--interface="${iface}" \
 	--script="${MODULES_DIR}/helpers.d/udhcpc-wrapper" 2>&1 \
 	| egrep -v '^info,' )
-    # We just check the last 5 letters
-    [[ ${x:((${#x} - 5)):5} == "bound" ]]
-    eend "$?" "${x}" || return 1
+	# We just check the last 5 letters
+	[[ ${x:((${#x} - 5)):5} == "bound" ]]
+	eend "$?" "${x}" || return 1
 
-    # DHCP succeeded, show address retrieved
-    local addr=$( interface_get_address "${iface}" )
-    einfo "${iface} received address ${addr}"
+	# DHCP succeeded, show address retrieved
+	local addr=$( interface_get_address "${iface}" )
+	einfo "${iface} received address ${addr}"
 
-    return 0
+	return 0
 }
+
+# vim:ts=4
