Misc STYLE and quoting issues fixes in net scripts.
    dhclient and udhcpc now work with RFC violating space separated
    domain names in /etc/resolv.conf - they get appended to the search
    option if it's not specified.

    punted clean_pidfile and process_finished functions and as
    start-stop-daemon as provided by rc-daemon.sh now provides
    the same thing, just better.

svn path=/branches/baselayout-1_12/; revision=1926

diff --git a/net-scripts/net.modules.d/iwconfig b/net-scripts/net.modules.d/iwconfig
--- a/net-scripts/net.modules.d/iwconfig
+++ b/net-scripts/net.modules.d/iwconfig
@@ -331,7 +331,13 @@ iwconfig_associate() {
 	local mac="$3" wep_required="$4" w="(WEP Disabled)"
 	local dessid="${ESSID//\\\\/\\\\}" key
 
-	iwconfig "${iface}" mode "${mode}" 2>/dev/null
+	if ! iwconfig "${iface}" mode "${mode}" ; then
+		eerror "Unable to change mode to ${mode}"
+		return 1
+	fi
+	interface_down "${iface}"
+	interface_up "${iface}"
+
 	if [[ ${ESSID} == "any" ]]; then
 		iwconfig "${iface}" ap any 2>/dev/null
 		dessid="any"
@@ -365,7 +371,7 @@ iwconfig_associate() {
 	fi
 
 	# Finally apply the user Config
-	iwconfig_user_config "${iface}" "${ESSIDVAR}"
+	#iwconfig_user_config "${iface}" "${ESSIDVAR}"
 
 	vebegin "Connecting to \"${dessid}\" ${w}"
 
