Update to 0.6.3 from Roy
svn path=/trunk/; revision=548

diff --git a/net-scripts/net.modules.d/udhcpc b/net-scripts/net.modules.d/udhcpc
--- a/net-scripts/net.modules.d/udhcpc
+++ b/net-scripts/net.modules.d/udhcpc
@@ -1,5 +1,5 @@
 # udhcpc (net-misc/udhcp) module for net-scripts
-# Version 0.6.2
+# Version 0.6.3
 # Copyright (c) 2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License V2
 # Contributed by Roy "UberLord" Marples (uberlord@rsm.demon.co.uk)
@@ -30,7 +30,7 @@ udhcpc_depend() {
 # Returns 1 if udhcpc is installed, otherwise 0
 udhcpc_check_installed() {
 	[[ -x /sbin/udhcpc ]] && return 0
-	[[ true == ${1} ]] && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
+	[[ ${1} == true ]] && eerror "For DHCP (udhcpc) support, emerge net-misc/udhcp"
 	return 1
 }
 
@@ -46,26 +46,13 @@ udhcpc_get_script() {
 #
 # Checks to see if we have the needed functions
 udhcpc_check_depends() {
-	local e
+	local f
 
-	if [[ function != $( type -t get_device ) ]]; then
-		eerror "udhcpc: net.lo is missing the required function get_device\n"
+	for f in get_device interface_is_up interface_get_address interface_module; do
+		[[ $(type -t ${f}) == function ]] && continue
+		eerror "udhcpc: missing required function ${f}\n"
 		return 1
-	fi
-
-	[[ -z ${e} && function != $( type -t interface_get_status ) ]] && e=interface_get_address
-	[[ -z ${e} && function != $( type -t interface_get_address ) ]] && e=interface_get_address
-	[[ -z ${e} && function != $( type -t interface_module ) ]] && e=interface_module
-	if [[ -n ${e} ]]; then
-		eerror "udhcpc: interface is missing the required function ${e}\n"
-		return 1
-	fi
-
-	local script=$( udhcpc_get_script )
-	if [[ ! -f ${script} ]]; then
-		eerror "The required file ${script} does not exist!"
-		return 1
-	fi
+	done
 
 	return 0
 }
@@ -105,7 +92,7 @@ udhcpc_stop() {
 #		while (( i < 30 )); do
 #			addr=$( interface_get_address ${iface} )
 #			[[ -z ${addr} ]] && break
-#			((i = i + 1))
+#			(( i++ ))
 #			sleep 1
 #		done
 		# For some reason we have no mech of removing the process, so
@@ -114,11 +101,8 @@ udhcpc_stop() {
 	done
 
 	r=$( ps -fC udhcpc | awk "/--interface=${iface}/ {print \$1}")
-	if [[ -z ${r} ]]; then
-		eend 0
-	else
-		eend 1
-	fi
+	[[ -z ${r} ]]
+	eend $?
 
 	return 0
 }
@@ -129,20 +113,22 @@ udhcpc_stop() {
 #
 # Returns 0 (true) when a DHCP address is obtained, otherwise 1
 udhcpc_start() {
-	local iface=${1} opts script=$( udhcpc_get_script )
-	local status=$( interface_get_status ${iface} ) check=$( get_device ${iface} )
+	local iface=${1} opts script=$( udhcpc_get_script ) hostname
+	local check=$( get_device ${iface} )
 
 	# Check that iface was not brought up by the kernel ...
-	if [[ ${status} == up && ${check} == ${iface} ]]; then
+	if [[ ${check} == ${iface} ]] && interface_is_up ${iface} true ; then
 		einfo "    Keeping kernel configuration for ${iface}"
 		return 0
 	fi
 
 	# Bring up DHCP for this interface (or alias)
 	eval opts=\"\$\{udhcpc_${iface}\}\"
-	local r=$( udhcpc ${opts} --script=${script} --now --interface=${iface} )
+	hostname=$( hostname )
+	[[ -n ${hostname} ]] && hostname="--hostname=${hostname%%.*}"
+	local r=$( udhcpc ${hostname} ${opts} --script=${script} --now --interface=${iface} )
 	# We just check the last 5 letters
-	if [[ BOUND != ${r:((${#r} - 5)):5} ]]; then
+	if [[ ${r:((${#r} - 5)):5} != BOUND ]]; then
 		eend 1 "  udhcpc recieved a ${r}"
 		return 1
 	fi
diff --git a/net-scripts/net.modules.d/wireless b/net-scripts/net.modules.d/wireless
--- a/net-scripts/net.modules.d/wireless
+++ b/net-scripts/net.modules.d/wireless
@@ -1,5 +1,5 @@
 # Wireless module for net-scripts
-# Version 0.6.2
+# Version 0.6.3
 # Copyright (c) 2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License V2
 # Contributed by Roy "UberLord" Marples (uberlord@rsm.demon.co.uk)
@@ -35,7 +35,7 @@ wireless_depend() {
 # Returns 1 if wireless-tools is installed, otherwise 0
 wireless_check_installed() {
 	[[ -x /usr/sbin/iwconfig ]] && return 0
-	[[ true == ${1} ]] && eerror "For Wireless (802.11) support, emerge net-wireless/wireless-tools"
+	[[ ${1} == true ]] && eerror "For Wireless (802.11) support, emerge net-wireless/wireless-tools"
 	return 1
 }
 
@@ -50,14 +50,15 @@ wireless_provides() {
 #
 # Checks to see if we have the needed functions
 wireless_check_depends() {
-	local e
+	local f
 
-	[[ -z ${e} && function != $( type -t interface_up ) ]] && e=interface_up
-	[[ -z ${e} && function != $( type -t interface_down ) ]] && e=interface_up
-	[[ -z ${e} ]] && return 0
+	for f in interface_up interface_down interface_del_addresses; do
+		[[ $(type -t ${f}) == function ]] && continue
+		eerror "wireless: missing required function ${f}\n"
+		return 1
+	done
 
-	eerror "wireless: interface is missing the required function ${e}\n"
-	return 1
+	return 0
 }
 
 # bool wireless_check_extensions(char *interface)
@@ -68,8 +69,8 @@ wireless_check_extensions() {
 
 	# Do we have wireless extensions enabled on the interface?
 	local ext=$(iwconfig ${iface} 2>/dev/null | awk -v iface=${iface} '{ if ($1 == iface) print "yes" }')
-	[[ yes == ${ext} ]] && return 0
-	return 1
+	[[ ${ext} == yes ]]
+	return $?
 }
 
 # char* wireless_wep_status(char *interface)
@@ -86,7 +87,10 @@ wireless_wep_status() {
 #
 # Gets the current ESSID of the iface
 wireless_get_essid() {
-	iwgetid ${1} 2>${devnull} | awk -F\" '/ESSID/ {print $2}'
+	# Too many users are having with iwgetid atm :/
+	# iwgetid -r
+
+	iwconfig ${1} 2>${devnull} | awk -F\" '/ESSID/ {print $2}'
 }
 
 # char* wireless_get_ap_mac_address(char *interface)
@@ -102,6 +106,13 @@ wireless_get_ap_mac_address() {
 # Returns the wireless mode in lower case
 wireless_get_mode() {
 	iwgetid -m ${1} | awk -F: '{print $2}' | tr '[:upper:]' '[:lower:]'
+}
+
+# char* wireless_get_type(char *interface)
+#
+# Returns the type of interface - the IEEE part
+wireless_get_type() {
+	iwconfig ${1} 2>/dev/null | awk '{print $2,$3}'
 }
 
 # void wireless_report(char *interface)
@@ -126,7 +137,7 @@ wireless_report() {
 
 	essid=${essid//\\\\/\\\\}
 	local mode=$( wireless_get_mode ${iface} )
-	if [[ managed == ${mode} ]]; then
+	if [[ ${mode} == managed ]]; then
 		m="to"
 		mac=$( wireless_get_ap_mac_address ${iface} )
 		mac=" at ${mac}"
@@ -200,7 +211,7 @@ wireless_setup_iface() {
 			evars=( $( ${func} ${essid} ) )
 			mvars=( $( ${func} ${mac} ) )
 			vars=( $( ${func} ${iface} ) )
-			for ((i = 0; i < ${#mvars[@]}; i++)); do
+			for ((i = 0; i<${#mvars[@]}; i++)); do
 				eval x=( \"\$\{mac_${mvars[i]}\[@\]\}\" )
 				[[ -z ${x} ]] && eval x=( \"\$\{${evars[i]}\[@\]\}\" )
 				[[ -n ${x} ]] && eval "${vars[i]}=( "\"\$\{x\[@\]\}\"" )"
@@ -209,13 +220,16 @@ wireless_setup_iface() {
 	done
 
 	# Nameserver setup for the essid if required
-	eval x=\"\$\{mac_nameserver_${mac}\}\"
-	[[ -z ${x} ]] && eval x=\"\$\{nameserver_${essid}\}\"
-	if [[ -n ${x} ]]; then
+	local -a nameservers=( \"\$\{mac_nameservers_${mac}\[@\]\}\" )
+	[[ -z ${nameservers} ]] && eval nameservers=( \"\$\{nameservers_${essid}\[@\]\}\" )
+	if [[ -n ${nameservers} ]]; then
 		# Make a backup of the origional file if necessary
 		[[ -f /etc/resolv.conf ]] && mv /etc/resolv.conf /etc/resolv.conf.sv
-		echo "nameserver ${x}" > /etc/resolv.conf
+		echo "# Generated by net-scripts wireless module" > /etc/resolv.conf
 		chmod 644 /etc/resolv.conf
+		for x in ${nameservers[@]}; do
+			echo "nameserver ${x}" >> /etc/resolv.conf
+		done
 		eval x=\"\$\{mac_domain_${mac}\}\"
 		[[ -z ${x} ]] && eval x=\"\$\{domain_${essid}\}\"
 		if [[ -n ${x} ]]; then
@@ -254,7 +268,7 @@ wireless_setup_specific() {
 
 	key=$( wireless_get_wep_key )
 	e=$( iwconfig ${iface} key ${key} 2>&1 )
-	if [[ -n ${e} && off != ${key} ]]; then
+	if [[ -n ${e} && ${key} != off ]]; then
 		e=$( get_essid_var ${essid} )
 		ewarn "  ${iface} does not support setting keys"
 		ewarn "  or the parameter \"mac_key_${e}\" or \"key_${e}\" is incorrect"
@@ -305,7 +319,7 @@ wireless_associate_mac() {
 # Returns true if the link quality is not 0 or 0.
 wireless_associate_quality() {
 	local quality=$( cat /proc/net/wireless | awk -v IFACE=${1}: '{ if ($1 == IFACE) print $3 }' )
-	[[ 0 != ${quality} && 0. != ${quality} ]] && return 0
+	[[ ${quality} != 0 && ${quality} != 0. ]] && return 0
 	return 1
 }
 
@@ -319,7 +333,7 @@ wireless_test_associated() {
 
 	test=$( eval echo \$\{associate_test_${iface}\} | tr '[:upper:]' '[:lower:]' )
 	test=${test:-mac}
-	if [[ mac != ${test} && quality != ${test} && all != ${test} ]]; then
+	if [[ ${test} != mac && ${test} != quality && ${test} != all ]]; then
 		ewarn "    associate_test_${iface} is not set to mac, quality or all"
 		ewarn "    defaulting to \"mac\""
 		test=mac
@@ -343,10 +357,10 @@ wireless_wait_for_association() {
 	eval wait=\"\$\{sleep_associate_${iface}\}\"
 	wait=${wait:-10}
 
-	while ((${i} < (${wait}))); do
+	while (( i<wait )); do
 		wireless_test_associated ${iface} && return 0
 		sleep 1
-		(( i = i + 1 ))
+		(( i++ ))
 	done
 	return 1
 }
@@ -362,41 +376,40 @@ wireless_associate() {
 	local dessid=${ESSID//\\\\/\\\\} key=$( wireless_get_wep_key ${mac} )
 	wep_required=${wep_required:-"off"}
 
-	if [[ any == ${ESSID} ]]; then
+	if [[ ${ESSID} == any ]]; then
 		iwconfig ${iface} ap any 2>/dev/null
 		dessid="any"
 	else
-		if [[ yes == ${wep_required} && off == ${key} ]]; then
+		if [[ ${wep_required} == yes && ${key} == off ]]; then
 			ewarn "  WEP key is not set for \"${dessid}\" - not connecting"
 			return 1
 		fi
-		if [[ no == ${wep_required} && off != ${key} ]]; then
+		if [[ ${wep_required} == no && ${key} != off ]]; then
 			key="off"
 			ewarn "  \"${dessid}\" is not WEP enabled - ignoring setting"
 		fi
 		e=$( iwconfig ${iface} key ${key} 2>&1 )
-		if [[ -n ${e} && off != ${key} ]]; then
+		if [[ -n ${e} && ${key} != off ]]; then
 			e=$( wireless_get_essid_var ${essid} )
 			ewarn "  ${iface} does not support setting keys"
 			ewarn "  or the parameter \"mac_key_${e}\" or \"key_${e}\" is incorrect"
 			return 1
 		fi
-		[[ off != ${key} ]] && w="(WEP enabled)"
+		[[ ${key} != off ]] && w="(WEP enabled)"
 	fi
 
 	e=$( iwconfig ${iface} essid "${ESSID}" 2>&1 )
-	[[ -n ${e} && any != ${essid} ]] \
-		&& ewarn "  ${iface} does not support setting ESSID to \"${dessid}\""
+	[[ -n ${e} && ${ESSID} != any ]] && ewarn "  ${iface} does not support setting ESSID to \"${dessid}\""
 	iwconfig ${iface} nick "${ESSID}" 2>/dev/null
 
 	ebegin "  Connecting to \"${ESSID//\\\\//}\" ${w}"
-	wireless_wait_for_association ${iface} || {
+	if ! wireless_wait_for_association ${iface} ; then
 		eend 1
 		return 1
-	}
+	fi
 	eend 0
 
-	if [[ any == ${ESSID} ]]; then
+	if [[ ${ESSID} == any ]]; then
 		ESSID=$( get_essid ${iface} )
 		wireless_associate ${iface}
 		return $?
@@ -437,7 +450,7 @@ wireless_scan() {
 	eval x=\"\$\{sleep_scan_${iface}\}\"
 	[[ -n ${x} ]] && sleep ${x}
 
-	local scan=$( iwlist ${iface} scan 2>/dev/null )
+	local scan=$( iwlist ${iface} scanning 2>/dev/null )
 
 	# We may need to unset the previous private driver ioctls
 	eval x=\"\$\{iwpriv_scan_post_${iface}\}\"
@@ -450,7 +463,7 @@ wireless_scan() {
 	fi
 
 	# Change back to the managed mode if needed
-	[[ managed != ${mode} ]] && iwconfig ${iface} mode managed 2>${devnull}
+	[[ ${mode} != managed ]] && iwconfig ${iface} mode managed 2>${devnull}
 
 	if [[ -z ${scan} ]]; then
 		ewarn "${iface} does not support scanning"
@@ -479,22 +492,28 @@ wireless_scan() {
 		else
 			t=$( echo ${val} | awk '/Address/ {print}' | sed 's/^.*\<\(..:..:..:..:..:..\)\>.*$/\1/g' )
 			if [[ ${#t} -gt 0 ]]; then
-				((i = i + 1))
+				((i++))
 				mac_APs[i]=${t}
 				essid_APs[i]=""
-				enc_APs[i]=""
+				enc_APs[i]=no
+				qual[i]=0
 			else
 				t=$( echo ${val} | awk -F: '/Encryption key/ {print $2}' )
 				if [[ ${#t} -gt 0 ]]; then
-					if [[ off == ${t} ]]; then
-						enc_APs[i]=no;
+					if [[ ${t} == off ]]; then
+						enc_APs[i]=no
 					else
-						enc_APs[i]=yes;
+						enc_APs[i]=yes
 					fi
 				else
 					t=$( echo ${val} | awk -F: '/Quality/ {print $2}' )
 					if [[ ${#t} -gt 0 ]]; then
-						qual[i]=${t%/*}
+						# Not all drivers report the same way, so we take the below measure
+						# to ensure we don't error on the sort below
+						t=${t# *}
+						t=${t%/*}
+						t=${t//[![:digit:]]/}
+						qual[i]=${t:-0}
 					fi
 				fi
 			fi
@@ -502,8 +521,8 @@ wireless_scan() {
 	done
 
 	# Now sort the AP's by quality
-	for (( last = ${#mac_APs[@]} - 1; last > 0; last-- )); do
-		for (( i = 0; i < ${last}; i++ )); do
+	for ((last=${#mac_APs[@]}-1; last>0; last--)); do
+		for ((i=0; i<${last}; i++)); do
 			(( j = i + 1 ))
 			if [[ ${qual[i]} -lt ${qual[j]} ]]; then
 				t=${mac_APs[i]}
@@ -537,9 +556,9 @@ wireless_scan_report() {
 
 	# We need to do the for loop like this so we can
 	# dynamically remove from the array
-	for (( i = 0; i < ${#mac_APs[@]}; i++ )); do
+	for ((i=0; i<${#mac_APs[@]}; i++)); do
 		k=""
-		[[ yes == ${enc_APs[i]} ]] && k="(WEP required)"
+		[[ ${enc_APs[i]} == yes ]] && k="(WEP required)"
 
 		if [[ -z ${essid_APs[i]} ]]; then
 			einfo "    Found ${mac_APs[i]} ${k}"
@@ -567,7 +586,7 @@ wireless_scan_report() {
 				fi
 			done
 		fi
-		[[ true == ${remove} ]] && u=( "${u[@]}" "${i}" )
+		${remove} && u=( "${u[@]}" "${i}" )
 	done
 
 	# Now we remove any duplicates
@@ -607,7 +626,7 @@ wireless_force_preferred() {
 				break
 			fi
 		done
-		if [[ false == ${found_AP} ]]; then
+		if ! ${found_AP} ; then
 			ESSID=${essid}
 			wireless_associate ${iface} && return 0
 		fi
@@ -625,7 +644,7 @@ wireless_connect_preferred() {
 	local iface=${1} essid i
 
 	for essid in "${preferred_aps[@]}"; do
-		for ((i = 0; i < ${#essid_APs[@]}; i++)); do
+		for ((i=0; i<${#essid_APs[@]}; i++)); do
 			if [[ ${essid} == ${essid_APs[i]} ]]; then
 				ESSID=${essid}
 				wireless_associate ${iface} ${mac_APs[i]} ${enc_APs[i]} && return 0
@@ -644,7 +663,7 @@ wireless_connect_preferred() {
 wireless_connect_not_preferred() {
 	local iface=${1} i ap has_preferred
 
-	for ((i = 0; i < ${#mac_APs[@]}; i++)); do
+	for ((i=0; i<${#mac_APs[@]}; i++)); do
 		has_preferred=false
 		for ap in "${preferred_aps[@]}"; do
 			if [[ ${ap} == ${essid_APs[i]} ]]; then
@@ -652,7 +671,7 @@ wireless_connect_not_preferred() {
 				break
 			fi
 		done
-		if [[ false == ${has_preferred} ]]; then
+		if ! ${has_preferred} ; then
 			ESSID=${essid_APs[i]}
 			wireless_associate ${iface} ${mac_APs[i]} ${enc_APs[i]} && return 0
 		fi
@@ -695,7 +714,7 @@ wireless_strip_associated() {
 		wireless_test_associated ${i} || continue
 		e=$( iwconfig ${i} | awk -F\" '/ESSID/ {print $2}' )
 		u=()
-		for (( j = 0; j < ${#mac_APs[@]}; j++ )); do
+		for ((j=0; j<${#mac_APs[@]}; j++)); do
 			if [[ ${essid_APs[j]} == ${e} ]]; then
 				ewarn "    ${e} has already been associated with ${i}"
 				unset essid_APs[j]
@@ -708,7 +727,7 @@ wireless_strip_associated() {
 				break
 			fi
 		done
-		for (( j = 0; j < ${#preferred_aps[@]}; j++ )); do
+		for ((j=0; j<${#preferred_aps[@]}; j++)); do
 			if [[ ${preferred_aps[j]} == ${e} ]]; then
 				unset preferred_aps[j]
 				preferred_aps=( "${preferred_aps[@]}" )
@@ -732,6 +751,14 @@ wireless_configure() {
 
 	# We need to bring the interface up to apply stuff
 	interface_up ${iface}
+
+	# Are we a proper IEEE device?
+	e=$( wireless_get_type ${iface} )
+	if [[ ${e%% *} != IEEE ]]; then
+		eerror "Looks like there was a probem loading the firmware for ${iface}"
+		return 1
+	fi
+	
 	wireless_defaults ${iface}
 
 	eval ESSID=\"\$\{essid_${iface}\}\"
@@ -739,12 +766,12 @@ wireless_configure() {
 	# Setup ad-hoc mode?
 	x=$( eval echo \$\{mode_${iface}\} | tr '[:upper:]' '[:lower:]' )
 	x=${x:-managed}
-	if [[ ad-hoc == ${x} || master == ${x} ]]; then
+	if [[ ${x} == ad-hoc || ${x} == master ]]; then
 		wireless_setup_specific ${iface} ${x}
 		return $?
 	fi
 
-	if [[ managed != ${x} ]]; then
+	if [[ ${x} != managed ]]; then
 		eerror "Only managed, ad-hoc and master modes are supported"
 		return 1
 	fi
@@ -766,7 +793,7 @@ wireless_configure() {
 	# Has an ESSID been forced?
 	if [[ -n ${ESSID} ]]; then
 		wireless_associate ${iface} && return 0
-		[[ any == ${ESSID} ]] && wireless_force_preferred ${iface} && return 0
+		[[ ${ESSID} == any ]] && wireless_force_preferred ${iface} && return 0
 
 		eval ESSID=\"\$\{adhoc_essid_${iface}\}\"
 		if [[ -n ${ESSID} ]]; then
@@ -806,7 +833,7 @@ wireless_configure() {
 	eval e=\"\$\{preferred_only_${iface}\}\"
 	[[ -n ${e} ]] && preferred_only=${e}
 	preferred_only=$( echo ${preferred_only:-no} | tr '[:upper:]' '[:lower:]' )
-	[[ no == ${preferred_only} ]] && wireless_connect_not_preferred ${iface} && return 0
+	[[ ${preferred_only} == no ]] && wireless_connect_not_preferred ${iface} && return 0
 
 	e="associate with"
 	[[ -z ${mac_APs} ]] && e="find"
@@ -829,24 +856,35 @@ wireless_configure() {
 # First we check if wireless extensions exist on the interface
 # If they are then we configue wireless
 wireless_pre_start() {
-	local iface=${1} r=0
+	local iface=${1} r=0 local wasup=true
 
-	wireless_check_extensions ${iface} || {
+	if ! interface_is_up ${iface} ; then
+		interface_up ${iface}
+		wasup=false
+	fi
+
+	if ! wireless_check_extensions ${iface} ; then
 		einfo "  Wireless extensions not found for ${iface}"
+		! ${wasup} && interface_down ${iface}
 		return 0
-	}
+	fi
 
 	einfo "  Configuring wireless network for ${iface}"
 
 	# Setup IFS incase parent script has modified it
 	local IFS=$' '$'\n'$'\t'
 
-	wireless_configure ${iface} && return 0
+	if wireless_configure ${iface} ; then
+		# This causes DHCP to work - and we don't have to take down the interface
+		# which makes things a lot faster
+		interface_del_addresses ${iface}
+		return 0
+	fi
 
 	eerror "Failed to configure wireless for ${iface}"
 	wireless_defaults ${iface}
 	unset ESSID
-	interface_down ${iface}
+	! ${wasup} && interface_down ${iface}
 	return 1
 }
 
@@ -855,17 +893,23 @@ wireless_pre_start() {
 # Removes wireless configuration if applicable
 # Always returns 0
 wireless_post_stop() {
-	local iface=${1}
+	local iface=${1} wasup=true
 
-        wireless_check_extensions ${iface} || return 0
+	if ! interface_is_up ${iface} ; then
+		interface_up ${iface}
+		wasup=false
+	fi
 
-	# Set the ESSID var for use in any postdown functions
-	ESSID=$( iwconfig ${iface} | awk -F\" '/ESSID/ {print $2}' )
+        if wireless_check_extensions ${iface} ; then
+		# Set the ESSID var for use in any postdown functions
+		ESSID=$( iwconfig ${iface} | awk -F\" '/ESSID/ {print $2}' )
 
-	ebegin "  Removing wireless configuration from ${iface}"
-	wireless_defaults ${iface}
-	eend 0
+		ebegin "  Removing wireless configuration from ${iface}"
+		wireless_defaults ${iface}
+		eend 0
+	fi
+
+	! ${wasup} && interface_down ${iface}
 
 	return 0
 }
-
