Fix bug 20597: Skip RCS files when updating modules.
Fix bug 49926: Add a --assume-kernel flag to modules-update.  This
requires a companion patch in module-init-tools-3.0-r2 to handle the
same flag in generate-modprobe.conf; this dependency won't be handled
in the baselayout ebuild since it only affects livecd building.

svn path=/trunk/; revision=499

diff --git a/sbin/modules-update b/sbin/modules-update
--- a/sbin/modules-update
+++ b/sbin/modules-update
@@ -3,10 +3,13 @@
 # This is the modules-update script for Debian GNU/Linux.
 # Written by Wichert Akkerman <wakkerma@debian.org>
 # Copyright (C) 1998, 1999 Software in the Public Interest
-
+#
 # Modifications by Daniel Robbins <drobbins@gentoo.org>, Gentoo Technologies, Inc.
-# 02 Sep 2001 -- Removed "arch" stuff since I see no reason to have support for varying
-# CPU architectures on a single system.
+# 02 Sep 2001 -- Removed "arch" stuff since I see no reason to have
+# support for varying CPU architectures on a single system.
+#
+# Updated by Aron Griffis <agriffis@gentoo.org> 
+# 05 May 2004 -- handle --assume-kernel argument for livecd building
 
 CFGFILE="/etc/modules.conf"
 TMPFILE="${CFGFILE}.$$"
@@ -22,11 +25,27 @@ HEADER="### This file is automatically generated by modules-update"
 
 source /sbin/functions.sh
 
-KERNEL_2_5="no"
+# Parse command-line
+FORCE=false
+KV=$(uname -r)
+while [ -n "$1" ]; do
+	case "$1" in
+		force) 
+			FORCE=true ;;
+		--assume-kernel=*) 
+			KV=${1#*=} ;;
+		*)
+			echo "Error: I don't understand $1" >&2
+			exit 1 ;;
+	esac
+	shift
+done
 
-if [ "$(get_KV)" -ge "$(KV_to_int '2.5.48')" ]
-then
-	KERNEL_2_5="yes"
+# Set kernel version, either from --assume-kernel or uname -r
+if [[ $(KV_to_int ${KV}) -ge $(KV_to_int 2.5.48) ]]; then
+	KERNEL_2_5=true
+else
+	KERNEL_2_5=false
 fi
 
 set -e
@@ -38,7 +57,7 @@ depdir() {
 	dep="`egrep '[[:space:]]*depfile' ${CFGFILE} | tail -n 1 | sed -e 's/depfile=//' -e 's,/[^/]*$,,'`"
 	if [ -z "${dep}" ]
 	then
-	    dep="/lib/modules/$(uname -r)"
+	    dep="/lib/modules/${KV}"
 	fi
 
 	echo "${dep}"
@@ -46,8 +65,7 @@ depdir() {
 
 CFGFILES="${CFGFILE}"
 
-if [ "${KERNEL_2_5}" = "yes" ]
-then
+if ${KERNEL_2_5}; then
 	CFGFILES="${CFGFILES} ${CFGFILE2} ${CFGFILE4}"
 fi
 
@@ -59,12 +77,11 @@ do
 		then
 			echo "Error: the current ${x} is not automatically generated."
 		
-			if [ "$1" != "force" ]
-			then
+			if $FORCE; then
+				echo "force specified, (re)generating file anyway."
+			else
 				echo "Use \"modules-update force\" to force (re)generation."
 				exit 1
-			else
-				echo "force specified, (re)generating file anyway."
 			fi
 		fi
 	fi
@@ -80,8 +97,7 @@ if [ -e "${CFGFILE}" ]
 then
 	cp -f "${CFGFILE}" "${CFGFILE}".old
 fi
-if [ "${KERNEL_2_5}" = "yes" ]
-then
+if ${KERNEL_2_5}; then
 	if [ -e "${CFGFILE2}" ]
 	then
 		cp -f "${CFGFILE2}" "${CFGFILE2}".old
@@ -101,7 +117,7 @@ cat <<EOF >> "${TMPFILE}"
 # the manpage for modules-update.
 #
 EOF
-if [ -x /sbin/generate-modprobe.conf -a "${KERNEL_2_5}" = "yes" ]
+if [ -x /sbin/generate-modprobe.conf -a "${KERNEL_2_5}" = "true" ]
 then
 	sed -e "s:the files in ${MODDIR}:${CFGFILE}:" \
 		"${TMPFILE}" > "${TMPFILE2}"
@@ -119,7 +135,8 @@ do
 
 	[ ! -r "${cfg}" ] && continue
 
-	[ -n "`echo "${cfg}" | awk '!/~$|\.bak$/ { print $0 }'`" ] || continue
+	# Skip backup and RCS files; fixes bug 20597 (07 May 2004 agriffis)
+	[[ ${cfg} == *~ || ${cfg} == *.bak || ${cfg} == *,v ]] && continue
 	
 	echo "### modules-update: start processing ${cfg}" >> "${TMPFILE}"
 	
@@ -138,9 +155,9 @@ done
 
 mv -f "${TMPFILE}" "${CFGFILE}"
 
-if [ -x /sbin/generate-modprobe.conf -a "${KERNEL_2_5}" = "yes" ]
+if [ -x /sbin/generate-modprobe.conf -a "${KERNEL_2_5}" = "true" ]
 then
-	if /sbin/generate-modprobe.conf >> "${TMPFILE2}" 2> /dev/null
+	if /sbin/generate-modprobe.conf --assume-kernel=${KV} >> "${TMPFILE2}" 2> /dev/null
 	then
 		mv -f "${TMPFILE2}" "${CFGFILE2}"
 	else
@@ -153,7 +170,7 @@ then
 		gawk '$0 !~ /^[[:space:]]*include/ { print $0 }' "${CFGFILE3}" > "${TMPFILE3}"
 		
 		export TESTING_MODPROBE_CONF="${TMPFILE3}"
-		if /sbin/generate-modprobe.conf >> "${TMPFILE4}" 2> /dev/null
+		if /sbin/generate-modprobe.conf --assume-kernel=${KV} >> "${TMPFILE4}" 2> /dev/null
 		then
 			mv -f "${TMPFILE4}" "${CFGFILE4}"
 
@@ -172,7 +189,11 @@ fi
 #
 if [ -d "`depdir`" -a -f /proc/modules ]
 then
-	depmod -a
+	if [ -f /usr/src/linux/System.map ]; then
+		depmod -a -F /usr/src/linux/System.map ${KV}
+	else
+		depmod -a ${KV}
+	fi
 fi
 
 
