drop init wrapper; LVM support; better unmount on shutdown support
svn path=/trunk/; revision=85

diff --git a/sbin/rc b/sbin/rc
--- a/sbin/rc
+++ b/sbin/rc
@@ -1,10 +1,120 @@
 #!/bin/bash
+# Copyright 1999-2002 Gentoo Technologies, Inc.
+# Distributed under the terms of the GNU General Public License, v2 or later
+# $Header$
 
-if [ -z "$1" ]
+trap ":" INT QUIT TSTP
+source /etc/init.d/functions.sh
+umask 022
+
+try() {
+	eval $*
+	if [ $? -ne 0 ]
+	then
+		echo -e "$ENDCOL$NORMAL[$BAD oops $NORMAL]"
+		echo
+		echo '!!! '"ERROR: the $1 command did not complete successfully."
+		echo '!!! '"(\" ${*} \")"
+		echo '!!! '"Since this is a critical task, startup cannot continue."
+		echo
+		/sbin/sulogin $CONSOLE
+		reboot -f
+		fi
+}
+
+#save $1
+argv1=$1
+
+#first time boot stuff goes here
+if [ "$RUNLEVEL" = "S" ] && [ "$argv1" = "boot" ]
+then
+	echo
+	echo -e "${GOOD}Gentoo Linux${GENTOO_VERS}; \e[34;01mhttp://www.gentoo.org${NORMAL}"
+	echo -e " Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL"
+	echo
+
+	ebegin "Mounting /proc"
+	try mount -n /proc
+	eend $?
+	
+	devfs="yes"
+	for copt in `cat /proc/cmdline`
+	do
+		if [ "${copt%=*}" = "gentoo" ]
+		then
+			parms=${copt##*=}
+			#parse gentoo option
+			if [ "${parms/nodevfs//}" != "${parms}" ]
+			then
+				devfs="no"
+			fi
+		fi
+	done
+	
+	#with the new way, /dev can be mounted by the kernel ...
+	
+	if [ "$devfs" = "yes" ] && [ ! -e /dev/.devfsd ]
+	then
+		mymounts="`cat /proc/filesystems`"
+		#is devfs support compiled in?
+		if [ "${mymounts/devfs//}" != "${mymounts}" ]
+		then
+			ebegin "Mounting devfs at /dev"; try mount -n -t devfs none /dev; eend
+		else
+			clear
+			echo
+			einfo "The Gentoo Linux system initialization scripts have detected that your"
+			einfo "kernel has been compiled without DEVFS support.  Because Gentoo Linux"
+			einfo "has been designed to work with DEVFS, it is required that you compile"
+			einfo "support for it into your kernel.  Please read the 'Gentoo Linux from"
+			einfo "source (build) CD Installation Guide' at:"
+			echo
+			einfo "    http://www.gentoo.org/doc/build.html"
+			echo
+			einfo "for more information on how to do this."
+			echo
+			read -t 15 -p "(hit Enter to continue or wait 15 seconds...)"
+		fi
+	fi
+
+	#mount shm and do dep scan
+	
+	ebegin "Mounting tmpfs at /dev/shm"
+	try mount -n -t tmpfs tmpfs /dev/shm -o rw,mode=0644,size=4m
+	eend
+			
+	/etc/init.d/depscan.sh
+
+	if [ "$devfs" = "yes" ] && [ -e /dev/.devfsd ]
+	then
+		ebegin "Starting devfsd"; /sbin/devfsd /dev >/dev/null 2>&1; eend $?
+	fi
+
+	#swap needs to be activated *after* devfs has been mounted and *after*
+	#devfsd has been started, so that the fstab can be properly parsed
+
+	ebegin "Activating swap"
+	swapon -a
+	eend
+
+	#set the console loglevel to 1 for a cleaner boot
+	#the logger should anyhow dump the ring-0 buffer at start to the
+	#logs, and that with dmesg can be used to check for problems
+	
+	/bin/dmesg -n 1
+
+	#$BOOT can be used by rc-scripts to test if it is the first time
+	#the 'boot' runlevel is executed
+	
+	export BOOT="yes"
+	
+fi #boot ends here
+
+if [ -z "$argv1" ]
 then
 	export SOFTLEVEL="`cat /dev/shm/.init.d/softlevel`"
 else
-	export SOFTLEVEL=$1
+	export SOFTLEVEL=$argv1
 fi
 svcdir=/dev/shm/.init.d
 
@@ -81,7 +191,7 @@ do
 			do
 				for dep in ${svcdir}/${mytype}/${myservice}/*
 				do
-					if [ -L /${svcdir}/softscripts.new/${dep##*/} ]
+					if [ -e ${dep} ] && [ -L /${svcdir}/softscripts.new/${dep##*/} ]
 					then
 						#this dep is valid
 						needsme=1
@@ -99,6 +209,7 @@ done
 
 # Only change softlevel AFTER all the services have been stopped,
 # else they will not get the depend's right (wrong SOFTLEVEL)
+
 echo $SOFTLEVEL > /dev/shm/.init.d/softlevel
 
 if [ "$SOFTLEVEL" = "reboot" ] || [ "$SOFTLEVEL" = "shutdown" ]
@@ -115,6 +226,7 @@ fi
 
 #clean out directory to remove traces of previous runlevel
 #and make the new softscripts directory the current
+
 rm -rf ${svcdir}/softscripts
 mv ${svcdir}/softscripts.new/ ${svcdir}/softscripts
 
@@ -135,6 +247,7 @@ done
 #depends gets newked, so update them
 #(this problem should be solved now, but i think it will be a good idea
 # to recreate the deps after a change in runlevel)
+
 /etc/init.d/depscan.sh >/dev/null 2>/dev/null
 
 #we want devfsd running after a change of runlevel (this is mostly if we return
