Add extra checks for critical directories to /sbin/rc.;  Release 1.4.3.12
svn path=/trunk/; revision=441

diff --git a/sbin/rc b/sbin/rc
--- a/sbin/rc
+++ b/sbin/rc
@@ -42,17 +42,19 @@ try() {
 	return ${retval}
 }
 
-# Check that $svcdir exists ...
+# Check that $1 exists ...
 check_statedir() {
-	if [ ! -d "${svcdir}" ] 
+	[ -z "$1" ] && return 0
+	
+	if [ ! -d "$1" ] 
 	then
-		if ! mkdir -p "${svcdir}" &> /dev/null
+		if ! mkdir -p "$1" &>/dev/null
 		then
 			echo
-			eerror "For Gentoo Linux to function properly, \"${svcdir}\" need to exist."
+			eerror "For Gentoo Linux to function properly, \"$1\" need to exist."
 			eerror "Please mount your root partition read/write, and execute:"
 			echo
-			eerror "  # mkdir -p ${svcdir}"
+			eerror "  # mkdir -p $1"
 			echo; echo
 			/sbin/sulogin ${CONSOLE}
 			einfo "Unmounting filesystems"
@@ -104,6 +106,8 @@ then
 	echo -e " Copyright 2001-2003 Gentoo Technologies, Inc.; Distributed under the GPL"
 	echo
 
+	check_statedir /proc
+
 	ebegin "Mounting proc at /proc"
 	try try mount -n -t proc none /proc
 	eend $?
@@ -118,6 +122,8 @@ then
 	then
 		ewarn "No /sys to mount sysfs needed in 2.6 and later kernels!"
 	fi
+
+	check_statedir /dev
 
 	devfs="yes"
 	udev="yes"
@@ -209,7 +215,9 @@ then
 			if [ ! -d /dev/pts -a -e "/dev/.devfsd" -a "${mymounts}" = "yes" ]
 			then
 				# Make sure we have /dev/pts
-				mkdir -p /dev/pts &> /dev/null
+				mkdir -p /dev/pts &>/dev/null || \
+					ewarn "Could not create /dev/pts!"
+				
 			fi
 
 			if [ -d /dev/pts ]
@@ -250,14 +258,14 @@ then
 	# Mount either a ramdisk or tmpfs if requested.
 	# we do this to temp mount, until we can get /var mounted ...
 	tsvcdir="/mnt/.init.d"
-	
+
 	# Should we use tmpfs or a ramdisk for caching dependency and
 	# general initscript data?  Note that the 'gentoo=tmpfs' kernel
 	# option should override most settings ...
 	if get_bootparam "tmpfs" || \
 	   [ "${svcmount}" = "yes" -a "${svcfstype}" = "tmpfs" ]
 	then
-		mkdir -p "${tsvcdir}" &> /dev/null
+		check_statedir "${tsvcdir}"
 		
 		ebegin "Mounting tmpfs at ${tsvcdir}"
 		try mount -n -t tmpfs tmpfs "${tsvcdir}" \
@@ -267,8 +275,8 @@ then
 	elif get_bootparam "ramfs" || \
 	     [ "${svcmount}" = "yes" -a "${svcfstype}" = "ramfs" ]
 	then
-		mkdir -p "${tsvcdir}"
-		
+		check_statedir "${tsvcdir}"
+
 		ebegin "Mounting ramdisk 0 at ${tsvcdir}"
 		try dd if=/dev/zero of=/dev/ram0 bs=1k count="${svcsize}"
 		try /sbin/mke2fs -i 1024 -vm0 /dev/ram0 "${svcsize}"
@@ -342,7 +350,7 @@ then
 		fi
 	done
 	# Check that $svcdir exists ...
-	check_statedir
+	check_statedir "${svcdir}"
 
 	# Since we are using tmpfs or ramfs, just bin to $tsvcdir to $svcdir
 	if get_bootparam "tmpfs" || get_bootparam "ramfs" || [ "${svcmount}" = "yes" ]
