lost of fixes
svn path=/trunk/; revision=144

diff --git a/sbin/rc b/sbin/rc
--- a/sbin/rc
+++ b/sbin/rc
@@ -3,62 +3,77 @@
 # Distributed under the terms of the GNU General Public License, v2 or later
 # $Header$
 
-#trap ":" INT QUIT TSTP
+
+trap ":" INT QUIT TSTP
 source /etc/init.d/functions.sh
 umask 022
 
 try() {
-	eval $* >/dev/null 2>&1
-	if [ $? -ne 0 ]
+	local retval=0
+	#this works fine in test, but real life booting, fails for mounting /proc
+	#for instance, if we only check $?, thus we need to [ -n "${errstr}" ]
+	#as well
+	local errstr="$((eval $*) 2>&1 >/dev/null)"
+	retval=$?
+	if [ "${retval}" -ne 0 ] || [ -n "${errstr}" ]
 	then
-		echo -e "$ENDCOL$NORMAL[$BAD oops $NORMAL]"
+		echo -e "${ENDCOL}${NORMAL}[${BAD} oops ${NORMAL}]"
 		echo
-		echo '!!! '"ERROR: the $1 command did not complete successfully."
-		echo '!!! '"(\" ${*} \")"
-		echo '!!! '"Since this is a critical task, startup cannot continue."
+		eerror "The \"${1}\" command failed with error:"
 		echo
-		/sbin/sulogin $CONSOLE
-		reboot -f
-		fi
+		echo "${errstr#*: }"
+		echo
+		eerror "Since this is a critical task, startup cannot continue."
+		echo
+		/sbin/sulogin ${CONSOLE}
+		/sbin/reboot -f
+	fi
+	return ${retval}
 }
 
 #save $1
-argv1=$1
+argv1="${1}"
 
 #first time boot stuff goes here
-if [ "$RUNLEVEL" = "S" ] && [ "$argv1" = "boot" ]
+if [ "${RUNLEVEL}" = "S" ] && [ "${argv1}" = "boot" ]
 then
+	#setup initial $PATH just in case
+	PATH="/bin:/sbin:/usr/bin:/usr/sbin:${PATH}"
+
 	echo
 	echo -e "${GOOD}Gentoo Linux${GENTOO_VERS}; \e[34;01mhttp://www.gentoo.org${NORMAL}"
 	echo -e " Copyright 2001 Gentoo Technologies, Inc.; Distributed under the GPL"
 	echo
 
-	ebegin "Mounting /proc"
-	try mount -n /proc
+	ebegin "Mounting /proc"; \
+	try mount -n /proc; \
 	eend $?
-	
+
+	#check if the user disabled devfs
 	devfs="yes"
 	get_bootparam "nodevfs"
-	if [ $? -eq 0 ]
+	if [ "$?" -eq 0 ]
 	then
 		devfs="no"
 	fi
 	
 	#fix wierd bug where there is a /dev/.devfsd in a unmounted /dev
-	mymounts="`cat /proc/mounts`"
+	mymounts="$(cat /proc/mounts)"
 	if [ -e /dev/.devfsd ] && [ "${mymounts/devfs//}" = "${mymounts}" ]
 	then
-		rm -f /dev/.devfsd >/dev/null 2>&1
+		rm -f /dev/.devfsd &>/dev/null
 	fi
 
 	#with the new way, /dev can be mounted by the kernel ...
-	if [ "$devfs" = "yes" ] && [ ! -e /dev/.devfsd ]
+	if [ "${devfs}" = "yes" ] && [ ! -e /dev/.devfsd ]
 	then
-		mymounts="`cat /proc/filesystems`"
+		mymounts="$(cat /proc/filesystems)"
 		#is devfs support compiled in?
 		if [ "${mymounts/devfs//}" != "${mymounts}" ]
 		then
-			ebegin "Mounting devfs at /dev"; try mount -n -t devfs none /dev; eend
+			ebegin "Mounting devfs at /dev"; \
+			try mount -n -t devfs none /dev; \
+			eend $?
 		else
 			clear
 			echo
@@ -77,47 +92,63 @@ then
 	fi
 
 	# need devfsd running now so that /dev/ram0 exists if we need it
-	mymounts="`cat /proc/mounts`"
-	if [ "$devfs" = "yes" ] && [ -e /dev/.devfsd ] && \
+	mymounts="$(cat /proc/mounts)"
+	if [ "${devfs}" = "yes" ] && [ -e /dev/.devfsd ] && \
 	   [ "${mymounts/devfs//}" != "${mymounts}" ]
 	then
-		ebegin "Starting devfsd"; /sbin/devfsd /dev >/dev/null 2>&1; eend $?
+		ebegin "Starting devfsd"
+		/sbin/devfsd /dev &>/dev/null
+		eend $?
 	fi
 
 	#mount either a ramdisk or tmpfs and do dep scan
 
+	#should we use tmpfs or a ramdisk ?
 	tmpfs="yes"
 	get_bootparam "notmpfs"
-	if [ $? -eq 0 ]
+	if [ "$?" -eq 0 ]
 	then
 		tmpfs="no"
 	fi
 
-	if [ ! -d $svcdir ]
+	if [ ! -d ${svcdir} ]
 	then
-		mkdir -p $svcdir >/dev/null 2>&1
+		echo
+		eerror "For Gentoo Linux to function properly, \"${svcdir}\" need to exist."
+		eerror "Please mount your root partition read/write, and execute:"
+		echo
+		eerror "  # mkdir -p ${svcdir}"
+		echo
+		echo
+		/sbin/sulogin ${CONSOLE}
+		mount -a -o remount,ro &>/dev/null
+		/sbin/reboot -f
 	fi
 	
-	if [ "$tmpfs" = "yes" ] ; then
-		ebegin "Mounting tmpfs at ${svcdir}"
-		try mount -n -t tmpfs tmpfs ${svcdir} -o rw,mode=0644,size=${svcsize}k
+	if [ "${tmpfs}" = "yes" ]
+	then
+		ebegin "Mounting tmpfs at ${svcdir}"; \
+		try mount -n -t tmpfs tmpfs ${svcdir} \
+			-o rw,mode=0644,size=${svcsize}k; \
 		eend 0
 	else
-		ebegin "Mounting ramdisk 0 at ${svcdir}"
-		try dd if=/dev/zero of=/dev/ram0 bs=1k count=$svcsize
-		try mke2fs -vm0 /dev/ram0 $svcsize
-		try mount -n -t ext2 /dev/ram0 ${svcdir} -o rw
+		ebegin "Mounting ramdisk 0 at ${svcdir}"; \
+		try dd if=/dev/zero of=/dev/ram0 bs=1k count=${svcsize}; \
+		try /sbin/mke2fs -vm0 /dev/ram0 ${svcsize}; \
+		try mount -n -t ext2 /dev/ram0 ${svcdir} -o rw; \
 		eend 0
 	fi
-			
-	/etc/init.d/depscan.sh
+	
+	ebegin "Caching service dependencies"; \
+	try /etc/init.d/depscan.sh; \
+	eend $?
 
 	#swap needs to be activated *after* devfs has been mounted and *after*
 	#devfsd has been started, so that the fstab can be properly parsed
 
 	ebegin "Activating swap"
-	swapon -a >/dev/null 2>&1
-	eend
+	/sbin/swapon -a &>/dev/null
+	eend 0
 
 	#set the console loglevel to 1 for a cleaner boot
 	#the logger should anyhow dump the ring-0 buffer at start to the
@@ -132,48 +163,49 @@ then
 	
 fi #boot ends here
 
-if [ -z "$argv1" ]
+if [ -z "${argv1}" ]
 then
 	if [ -e ${svcdir}/softlevel ]
 	then
-		export SOFTLEVEL="`cat ${svcdir}/softlevel`"
+		export SOFTLEVEL="$(cat ${svcdir}/softlevel)"
 	else
 		export SOFTLEVEL="boot"
 	fi
 else
-	export SOFTLEVEL="$argv1"
+	export SOFTLEVEL="${argv1}"
 fi
 
 #for keeping a list of services that fails during boot/halt
 if [ ! -d ${svcdir}/fails ]
 then
-	mkdir -p ${svcdir}/fails >/dev/null 2>&1
+	install -d -m0755 ${svcdir}/fails
 else
-	rm -rf ${svcdir}/fails/* >/dev/null 2>&1
+	rm -rf ${svcdir}/fails/*
 fi
 
-if [ "$SOFTLEVEL" = "reboot" ] || [ "$SOFTLEVEL" = "shutdown" ]
+if [ "${SOFTLEVEL}" = "reboot" ] || [ "${SOFTLEVEL}" = "shutdown" ]
 then
 	myscripts=""
 elif [ ! -d /etc/runlevels/${SOFTLEVEL} ]
 then
-	echo "runlevel ${SOFTLEVEL} does not exist; exiting."
+	eerror "ERROR:  runlevel ${SOFTLEVEL} does not exist; exiting..."
 	exit 1
 else
 	myscripts=""
-	if [ "$SOFTLEVEL" != "boot" ]
+	if [ "${SOFTLEVEL}" != "boot" ]
 	then
 		#normal runlevels *include* boot scripts
-		mylevels="/etc/runlevels/${SOFTLEVEL}/* /etc/runlevels/boot/*"
+		mylevels="$(dolisting /etc/runlevels/${SOFTLEVEL}/)"
+		mylevels="${mylevels} $(dolisting /etc/runlevels/boot/)"
 	else
 		#non-normal runlevels don't include boot scripts as default
-		mylevels="/etc/runlevels/${SOFTLEVEL}/*"
+		mylevels="$(dolisting /etc/runlevels/${SOFTLEVEL}/)"
 	fi
-	for x in $mylevels 
+	for x in ${mylevels}
 	do
-		if [ -L $x ]
+		if [ -L ${x} ]
 		then
-			myscripts="$myscripts ${x##*/}"
+			myscripts="${myscripts} ${x##*/}"
 		fi
 	done
 fi
@@ -185,11 +217,11 @@ fi
 
 install -d -m0755 ${svcdir}/softscripts.new
 
-for x in $myscripts
+for x in ${myscripts}
 do
 	if [ ! -e /etc/init.d/${x} ]
 	then
-		echo "skipping, /etc/init.d/${x} missing"
+		ewarn "WARNING:  /etc/init.d/${x} missing; skipping..."
 		continue
 	fi
 	#the -f eliminates a warning if the symlink already exists, 
@@ -210,7 +242,7 @@ dep_stop() {
 		rm ${1}
 		continue
 	fi
-	myservice=${1##*/}
+	myservice="${1##*/}"
 	
 	if [ ! -L ${svcdir}/softscripts.new/${myservice} ]
 	then
@@ -227,11 +259,12 @@ dep_stop() {
 		else
 			#something may depend on me
 			needsme=0
-			for mytype in need #use
+			for mytype in need
 			do
-				for dep in ${svcdir}/${mytype}/${myservice}/*
+				for dep in $(dolisting ${svcdir}/${mytype}/${myservice}/)
 				do
-					if [ -e ${dep} ] && [ -L /${svcdir}/softscripts.new/${dep##*/} ]
+					if [ -L ${svcdir}/softscripts.new/${dep##*/} ] && \
+					   [ -e ${dep} ]
 					then
 						#this dep is valid
 						needsme=1
@@ -239,7 +272,7 @@ dep_stop() {
 					fi
 				done
 			done
-			if [ $needsme -eq 0 ]
+			if [ "${needsme}" -eq 0 ]
 			then
 				if [ -L ${svcdir}/started/${myservice} ]
 				then
@@ -251,21 +284,21 @@ dep_stop() {
 }
 
 #stop services
-for i in ${svcdir}/started/*
+for i in $(dolisting ${svcdir}/started/)
 do
-	dep_stop $i
+	dep_stop ${i}
 done
 
 # Only change softlevel AFTER all the services have been stopped,
 # else they will not get the depend's right (wrong SOFTLEVEL)
 
-echo "$SOFTLEVEL" > ${svcdir}/softlevel
+echo "${SOFTLEVEL}" > ${svcdir}/softlevel
 
-if [ "$SOFTLEVEL" = "reboot" ] || [ "$SOFTLEVEL" = "shutdown" ]
+if [ "${SOFTLEVEL}" = "reboot" ] || [ "${SOFTLEVEL}" = "shutdown" ]
 then
 	source /etc/init.d/functions.sh
 	source /etc/init.d/halt.sh
-	if [ "$SOFTLEVEL" = "reboot" ]
+	if [ "${SOFTLEVEL}" = "reboot" ]
 	then
 		source /etc/init.d/reboot.sh 
 	else
@@ -276,50 +309,52 @@ fi
 #move the old softscritps directory to a different one
 #and make the new softscripts directory the current
 
-mv ${svcdir}/softscripts ${svcdir}/softscripts.old >/dev/null 2>&1
-mv ${svcdir}/softscripts.new/ ${svcdir}/softscripts >/dev/null 2>&1
+mv ${svcdir}/softscripts ${svcdir}/softscripts.old &>/dev/null
+mv ${svcdir}/softscripts.new ${svcdir}/softscripts &>/dev/null
 
 dep_start() {
 	local x=""
 	local myservice=""
 	local depservice=""
-	if [ ! -L $1 ]
+	if [ ! -L ${1} ]
 	then
 		continue
 	fi
 	#only start a script if it isn't already running
-	myservice=${1##*/}
+	myservice="${1##*/}"
 	if [ ! -L ${svcdir}/started/${myservice} ]
 	then
-		$1 start
+		${1} start
 	fi
 }
 
 #start scripts
-for i in ${svcdir}/softscripts/*
+for i in $(dolisting ${svcdir}/softscripts/)
 do
-	dep_start $i
+	dep_start ${i}
 done
 
 #clean the old runlevel
-rm -rf ${svcdir}/softscripts.old >/dev/null 2>&1
+rm -rf ${svcdir}/softscripts.old &>/dev/null
 
 #depends gets newked, so update them
 #(this problem should be solved now, but i think it will be a good idea
 # to recreate the deps after a change in runlevel)
 
-/etc/init.d/depscan.sh >/dev/null 2>&1
+#/etc/init.d/depscan.sh &>/dev/null
 
 #we want devfsd running after a change of runlevel (this is mostly if we return
 #from runlevel 'single')
-if [ "`cat /proc/mounts | grep -e '/dev devfs'`" ] && [ ! "`ps -A | grep devfsd`" ]
+if [ -z "$(ps -A | grep devfsd)" ] && \
+   [ -n "$(cat mounts | grep -e '/dev devfs')" ]
 then
-	/sbin/devfsd /dev >/dev/null 2>&1
+	/sbin/devfsd /dev &>/dev/null
 fi
 
 #runlevel end, so clear stale fail list
-rm -rf ${svcdir}/fails >/dev/null 2>&1
+rm -rf ${svcdir}/fails &>/dev/null
 
 #if we were in the boot runlevel, it is done now ...
-[ -n "$BOOT" ] && unset BOOT
+[ -n "${BOOT}" ] && unset BOOT
 
+# vim:ts=4
