cvs diff: etc/conf.d/cryptfs is a new entry, no comparison available
    Add the default cryptfs configuration file

 init.d/checkfs    |  146 +++++++++++++++++++++++++++++++-----------------------
 init.d/localmount |  111 +++++++++++++++++++++++++++--------------

    Minor fixes to tigger's dm-crypt stuff that resulted in some
    rewriting.  Don't set status in a subshell so success/failure is
    preserved.  Allow multi-line configuration files

 ChangeLog         |    9 ++-
 tarball.sh        |    2

    Update to version 1.6.1

 4 files changed, 167 insertions(+), 101 deletions(-)

svn path=/trunk/; revision=566

diff --git a/init.d/checkfs b/init.d/checkfs
--- a/init.d/checkfs
+++ b/init.d/checkfs
@@ -179,69 +179,9 @@ start() {
 		eend $? "Failed to setup the LVM"
 	fi
 
-
 	ebegin 'Setting up dm-crypt mappings'
-
-	if [ -f /etc/conf.d/cryptfs ]
-	then
-		cryptfs_status=0
-
-		/bin/egrep '^(mount|swap)' /etc/conf.d/cryptfs | \
-		while read mountline
-		do
-			mount=
-			swap=
-			options=
-			pre_mount=
-
-			eval ${mountline}
-
-			if [ -n "${mount}" ]
-			then
-				target=${mount}
-				[ -z "${options}" ] && options='-c aes -h sha1'
-			elif [ -n "${swap}" ]
-			then
-				target=${swap}
-				[ -z "${options}" ] && options='-c aes -h sha1 -d /dev/urandom'
-			else
-				ewarn "Invalid line in /etc/conf.d/cryptomount: ${mountline}"
-			fi
-
-			! /bin/cryptsetup status ${target}|egrep '\<active:' > /dev/null
-			configured=$?
-
-			if [ ${configured} -eq 0 ]
-			then
-				einfo "dm-crypt map ${target}"
-				if ! /bin/cryptsetup ${options} create ${target} ${source} >/dev/console </dev/console
-				then
-					ewarn "Failure configuring ${target}"
-					cryptfs_status=1
-				else
-					if [ -n "${swap}" ]
-					then
-						[ -z "${pre_mount}" ] && pre_mount='mkswap ${dev}'
-					fi
-
-					if [ -n "${pre_mount}" ]
-					then
-						dev="/dev/mapper/${target}"
-						einfo "  Running pre_mount commands on: ${target}"
-						if ! eval "${pre_mount}" > /dev/null
-						then
-							ewarn "Failed to run pre_mount commands on: ${target}"
-							cryptfs_status=1
-						fi
-					fi
-				fi
-			else
-				ewarn "dm-crypt mapping ${target} is already configured"
-				cryptfs_status=1
-			fi
-		done
-	fi
-	ewend ${cryptfs_status} 'Failed to setup a mapping or swap device.'
+	dm-crypt-start
+	ewend $? 'Failed to setup a mapping or swap device'
 
 	if [ -f /fastboot -o -n "${CDBOOT}" ]
 	then
@@ -269,6 +209,88 @@ start() {
 		else
 			eend 2 "Fsck could not correct all errors, manual repair needed"
 			/sbin/sulogin ${CONSOLE}
+		fi
+	fi
+}
+
+# Note: This function is exactly duplicated in localmount.  If you change it
+# here, make sure to change it there also!
+dm-crypt-start() {
+	local cryptfs_status=0 
+	local mountline mount swap options pre_mount post_mount source
+
+	if [ -f /etc/conf.d/cryptfs ]; then
+		while read mountline; do
+			# skip comments and blank lines
+			[[ ${mountline}\# == \#* ]] && continue
+
+			# check for the start of a new mount/swap
+			case ${mountline} in
+				mount=*|swap=*)
+					# If we have a mount queued up, then execute it
+					dm-crypt-execute
+
+					# Prepare for the next mount/swap by resetting variables
+					unset mount swap options pre_mount post_mount source
+					;;
+
+				options=*|pre_mount=*|post_mount=*|source=*)
+					if [[ -z ${mount} && -z ${swap} ]]; then
+						ewarn "Ignoring setting outside mount/swap section: ${mountline}"
+						continue
+					fi
+					;;
+
+				*)
+					ewarn "Skipping invalid line in /etc/conf.d/cryptfs: ${mountline}"
+					;;
+			esac
+
+			# Queue this setting for the next call to dm-crypt-execute
+			eval "${mountline}"
+		done < /etc/conf.d/cryptfs
+
+		# If we have a mount queued up, then execute it
+		dm-crypt-execute
+	fi
+
+	return ${cryptfs_status}
+}
+
+# Setup mappings for an individual mount/swap
+#
+# Note: This relies on variables localized in dm-crypt-start.  This function
+# is quite different from the function by the same name in localmount...
+dm-crypt-execute() {
+	local dev target
+
+	if [[ -n ${mount} ]]; then
+		target=${mount}
+		: ${options:='-c aes -h sha1'}
+	elif [[ -n ${swap} ]]; then
+		target=${swap}
+		: ${options:='-c aes -h sha1 -d /dev/urandom'}
+		: ${pre_mount:='mkswap ${dev}'}
+	else
+		return
+	fi
+
+	if /bin/cryptsetup status ${target} | egrep -q '\<active:'; then
+		einfo "dm-crypt mapping ${target} is already configured"
+		return
+	fi
+
+	ebegin "dm-crypt map ${target}"
+	/bin/cryptsetup ${options} create ${target} ${source} >/dev/console </dev/console
+	eend $? "failure running cryptsetup"
+	if [[ $? != 0 ]]; then
+		cryptfs_status=1
+	else
+		if [[ -n ${pre_mount} ]]; then
+			dev="/dev/mapper/${target}"
+			ebegin "  Running pre_mount commands for ${target}"
+			eval "${pre_mount}" > /dev/null
+			ewend $? || cryptfs_status=1
 		fi
 	fi
 }
diff --git a/init.d/localmount b/init.d/localmount
--- a/init.d/localmount
+++ b/init.d/localmount
@@ -42,48 +42,85 @@ start() {
 	/sbin/swapon -a &>/dev/null
 	eend 0
 
-	# Run any post_mount commands for cryptfs
-
-	if [ -f /etc/conf.d/cryptfs ]
-	then
-		ebegin "Running post_mount commands for cryptfs"
-
-		/bin/egrep "^mount" /etc/conf.d/cryptfs | \
-		while read mountline
-		do
-			mount=
-			mount_point=
-			post_mount=
-
-			eval ${mountline}
-
-			target=${mount}
-
-			! /bin/cryptsetup status ${target}|egrep '\<active:' > /dev/null
-			configured=$?
-
-			if [ ${configured} -eq 1 ]
-			then
-				mount_point=`/bin/awk "/\/dev\/mapper\/${target}/ { print \\$2 }" /proc/mounts`
-				if [ -n "${mount_point}" ]
-				then
-					if [ -n "${post_mount}" ]
-					then
-						if ! eval "${post_mount}" > /dev/null
-						then
-							ewarn "Failed to run post_mount commands on: ${target}"
-						fi
-					fi
-				else
-					ewarn "Failed to find mount point to ${target}. Skipping"
-				fi
-			else
-				ewarn "Target ${target} wasn't mapped, skipping"
-			fi
-
-		done
-	fi
+	ebegin 'Running post_mount commands for dm-crypt'
+	dm-crypt-start
+	ewend $? 'Failed to run a post_mount command'
 }
 
+# Note: This function is exactly duplicated in localmount.  If you change it
+# here, make sure to change it there also!
+dm-crypt-start() {
+	local cryptfs_status=0 
+	local mountline mount swap options pre_mount post_mount source
+
+	if [ -f /etc/conf.d/cryptfs ]; then
+		while read mountline; do
+			# skip comments and blank lines
+			[[ ${mountline}\# == \#* ]] && continue
+
+			# check for the start of a new mount/swap
+			case ${mountline} in
+				mount=*|swap=*)
+					# If we have a mount queued up, then execute it
+					dm-crypt-execute
+
+					# Prepare for the next mount/swap by resetting variables
+					unset mount swap options pre_mount post_mount source
+					;;
+
+				options=*|pre_mount=*|post_mount=*|source=*)
+					if [[ -z ${mount} && -z ${swap} ]]; then
+						ewarn "Ignoring setting outside mount/swap section: ${mountline}"
+						continue
+					fi
+					;;
+
+				*)
+					ewarn "Skipping invalid line in /etc/conf.d/cryptfs: ${mountline}"
+					;;
+			esac
+
+			# Queue this setting for the next call to dm-crypt-execute
+			eval "${mountline}"
+		done < /etc/conf.d/cryptfs
+
+		# If we have a mount queued up, then execute it
+		dm-crypt-execute
+	fi
+
+	return ${cryptfs_status}
+}
+
+# Run any post_mount commands for an individual mount
+#
+# Note: This relies on variables localized in dm-crypt-start.  This function
+# is quite different from the function by the same name in checkfs...
+dm-crypt-execute() {
+	local mount_point target
+
+	if [[ -n ${mount} && -n ${post_mount} ]]; then
+		target=${mount}
+	else
+		return
+	fi
+
+	if ! /bin/cryptsetup status ${target} | egrep -q '\<active:'; then
+		ewarn "Skipping unmapped target ${target}"
+		cryptfs_status=1
+		return
+	fi
+
+	mount_point=$(grep "/dev/mapper/${target}" /proc/mounts | cut -d' ' -f2)
+	if [[ -z ${mount_point} ]]; then
+		ewarn "Failed to find mount point for ${target}, skipping"
+		cryptfs_status=1
+	fi
+
+	if [[ -n ${post_mount} ]]; then
+		ebegin "Running post_mount commands for target ${target}"
+		eval "${post_mount}" >/dev/null
+		eend $? || cryptfs_status=1
+	fi
+}
 
 # vim:ts=4
