handle read only filesystems nicer
svn path=/trunk/; revision=630

diff --git a/init.d/domainname b/init.d/domainname
--- a/init.d/domainname
+++ b/init.d/domainname
@@ -23,6 +23,15 @@ checkconfig_dns() {
 #		eerror "You need to set /etc/dnsdomainname to a valid DNS domainname"
 		return 1
 	fi
+
+	mydnsdomain="$(< /etc/dnsdomainname)"
+
+	if ! touch /etc/dnsdomainname 2> /dev/null
+	then
+		ewarn "Unable to set domain in resolv.conf (ro root?)"
+		return 1
+	fi
+
 	return 0
 }
 
@@ -30,8 +39,8 @@ start() {
 	local mynisdomain=
 	local mydnsdomain=
 	local retval=0
-	local retval2=2
-	
+	local retval2=0
+
 	if checkconfig_nis
 	then
 		mynisdomain="$(< /etc/nisdomainname)"
@@ -45,8 +54,6 @@ start() {
 
 	if checkconfig_dns
 	then
-		mydnsdomain="$(< /etc/dnsdomainname)"
-
 		[ ! -f /etc/resolv.conf ] && touch /etc/resolv.conf
 		ebegin "Setting DNS domainname to ${mydnsdomain}"
 		gawk -v DOMAIN="${mydnsdomain}" \
@@ -60,9 +67,7 @@ start() {
 		eend ${retval2} "Failed to set the DNS domainname"
 	fi
 
-	retval=$((retval + retval2))
-	
-	return ${retval}
+	return $((retval + retval2))
 }
 
 
diff --git a/sbin/rc b/sbin/rc
--- a/sbin/rc
+++ b/sbin/rc
@@ -337,6 +337,16 @@ then
 			break
 		fi
 	done
+	if [ "${svcmount}" == "no" ]
+	then
+		# Check to see if current svcdir is writable, and
+		# if it isn't (readonly filesystem?), mount on ramdisk
+		if ! touch -c "${svcdir}" 2> /dev/null
+		then
+			ewarn "Could not use '${svcdir}', mounting ramdisk (ro root?)"
+			svcmount="yes"
+		fi
+	fi
 	if [ "${svcmount}" == "yes" ]
 	then
 		check_statedir "${tsvcdir}"
@@ -359,7 +369,6 @@ then
 		esac
 		eend 0
 	fi
-
 
 	# Swap needs to be activated *after* devfs has been mounted and *after*
 	# devfsd has been started, so that the fstab can be properly parsed
@@ -431,8 +440,8 @@ then
 	# Check that $svcdir exists ...
 	check_statedir "${svcdir}"
 
-	# Since we are using tmpfs or ramfs, just bin to $tsvcdir to $svcdir
-	if get_bootparam "tmpfs" || get_bootparam "ramfs" || [ "${svcmount}" = "yes" ]
+	# Since we are mounting the svcdir in ram, bind it over
+	if [ "${svcmount}" == "yes" ]
 	then
 		mount --bind "${tsvcdir}" "${svcdir}"
 	fi
@@ -466,12 +475,18 @@ then
 
 	# Setup login records ... this has to be done here because when 
 	# we exit this runlevel, init will write a boot record to utmp
-	> /var/run/utmp
-	touch /var/log/wtmp
-	chgrp utmp /var/run/utmp /var/log/wtmp
-	chmod 0664 /var/run/utmp /var/log/wtmp
-	# Remove /var/run/utmpx (bug from the past)
-	rm -f /var/run/utmpx
+	# If /var/run is readonly, then print a warning, not errors
+	if touch /var/run/utmp 2> /dev/null
+	then
+		> /var/run/utmp
+		touch /var/log/wtmp
+		chgrp utmp /var/run/utmp /var/log/wtmp
+		chmod 0664 /var/run/utmp /var/log/wtmp
+		# Remove /var/run/utmpx (bug from the past)
+		rm -f /var/run/utmpx
+	else
+		ewarn "Skipping /var/run/utmp initialization (ro root?)"
+	fi
 
 	exit 0
 fi # Sysinit ends here
